import type { AssetRecord } from './types';

/**
 * ETFs, crypto, commodity proxies, and popular non-S&P-500 stocks not covered
 * by the S&P 500 constituent list. searchableTerms drive intent queries.
 */
export const EXTRA_INSTRUMENTS: readonly AssetRecord[] = [
    // ─── Crypto ──────────────────────────────────────────────────────────────
    {
        symbol: 'BTC-USD',
        name: 'Bitcoin',
        type: 'crypto',
        exchange: 'CCY',
        searchableTerms: ['bitcoin', 'btc', 'crypto', 'digital gold'],
    },
    {
        symbol: 'ETH-USD',
        name: 'Ethereum',
        type: 'crypto',
        exchange: 'CCY',
        searchableTerms: ['ethereum', 'eth', 'crypto', 'ether'],
    },
    {
        symbol: 'SOL-USD',
        name: 'Solana',
        type: 'crypto',
        exchange: 'CCY',
        searchableTerms: ['solana', 'sol', 'crypto'],
    },
    {
        symbol: 'XRP-USD',
        name: 'XRP',
        type: 'crypto',
        exchange: 'CCY',
        searchableTerms: ['xrp', 'ripple', 'crypto'],
    },
    {
        symbol: 'DOGE-USD',
        name: 'Dogecoin',
        type: 'crypto',
        exchange: 'CCY',
        searchableTerms: ['dogecoin', 'doge', 'crypto', 'meme coin'],
    },
    {
        symbol: 'ADA-USD',
        name: 'Cardano',
        type: 'crypto',
        exchange: 'CCY',
        searchableTerms: ['cardano', 'ada', 'crypto'],
    },
    {
        symbol: 'AVAX-USD',
        name: 'Avalanche',
        type: 'crypto',
        exchange: 'CCY',
        searchableTerms: ['avalanche', 'avax', 'crypto'],
    },
    {
        symbol: 'LINK-USD',
        name: 'Chainlink',
        type: 'crypto',
        exchange: 'CCY',
        searchableTerms: ['chainlink', 'link', 'crypto', 'oracle'],
    },
    {
        symbol: 'LTC-USD',
        name: 'Litecoin',
        type: 'crypto',
        exchange: 'CCY',
        searchableTerms: ['litecoin', 'ltc', 'crypto', 'silver bitcoin'],
    },
    {
        symbol: 'DOT-USD',
        name: 'Polkadot',
        type: 'crypto',
        exchange: 'CCY',
        searchableTerms: ['polkadot', 'dot', 'crypto'],
    },

    // ─── S&P 500 Index ETFs ───────────────────────────────────────────────────
    {
        symbol: 'SPY',
        name: 'SPDR S&P 500 ETF Trust',
        type: 'etf',
        exchange: 'US',
        sector: 'Index',
        searchableTerms: ['s&p 500', 's&p500', 'sp500', 'sp 500', 'sandp', 's and p 500', 'index', 'large cap blend', 'spdr'],
    },
    {
        symbol: 'VOO',
        name: 'Vanguard S&P 500 ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Index',
        searchableTerms: ['s&p 500', 's&p500', 'sp500', 'sp 500', 'sandp', 'vanguard s&p', 'vanguard'],
    },
    {
        symbol: 'IVV',
        name: 'iShares Core S&P 500 ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Index',
        searchableTerms: ['s&p 500', 's&p500', 'sp500', 'sp 500', 'ishares s&p', 'ishares', 'blackrock'],
    },
    {
        symbol: 'IVW',
        name: 'iShares S&P 500 Growth ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Index',
        searchableTerms: ['s&p growth', 'large cap growth', 'ishares growth'],
    },
    {
        symbol: 'IVE',
        name: 'iShares S&P 500 Value ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Index',
        searchableTerms: ['s&p value', 'large cap value', 'ishares value'],
    },
    {
        symbol: 'SPYG',
        name: 'SPDR Portfolio S&P 500 Growth ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Index',
        searchableTerms: ['s&p growth', 'large cap growth', 'spdr growth'],
    },
    {
        symbol: 'SPYV',
        name: 'SPDR Portfolio S&P 500 Value ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Index',
        searchableTerms: ['s&p value', 'large cap value', 'spdr value'],
    },

    // ─── Nasdaq Index ETFs ────────────────────────────────────────────────────
    {
        symbol: 'QQQ',
        name: 'Invesco QQQ Trust',
        type: 'etf',
        exchange: 'US',
        sector: 'Index',
        searchableTerms: ['nasdaq', 'nasdaq 100', 'ndx', 'tech heavy', 'qqq', 'invesco'],
    },
    {
        symbol: 'QQQM',
        name: 'Invesco NASDAQ 100 ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Index',
        searchableTerms: ['nasdaq', 'nasdaq 100', 'qqq', 'qqqm', 'invesco'],
    },

    // ─── Total Market ETFs ────────────────────────────────────────────────────
    {
        symbol: 'VTI',
        name: 'Vanguard Total Stock Market ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Index',
        searchableTerms: ['total market', 'vti', 'broad market', 'vanguard total'],
    },
    {
        symbol: 'SCHB',
        name: 'Schwab U.S. Broad Market ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Index',
        searchableTerms: ['broad market', 'total market', 'schwab', 'schb'],
    },

    // ─── Dow Jones ETF ────────────────────────────────────────────────────────
    {
        symbol: 'DIA',
        name: 'SPDR Dow Jones Industrial Average ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Index',
        searchableTerms: ['dow', 'dow jones', 'industrial average', 'dia', 'djia'],
    },

    // ─── Russell 2000 ETFs ────────────────────────────────────────────────────
    {
        symbol: 'IWM',
        name: 'iShares Russell 2000 ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Index',
        searchableTerms: ['russell 2000', 'small cap', 'iwm', 'ishares russell'],
    },
    {
        symbol: 'IJR',
        name: 'iShares Core S&P Small-Cap ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Index',
        searchableTerms: ['small cap', 'small cap index', 's&p smallcap 600'],
    },

    // ─── Mid-Cap ETFs ─────────────────────────────────────────────────────────
    {
        symbol: 'IJH',
        name: 'iShares Core S&P Mid-Cap ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Index',
        searchableTerms: ['mid cap', 'midcap', 's&p midcap 400', 'ishares mid cap'],
    },
    {
        symbol: 'MDY',
        name: 'SPDR S&P MidCap 400 ETF Trust',
        type: 'etf',
        exchange: 'US',
        sector: 'Index',
        searchableTerms: ['mid cap', 'midcap', 's&p 400', 'mdy'],
    },

    // ─── Growth / Value ETFs ─────────────────────────────────────────────────
    {
        symbol: 'SCHG',
        name: 'Schwab U.S. Large-Cap Growth ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Index',
        searchableTerms: ['growth', 'large cap growth', 'schwab growth'],
    },
    {
        symbol: 'SCHV',
        name: 'Schwab U.S. Large-Cap Value ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Index',
        searchableTerms: ['value', 'large cap value', 'schwab value'],
    },

    // ─── Dividend ETFs ────────────────────────────────────────────────────────
    {
        symbol: 'SCHD',
        name: 'Schwab U.S. Dividend Equity ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Dividend',
        searchableTerms: ['dividend', 'schd', 'quality dividend', 'schwab dividend'],
    },
    {
        symbol: 'VIG',
        name: 'Vanguard Dividend Appreciation ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Dividend',
        searchableTerms: ['dividend', 'dividend growth', 'vanguard dividend', 'vig'],
    },
    {
        symbol: 'HDV',
        name: 'iShares Core High Dividend ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Dividend',
        searchableTerms: ['high dividend', 'dividend income', 'hdv'],
    },
    {
        symbol: 'NOBL',
        name: 'ProShares S&P 500 Dividend Aristocrats ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Dividend',
        searchableTerms: ['dividend aristocrats', 'aristocrats', 'dividend growth', 'nobl'],
    },
    {
        symbol: 'SDY',
        name: 'SPDR S&P Dividend ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Dividend',
        searchableTerms: ['dividend', 'high yield dividend', 'sdy'],
    },

    // ─── Sector ETFs (SPDR complete suite) ───────────────────────────────────
    {
        symbol: 'XLF',
        name: 'Financial Select Sector SPDR Fund',
        type: 'etf',
        exchange: 'US',
        sector: 'Financials',
        searchableTerms: ['financials', 'banks', 'xlf', 'sector financials', 'finance sector'],
    },
    {
        symbol: 'XLK',
        name: 'Technology Select Sector SPDR Fund',
        type: 'etf',
        exchange: 'US',
        sector: 'Technology',
        searchableTerms: ['technology sector', 'tech sector', 'xlk'],
    },
    {
        symbol: 'XLE',
        name: 'Energy Select Sector SPDR Fund',
        type: 'etf',
        exchange: 'US',
        sector: 'Energy',
        searchableTerms: ['energy sector', 'oil gas', 'xle'],
    },
    {
        symbol: 'XLV',
        name: 'Health Care Select Sector SPDR Fund',
        type: 'etf',
        exchange: 'US',
        sector: 'Health Care',
        searchableTerms: ['health care sector', 'healthcare sector', 'xlv'],
    },
    {
        symbol: 'XLI',
        name: 'Industrial Select Sector SPDR Fund',
        type: 'etf',
        exchange: 'US',
        sector: 'Industrials',
        searchableTerms: ['industrials sector', 'industrial etf', 'xli'],
    },
    {
        symbol: 'XLY',
        name: 'Consumer Discretionary Select Sector SPDR Fund',
        type: 'etf',
        exchange: 'US',
        sector: 'Consumer Discretionary',
        searchableTerms: ['consumer discretionary', 'retail sector', 'xly'],
    },
    {
        symbol: 'XLP',
        name: 'Consumer Staples Select Sector SPDR Fund',
        type: 'etf',
        exchange: 'US',
        sector: 'Consumer Staples',
        searchableTerms: ['consumer staples', 'staples sector', 'xlp'],
    },
    {
        symbol: 'XLB',
        name: 'Materials Select Sector SPDR Fund',
        type: 'etf',
        exchange: 'US',
        sector: 'Materials',
        searchableTerms: ['materials sector', 'basic materials', 'xlb'],
    },
    {
        symbol: 'XLRE',
        name: 'Real Estate Select Sector SPDR Fund',
        type: 'etf',
        exchange: 'US',
        sector: 'Real Estate',
        searchableTerms: ['real estate sector', 'reit sector', 'xlre'],
    },
    {
        symbol: 'XLU',
        name: 'Utilities Select Sector SPDR Fund',
        type: 'etf',
        exchange: 'US',
        sector: 'Utilities',
        searchableTerms: ['utilities sector', 'utility etf', 'xlu'],
    },
    {
        symbol: 'XLC',
        name: 'Communication Services Select Sector SPDR Fund',
        type: 'etf',
        exchange: 'US',
        sector: 'Communication Services',
        searchableTerms: ['communication services', 'telecom sector', 'xlc'],
    },

    // ─── Real Estate ETFs ─────────────────────────────────────────────────────
    {
        symbol: 'VNQ',
        name: 'Vanguard Real Estate ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Real Estate',
        searchableTerms: ['reit', 'real estate', 'vnq', 'vanguard reit'],
    },

    // ─── Semiconductor ETFs ───────────────────────────────────────────────────
    {
        symbol: 'SMH',
        name: 'VanEck Semiconductor ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Technology',
        searchableTerms: ['semiconductor', 'semis', 'chips', 'smh', 'vaneck semiconductor'],
    },
    {
        symbol: 'SOXX',
        name: 'iShares Semiconductor ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Technology',
        searchableTerms: ['semiconductor', 'semis', 'chips', 'soxx', 'ishares semiconductor'],
    },

    // ─── Biotech ETFs ─────────────────────────────────────────────────────────
    {
        symbol: 'IBB',
        name: 'iShares Biotechnology ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Health Care',
        searchableTerms: ['biotech', 'biotechnology', 'ibb', 'ishares biotech'],
    },
    {
        symbol: 'XBI',
        name: 'SPDR S&P Biotech ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Health Care',
        searchableTerms: ['biotech', 'biotechnology', 'xbi', 'small cap biotech'],
    },

    // ─── Thematic / Innovation ETFs ───────────────────────────────────────────
    {
        symbol: 'ARKK',
        name: 'ARK Innovation ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Thematic',
        searchableTerms: ['ark', 'innovation', 'cathie wood', 'arkk', 'disruptive'],
    },
    {
        symbol: 'ARKG',
        name: 'ARK Genomic Revolution ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Health Care',
        searchableTerms: ['ark', 'genomics', 'gene editing', 'arkg', 'cathie wood'],
    },
    {
        symbol: 'ARKW',
        name: 'ARK Next Generation Internet ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Technology',
        searchableTerms: ['ark', 'internet', 'next gen internet', 'arkw', 'cathie wood'],
    },
    {
        symbol: 'ARKF',
        name: 'ARK Fintech Innovation ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Financials',
        searchableTerms: ['ark', 'fintech', 'financial technology', 'arkf', 'cathie wood'],
    },

    // ─── Banking / Finance ETFs ───────────────────────────────────────────────
    {
        symbol: 'KRE',
        name: 'SPDR S&P Regional Banking ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Financials',
        searchableTerms: ['regional banks', 'banking', 'kre', 'regional banking'],
    },
    {
        symbol: 'KBWB',
        name: 'Invesco KBW Bank ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Financials',
        searchableTerms: ['banks', 'kbw bank', 'banking etf', 'kbwb'],
    },

    // ─── Energy ETFs ─────────────────────────────────────────────────────────
    {
        symbol: 'OIH',
        name: 'VanEck Oil Services ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Energy',
        searchableTerms: ['oil services', 'oilfield services', 'oih'],
    },
    {
        symbol: 'XOP',
        name: 'SPDR S&P Oil & Gas Exploration & Production ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Energy',
        searchableTerms: ['oil exploration', 'oil gas production', 'xop', 'e&p'],
    },

    // ─── Clean Energy ETFs ────────────────────────────────────────────────────
    {
        symbol: 'ICLN',
        name: 'iShares Global Clean Energy ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Energy',
        searchableTerms: ['clean energy', 'renewable energy', 'solar wind', 'icln', 'green energy'],
    },

    // ─── International ETFs ───────────────────────────────────────────────────
    {
        symbol: 'EFA',
        name: 'iShares MSCI EAFE ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'International',
        searchableTerms: ['international', 'developed markets', 'europe asia', 'efa', 'eafe'],
    },
    {
        symbol: 'VEA',
        name: 'Vanguard FTSE Developed Markets ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'International',
        searchableTerms: ['international', 'developed markets', 'vanguard international', 'vea'],
    },
    {
        symbol: 'EEM',
        name: 'iShares MSCI Emerging Markets ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'International',
        searchableTerms: ['emerging markets', 'eem', 'developing markets', 'ishares emerging'],
    },
    {
        symbol: 'VWO',
        name: 'Vanguard FTSE Emerging Markets ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'International',
        searchableTerms: ['emerging markets', 'vwo', 'vanguard emerging'],
    },
    {
        symbol: 'EWJ',
        name: 'iShares MSCI Japan ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'International',
        searchableTerms: ['japan', 'japanese stocks', 'ewj'],
    },
    {
        symbol: 'EWZ',
        name: 'iShares MSCI Brazil ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'International',
        searchableTerms: ['brazil', 'brazilian stocks', 'ewz', 'latin america'],
    },
    {
        symbol: 'FXI',
        name: 'iShares China Large-Cap ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'International',
        searchableTerms: ['china', 'chinese stocks', 'fxi'],
    },
    {
        symbol: 'MCHI',
        name: 'iShares MSCI China ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'International',
        searchableTerms: ['china', 'chinese stocks', 'msci china', 'mchi'],
    },
    {
        symbol: 'KWEB',
        name: 'KraneShares CSI China Internet ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'International',
        searchableTerms: ['china internet', 'chinese tech', 'kweb', 'kraneshares'],
    },

    // ─── Bond / Fixed Income ETFs ─────────────────────────────────────────────
    {
        symbol: 'AGG',
        name: 'iShares Core U.S. Aggregate Bond ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Fixed Income',
        searchableTerms: ['bonds', 'fixed income', 'aggregate bond', 'agg', 'core bond'],
    },
    {
        symbol: 'BND',
        name: 'Vanguard Total Bond Market ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Fixed Income',
        searchableTerms: ['bonds', 'total bond', 'vanguard bond', 'bnd'],
    },
    {
        symbol: 'TLT',
        name: 'iShares 20+ Year Treasury Bond ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Fixed Income',
        searchableTerms: ['treasury bonds', 'long term bonds', 'government bonds', 'tlt', '20 year treasury'],
    },
    {
        symbol: 'IEF',
        name: 'iShares 7-10 Year Treasury Bond ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Fixed Income',
        searchableTerms: ['treasury bonds', 'intermediate bonds', 'ief', '10 year treasury'],
    },
    {
        symbol: 'SHY',
        name: 'iShares 1-3 Year Treasury Bond ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Fixed Income',
        searchableTerms: ['short term bonds', 'treasury bills', 'shy', '2 year treasury'],
    },
    {
        symbol: 'BIL',
        name: 'SPDR Bloomberg 1-3 Month T-Bill ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Fixed Income',
        searchableTerms: ['t-bills', 'treasury bills', 'cash equivalent', 'bil', 'money market'],
    },
    {
        symbol: 'HYG',
        name: 'iShares iBoxx $ High Yield Corporate Bond ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Fixed Income',
        searchableTerms: ['high yield bonds', 'junk bonds', 'corporate bonds', 'hyg'],
    },
    {
        symbol: 'LQD',
        name: 'iShares iBoxx $ Investment Grade Corporate Bond ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Fixed Income',
        searchableTerms: ['investment grade bonds', 'corporate bonds', 'lqd'],
    },

    // ─── Gold / Precious Metals ETFs ──────────────────────────────────────────
    {
        symbol: 'GLD',
        name: 'SPDR Gold Shares',
        type: 'commodity_proxy',
        exchange: 'US',
        sector: 'Commodities',
        searchableTerms: ['gold', 'bullion', 'precious metal', 'gld', 'gold etf'],
    },
    {
        symbol: 'IAU',
        name: 'iShares Gold Trust',
        type: 'commodity_proxy',
        exchange: 'US',
        sector: 'Commodities',
        searchableTerms: ['gold', 'bullion', 'precious metal', 'iau'],
    },
    {
        symbol: 'SGOL',
        name: 'abrdn Physical Gold Shares ETF',
        type: 'commodity_proxy',
        exchange: 'US',
        sector: 'Commodities',
        searchableTerms: ['gold', 'bullion', 'sgol', 'physical gold'],
    },
    {
        symbol: 'GDX',
        name: 'VanEck Gold Miners ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Materials',
        searchableTerms: ['gold miners', 'mining', 'gdx', 'gold stocks', 'vaneck gold'],
    },
    {
        symbol: 'GDXJ',
        name: 'VanEck Junior Gold Miners ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Materials',
        searchableTerms: ['junior gold miners', 'small gold miners', 'gdxj', 'gold mining'],
    },
    {
        symbol: 'NUGT',
        name: 'Direxion Daily Gold Miners Bull 2X Shares',
        type: 'etf',
        exchange: 'US',
        sector: 'Materials',
        searchableTerms: ['gold miners', 'leveraged gold', 'nugt', 'direxion gold'],
    },

    // ─── Silver ETFs ──────────────────────────────────────────────────────────
    {
        symbol: 'SLV',
        name: 'iShares Silver Trust',
        type: 'commodity_proxy',
        exchange: 'US',
        sector: 'Commodities',
        searchableTerms: ['silver', 'precious metal', 'slv', 'silver etf'],
    },
    {
        symbol: 'SIVR',
        name: 'abrdn Physical Silver Shares ETF',
        type: 'commodity_proxy',
        exchange: 'US',
        sector: 'Commodities',
        searchableTerms: ['silver', 'sivr', 'precious metal', 'physical silver'],
    },

    // ─── Other Commodity ETFs ─────────────────────────────────────────────────
    {
        symbol: 'COPX',
        name: 'Global X Copper Miners ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Materials',
        searchableTerms: ['copper', 'miners', 'copx', 'copper mining'],
    },
    {
        symbol: 'DBC',
        name: 'Invesco DB Commodity Index Tracking Fund',
        type: 'commodity_proxy',
        exchange: 'US',
        sector: 'Commodities',
        searchableTerms: ['commodities', 'commodity index', 'dbc', 'broad commodities'],
    },
    {
        symbol: 'PDBC',
        name: 'Invesco Optimum Yield Diversified Commodity Strategy ETF',
        type: 'commodity_proxy',
        exchange: 'US',
        sector: 'Commodities',
        searchableTerms: ['commodities', 'diversified commodities', 'pdbc'],
    },
    {
        symbol: 'DBA',
        name: 'Invesco DB Agriculture Fund',
        type: 'commodity_proxy',
        exchange: 'US',
        sector: 'Commodities',
        searchableTerms: ['agriculture', 'farming', 'food commodities', 'dba', 'grains'],
    },

    // ─── Oil & Natural Gas ETFs ───────────────────────────────────────────────
    {
        symbol: 'USO',
        name: 'United States Oil Fund',
        type: 'commodity_proxy',
        exchange: 'US',
        sector: 'Energy',
        searchableTerms: ['oil', 'crude', 'wti', 'uso', 'crude oil'],
    },
    {
        symbol: 'UNG',
        name: 'United States Natural Gas Fund',
        type: 'commodity_proxy',
        exchange: 'US',
        sector: 'Energy',
        searchableTerms: ['natural gas', 'ung', 'natgas'],
    },

    // ─── Leveraged & Inverse ETFs ─────────────────────────────────────────────
    {
        symbol: 'TQQQ',
        name: 'ProShares UltraPro QQQ',
        type: 'etf',
        exchange: 'US',
        sector: 'Leveraged',
        searchableTerms: ['leveraged nasdaq', 'triple qqq', 'tqqq', '3x nasdaq', 'proshares'],
    },
    {
        symbol: 'SQQQ',
        name: 'ProShares UltraPro Short QQQ',
        type: 'etf',
        exchange: 'US',
        sector: 'Leveraged',
        searchableTerms: ['inverse nasdaq', 'short nasdaq', 'sqqq', 'bear nasdaq', 'proshares'],
    },
    {
        symbol: 'SOXL',
        name: 'Direxion Daily Semiconductor Bull 3X Shares',
        type: 'etf',
        exchange: 'US',
        sector: 'Leveraged',
        searchableTerms: ['leveraged semiconductor', 'triple semi', 'soxl', '3x semis', 'direxion chips'],
    },
    {
        symbol: 'SOXS',
        name: 'Direxion Daily Semiconductor Bear 3X Shares',
        type: 'etf',
        exchange: 'US',
        sector: 'Leveraged',
        searchableTerms: ['inverse semiconductor', 'short semiconductor', 'soxs', 'bear semis'],
    },
    {
        symbol: 'SPXL',
        name: 'Direxion Daily S&P 500 Bull 3X Shares',
        type: 'etf',
        exchange: 'US',
        sector: 'Leveraged',
        searchableTerms: ['leveraged s&p', 'triple spy', 'spxl', '3x s&p 500', 'direxion'],
    },
    {
        symbol: 'SPXS',
        name: 'Direxion Daily S&P 500 Bear 3X Shares',
        type: 'etf',
        exchange: 'US',
        sector: 'Leveraged',
        searchableTerms: ['inverse s&p', 'short s&p', 'spxs', 'bear s&p 500'],
    },
    {
        symbol: 'UVXY',
        name: 'ProShares Ultra VIX Short-Term Futures ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Volatility',
        searchableTerms: ['vix', 'volatility', 'uvxy', 'fear index', 'proshares vix'],
    },

    // ─── Bitcoin / Crypto ETFs ────────────────────────────────────────────────
    {
        symbol: 'BITO',
        name: 'ProShares Bitcoin Strategy ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Crypto',
        searchableTerms: ['bitcoin etf', 'btc etf', 'bito', 'proshares bitcoin'],
    },
    {
        symbol: 'IBIT',
        name: 'iShares Bitcoin Trust ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Crypto',
        searchableTerms: ['bitcoin etf', 'btc etf', 'ibit', 'blackrock bitcoin', 'ishares bitcoin'],
    },
    {
        symbol: 'FBTC',
        name: 'Fidelity Wise Origin Bitcoin Fund',
        type: 'etf',
        exchange: 'US',
        sector: 'Crypto',
        searchableTerms: ['bitcoin etf', 'btc etf', 'fbtc', 'fidelity bitcoin'],
    },
    {
        symbol: 'GBTC',
        name: 'Grayscale Bitcoin Trust ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Crypto',
        searchableTerms: ['bitcoin', 'grayscale', 'gbtc', 'btc trust'],
    },

    // ─── Popular Non-S&P-500 Stocks ───────────────────────────────────────────

    // SpaceX (IPO June 12, 2026 — Nasdaq: SPCX)
    {
        symbol: 'SPCX',
        name: 'Space Exploration Technologies Corp. (SpaceX)',
        type: 'stock',
        exchange: 'US',
        sector: 'Industrials',
        searchableTerms: ['spacex', 'space exploration', 'elon musk', 'starlink', 'rocket', 'starship', 'xai', 'spcx', 'space tech'],
    },

    // Semiconductors / Hardware
    {
        symbol: 'TSM',
        name: 'Taiwan Semiconductor Manufacturing',
        type: 'stock',
        exchange: 'US',
        sector: 'Information Technology',
        searchableTerms: ['tsmc', 'taiwan semiconductor', 'chip maker', 'foundry'],
    },
    {
        symbol: 'ASML',
        name: 'ASML Holding NV',
        type: 'stock',
        exchange: 'US',
        sector: 'Information Technology',
        searchableTerms: ['asml', 'euv', 'lithography', 'chip equipment', 'dutch semiconductor'],
    },
    {
        symbol: 'ARM',
        name: 'Arm Holdings',
        type: 'stock',
        exchange: 'US',
        sector: 'Information Technology',
        searchableTerms: ['arm', 'arm holdings', 'chip design', 'mobile chips', 'softbank arm'],
    },

    // Bitcoin-related stocks
    {
        symbol: 'MSTR',
        name: 'MicroStrategy (Strategy)',
        type: 'stock',
        exchange: 'US',
        sector: 'Information Technology',
        searchableTerms: ['microstrategy', 'strategy', 'bitcoin treasury', 'mstr', 'saylor'],
    },
    {
        symbol: 'MARA',
        name: 'MARA Holdings',
        type: 'stock',
        exchange: 'US',
        sector: 'Information Technology',
        searchableTerms: ['bitcoin mining', 'marathon digital', 'crypto mining', 'mara'],
    },
    {
        symbol: 'RIOT',
        name: 'Riot Platforms',
        type: 'stock',
        exchange: 'US',
        sector: 'Information Technology',
        searchableTerms: ['bitcoin mining', 'crypto mining', 'riot', 'riot platforms'],
    },

    // EV / Automotive
    {
        symbol: 'RIVN',
        name: 'Rivian Automotive',
        type: 'stock',
        exchange: 'US',
        sector: 'Consumer Discretionary',
        searchableTerms: ['rivian', 'electric vehicle', 'ev', 'electric truck', 'amazon ev'],
    },
    {
        symbol: 'LCID',
        name: 'Lucid Group',
        type: 'stock',
        exchange: 'US',
        sector: 'Consumer Discretionary',
        searchableTerms: ['lucid', 'lucid motors', 'electric vehicle', 'ev', 'luxury ev'],
    },
    {
        symbol: 'NIO',
        name: 'NIO Inc.',
        type: 'stock',
        exchange: 'US',
        sector: 'Consumer Discretionary',
        searchableTerms: ['nio', 'chinese electric vehicle', 'ev china', 'chinese tesla'],
    },

    // Chinese Tech
    {
        symbol: 'BABA',
        name: 'Alibaba Group',
        type: 'stock',
        exchange: 'US',
        sector: 'Consumer Discretionary',
        searchableTerms: ['alibaba', 'chinese tech', 'china ecommerce', 'taobao', 'tmall', 'jack ma'],
    },
    {
        symbol: 'BIDU',
        name: 'Baidu Inc.',
        type: 'stock',
        exchange: 'US',
        sector: 'Communication Services',
        searchableTerms: ['baidu', 'chinese google', 'china ai', 'china search'],
    },
    {
        symbol: 'JD',
        name: 'JD.com Inc.',
        type: 'stock',
        exchange: 'US',
        sector: 'Consumer Discretionary',
        searchableTerms: ['jd.com', 'jingdong', 'china ecommerce', 'chinese amazon'],
    },
    {
        symbol: 'PDD',
        name: 'PDD Holdings (Temu / Pinduoduo)',
        type: 'stock',
        exchange: 'US',
        sector: 'Consumer Discretionary',
        searchableTerms: ['pdd', 'pinduoduo', 'temu', 'china ecommerce', 'pdd holdings'],
    },
    {
        symbol: 'SE',
        name: 'Sea Limited',
        type: 'stock',
        exchange: 'US',
        sector: 'Consumer Discretionary',
        searchableTerms: ['sea limited', 'shopee', 'garena', 'southeast asia tech', 'singapore tech'],
    },

    // Fintech
    {
        symbol: 'SOFI',
        name: 'SoFi Technologies',
        type: 'stock',
        exchange: 'US',
        sector: 'Financials',
        searchableTerms: ['sofi', 'student loans', 'neobank', 'fintech', 'digital bank'],
    },
    {
        symbol: 'AFRM',
        name: 'Affirm Holdings',
        type: 'stock',
        exchange: 'US',
        sector: 'Financials',
        searchableTerms: ['affirm', 'buy now pay later', 'bnpl', 'fintech', 'installment'],
    },
    {
        symbol: 'BILL',
        name: 'Bill Holdings',
        type: 'stock',
        exchange: 'US',
        sector: 'Financials',
        searchableTerms: ['bill.com', 'accounts payable', 'sme finance', 'fintech'],
    },
    {
        symbol: 'NU',
        name: 'Nu Holdings (Nubank)',
        type: 'stock',
        exchange: 'US',
        sector: 'Financials',
        searchableTerms: ['nu', 'nubank', 'brazil fintech', 'latin america bank', 'digital banking'],
    },

    // E-commerce / Consumer Tech
    {
        symbol: 'SHOP',
        name: 'Shopify Inc.',
        type: 'stock',
        exchange: 'US',
        sector: 'Information Technology',
        searchableTerms: ['shopify', 'ecommerce platform', 'online store builder'],
    },
    {
        symbol: 'MELI',
        name: 'MercadoLibre',
        type: 'stock',
        exchange: 'US',
        sector: 'Consumer Discretionary',
        searchableTerms: ['mercadolibre', 'latin america ecommerce', 'mercadopago', 'latam amazon'],
    },

    // Social / Media
    {
        symbol: 'SNAP',
        name: 'Snap Inc.',
        type: 'stock',
        exchange: 'US',
        sector: 'Communication Services',
        searchableTerms: ['snapchat', 'snap', 'social media', 'stories'],
    },
    {
        symbol: 'PINS',
        name: 'Pinterest Inc.',
        type: 'stock',
        exchange: 'US',
        sector: 'Communication Services',
        searchableTerms: ['pinterest', 'social media', 'image sharing', 'pins'],
    },
    {
        symbol: 'RDDT',
        name: 'Reddit Inc.',
        type: 'stock',
        exchange: 'US',
        sector: 'Communication Services',
        searchableTerms: ['reddit', 'social media', 'community forum', 'wallstreetbets'],
    },
    {
        symbol: 'PARA',
        name: 'Paramount Global',
        type: 'stock',
        exchange: 'US',
        sector: 'Communication Services',
        searchableTerms: ['paramount', 'viacom', 'cbs', 'streaming', 'paramount+'],
    },

    // Entertainment / Gaming
    {
        symbol: 'RBLX',
        name: 'Roblox Corporation',
        type: 'stock',
        exchange: 'US',
        sector: 'Communication Services',
        searchableTerms: ['roblox', 'gaming', 'metaverse', 'kids games', 'online gaming'],
    },
    {
        symbol: 'DKNG',
        name: 'DraftKings Inc.',
        type: 'stock',
        exchange: 'US',
        sector: 'Consumer Discretionary',
        searchableTerms: ['draftkings', 'sports betting', 'gambling', 'daily fantasy', 'online sports'],
    },
    {
        symbol: 'SPOT',
        name: 'Spotify Technology',
        type: 'stock',
        exchange: 'US',
        sector: 'Communication Services',
        searchableTerms: ['spotify', 'music streaming', 'podcast', 'audio streaming'],
    },

    // SaaS / Enterprise Tech
    {
        symbol: 'ZM',
        name: 'Zoom Video Communications',
        type: 'stock',
        exchange: 'US',
        sector: 'Information Technology',
        searchableTerms: ['zoom', 'video conferencing', 'remote work', 'video calls'],
    },
    {
        symbol: 'DOCU',
        name: 'DocuSign Inc.',
        type: 'stock',
        exchange: 'US',
        sector: 'Information Technology',
        searchableTerms: ['docusign', 'e-signature', 'digital signature', 'esign'],
    },
    {
        symbol: 'OKTA',
        name: 'Okta Inc.',
        type: 'stock',
        exchange: 'US',
        sector: 'Information Technology',
        searchableTerms: ['okta', 'identity management', 'cybersecurity', 'sso', 'authentication'],
    },
    {
        symbol: 'MNDY',
        name: 'monday.com Ltd.',
        type: 'stock',
        exchange: 'US',
        sector: 'Information Technology',
        searchableTerms: ['monday.com', 'project management', 'work os', 'collaboration software'],
    },
    {
        symbol: 'U',
        name: 'Unity Software Inc.',
        type: 'stock',
        exchange: 'US',
        sector: 'Information Technology',
        searchableTerms: ['unity', 'game engine', 'game development', '3d software', 'unity software'],
    },

    // Health / Consumer
    {
        symbol: 'HIMS',
        name: 'Hims & Hers Health',
        type: 'stock',
        exchange: 'US',
        sector: 'Health Care',
        searchableTerms: ['hims', 'hers', 'telehealth', 'men health', 'weight loss', 'ozempic'],
    },

    // Rideshare / Mobility
    {
        symbol: 'LYFT',
        name: 'Lyft Inc.',
        type: 'stock',
        exchange: 'US',
        sector: 'Information Technology',
        searchableTerms: ['lyft', 'rideshare', 'ride hailing', 'uber competitor'],
    },

    // Dating / Social
    {
        symbol: 'MTCH',
        name: 'Match Group',
        type: 'stock',
        exchange: 'US',
        sector: 'Communication Services',
        searchableTerms: ['match group', 'tinder', 'dating app', 'hinge', 'okcupid'],
    },

    // Quantum Computing
    {
        symbol: 'IONQ',
        name: 'IonQ Inc.',
        type: 'stock',
        exchange: 'US',
        sector: 'Information Technology',
        searchableTerms: ['quantum computing', 'ionq', 'quantum', 'ion trap'],
    },
];
