import type { AssetRecord } from './types';

/**
 * ETFs, crypto, and commodity proxies not covered as single stocks in the S&P 500 list.
 * searchableTerms drive intent queries (e.g. "gold", "S&P 500", "Nasdaq").
 */
export const EXTRA_INSTRUMENTS: readonly AssetRecord[] = [
    {
        symbol: 'BTC-USD',
        name: 'Bitcoin',
        type: 'crypto',
        exchange: 'CCY',
        searchableTerms: ['bitcoin', 'btc', 'crypto'],
    },
    {
        symbol: 'ETH-USD',
        name: 'Ethereum',
        type: 'crypto',
        exchange: 'CCY',
        searchableTerms: ['ethereum', 'eth', 'crypto'],
    },
    {
        symbol: 'SPY',
        name: 'SPDR S&P 500 ETF Trust',
        type: 'etf',
        exchange: 'US',
        sector: 'Index',
        searchableTerms: ['s&p 500', 's&p500', 'sp500', 'sp 500', 'sandp', 's and p 500', 'index', 'large cap blend'],
    },
    {
        symbol: 'VOO',
        name: 'Vanguard S&P 500 ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Index',
        searchableTerms: ['s&p 500', 's&p500', 'sp500', 'sp 500', 'sandp', 'vanguard s&p'],
    },
    {
        symbol: 'IVV',
        name: 'iShares Core S&P 500 ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Index',
        searchableTerms: ['s&p 500', 's&p500', 'sp500', 'sp 500', 'ishares s&p'],
    },
    {
        symbol: 'DIA',
        name: 'SPDR Dow Jones Industrial Average ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Index',
        searchableTerms: ['dow', 'dow jones', 'industrial average', 'dia'],
    },
    {
        symbol: 'QQQ',
        name: 'Invesco QQQ Trust',
        type: 'etf',
        exchange: 'US',
        sector: 'Index',
        searchableTerms: ['nasdaq', 'nasdaq 100', 'ndx', 'tech heavy', 'qqq'],
    },
    {
        symbol: 'QQQM',
        name: 'Invesco NASDAQ 100 ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Index',
        searchableTerms: ['nasdaq', 'nasdaq 100', 'qqq', 'qqqm'],
    },
    {
        symbol: 'IWM',
        name: 'iShares Russell 2000 ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Index',
        searchableTerms: ['russell 2000', 'small cap', 'iwm'],
    },
    {
        symbol: 'VTI',
        name: 'Vanguard Total Stock Market ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Index',
        searchableTerms: ['total market', 'vti', 'broad market'],
    },
    {
        symbol: 'XLF',
        name: 'Financial Select Sector SPDR Fund',
        type: 'etf',
        exchange: 'US',
        sector: 'Financials',
        searchableTerms: ['financials', 'banks', 'xlf', 'sector financials'],
    },
    {
        symbol: 'XLK',
        name: 'Technology Select Sector SPDR Fund',
        type: 'etf',
        exchange: 'US',
        sector: 'Technology',
        searchableTerms: ['technology sector', 'tech sector', 'xlk'],
    },
    {
        symbol: 'XLE',
        name: 'Energy Select Sector SPDR Fund',
        type: 'etf',
        exchange: 'US',
        sector: 'Energy',
        searchableTerms: ['energy sector', 'oil gas', 'xle'],
    },
    {
        symbol: 'XLV',
        name: 'Health Care Select Sector SPDR Fund',
        type: 'etf',
        exchange: 'US',
        sector: 'Health Care',
        searchableTerms: ['health care sector', 'healthcare sector', 'xlv'],
    },
    {
        symbol: 'SCHD',
        name: 'Schwab U.S. Dividend Equity ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Dividend',
        searchableTerms: ['dividend', 'schd', 'quality dividend'],
    },
    {
        symbol: 'ARKK',
        name: 'ARK Innovation ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Thematic',
        searchableTerms: ['ark', 'innovation', 'cathie wood', 'arkk'],
    },
    {
        symbol: 'VNQ',
        name: 'Vanguard Real Estate ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Real Estate',
        searchableTerms: ['reit', 'real estate', 'vnq'],
    },
    {
        symbol: 'GLD',
        name: 'SPDR Gold Shares',
        type: 'commodity_proxy',
        exchange: 'US',
        sector: 'Commodities',
        searchableTerms: ['gold', 'bullion', 'precious metal', 'gld', 'gold etf'],
    },
    {
        symbol: 'IAU',
        name: 'iShares Gold Trust',
        type: 'commodity_proxy',
        exchange: 'US',
        sector: 'Commodities',
        searchableTerms: ['gold', 'bullion', 'precious metal', 'iau'],
    },
    {
        symbol: 'SGOL',
        name: 'abrdn Physical Gold Shares ETF',
        type: 'commodity_proxy',
        exchange: 'US',
        sector: 'Commodities',
        searchableTerms: ['gold', 'bullion', 'sgol'],
    },
    {
        symbol: 'SLV',
        name: 'iShares Silver Trust',
        type: 'commodity_proxy',
        exchange: 'US',
        sector: 'Commodities',
        searchableTerms: ['silver', 'precious metal', 'slv', 'silver etf'],
    },
    {
        symbol: 'SIVR',
        name: 'abrdn Physical Silver Shares ETF',
        type: 'commodity_proxy',
        exchange: 'US',
        sector: 'Commodities',
        searchableTerms: ['silver', 'sivr', 'precious metal'],
    },
    {
        symbol: 'GDX',
        name: 'VanEck Gold Miners ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Materials',
        searchableTerms: ['gold miners', 'mining', 'gdx', 'gold stocks'],
    },
    {
        symbol: 'NUGT',
        name: 'Direxion Daily Gold Miners Bull 2X Shares',
        type: 'etf',
        exchange: 'US',
        sector: 'Materials',
        searchableTerms: ['gold miners', 'leveraged gold', 'nugt'],
    },
    {
        symbol: 'COPX',
        name: 'Global X Copper Miners ETF',
        type: 'etf',
        exchange: 'US',
        sector: 'Materials',
        searchableTerms: ['copper', 'miners', 'copx'],
    },
    {
        symbol: 'USO',
        name: 'United States Oil Fund',
        type: 'commodity_proxy',
        exchange: 'US',
        sector: 'Energy',
        searchableTerms: ['oil', 'crude', 'wti', 'uso'],
    },
    {
        symbol: 'UNG',
        name: 'United States Natural Gas Fund',
        type: 'commodity_proxy',
        exchange: 'US',
        sector: 'Energy',
        searchableTerms: ['natural gas', 'ung'],
    },
];
