/** Auto-generated from datasets/s-and-p-500-companies constituents. */
import type { AssetRecord } from './types';

export const SP500_CONSTITUENTS: readonly AssetRecord[] = [
  { symbol: "MMM", name: "3M", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "AOS", name: "A. O. Smith", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "ABT", name: "Abbott Laboratories", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "ABBV", name: "AbbVie", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "ACN", name: "Accenture", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "ADBE", name: "Adobe Inc.", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "AMD", name: "Advanced Micro Devices", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "AES", name: "AES Corporation", type: 'stock', exchange: 'US', sector: "Utilities", searchableTerms: [] },
  { symbol: "AFL", name: "Aflac", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "A", name: "Agilent Technologies", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "APD", name: "Air Products", type: 'stock', exchange: 'US', sector: "Materials", searchableTerms: [] },
  { symbol: "ABNB", name: "Airbnb", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "AKAM", name: "Akamai Technologies", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "ALB", name: "Albemarle Corporation", type: 'stock', exchange: 'US', sector: "Materials", searchableTerms: [] },
  { symbol: "ARE", name: "Alexandria Real Estate Equities", type: 'stock', exchange: 'US', sector: "Real Estate", searchableTerms: [] },
  { symbol: "ALGN", name: "Align Technology", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "ALLE", name: "Allegion", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "LNT", name: "Alliant Energy", type: 'stock', exchange: 'US', sector: "Utilities", searchableTerms: [] },
  { symbol: "ALL", name: "Allstate", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "GOOGL", name: "Alphabet Inc. (Class A)", type: 'stock', exchange: 'US', sector: "Communication Services", searchableTerms: [] },
  { symbol: "GOOG", name: "Alphabet Inc. (Class C)", type: 'stock', exchange: 'US', sector: "Communication Services", searchableTerms: [] },
  { symbol: "MO", name: "Altria", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "AMZN", name: "Amazon", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "AMCR", name: "Amcor", type: 'stock', exchange: 'US', sector: "Materials", searchableTerms: [] },
  { symbol: "AEE", name: "Ameren", type: 'stock', exchange: 'US', sector: "Utilities", searchableTerms: [] },
  { symbol: "AEP", name: "American Electric Power", type: 'stock', exchange: 'US', sector: "Utilities", searchableTerms: [] },
  { symbol: "AXP", name: "American Express", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "AIG", name: "American International Group", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "AMT", name: "American Tower", type: 'stock', exchange: 'US', sector: "Real Estate", searchableTerms: [] },
  { symbol: "AWK", name: "American Water Works", type: 'stock', exchange: 'US', sector: "Utilities", searchableTerms: [] },
  { symbol: "AMP", name: "Ameriprise Financial", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "AME", name: "Ametek", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "AMGN", name: "Amgen", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "APH", name: "Amphenol", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "ADI", name: "Analog Devices", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "AON", name: "Aon plc", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "APA", name: "APA Corporation", type: 'stock', exchange: 'US', sector: "Energy", searchableTerms: [] },
  { symbol: "APO", name: "Apollo Global Management", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "AAPL", name: "Apple Inc.", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "AMAT", name: "Applied Materials", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "APP", name: "AppLovin", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "APTV", name: "Aptiv", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "ACGL", name: "Arch Capital Group", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "ADM", name: "Archer Daniels Midland", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "ARES", name: "Ares Management", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "ANET", name: "Arista Networks", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "AJG", name: "Arthur J. Gallagher & Co.", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "AIZ", name: "Assurant", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "T", name: "AT&T", type: 'stock', exchange: 'US', sector: "Communication Services", searchableTerms: [] },
  { symbol: "ATO", name: "Atmos Energy", type: 'stock', exchange: 'US', sector: "Utilities", searchableTerms: [] },
  { symbol: "ADSK", name: "Autodesk", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "ADP", name: "Automatic Data Processing", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "AZO", name: "AutoZone", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "AVB", name: "AvalonBay Communities", type: 'stock', exchange: 'US', sector: "Real Estate", searchableTerms: [] },
  { symbol: "AVY", name: "Avery Dennison", type: 'stock', exchange: 'US', sector: "Materials", searchableTerms: [] },
  { symbol: "AXON", name: "Axon Enterprise", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "BKR", name: "Baker Hughes", type: 'stock', exchange: 'US', sector: "Energy", searchableTerms: [] },
  { symbol: "BALL", name: "Ball Corporation", type: 'stock', exchange: 'US', sector: "Materials", searchableTerms: [] },
  { symbol: "BAC", name: "Bank of America", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "BAX", name: "Baxter International", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "BDX", name: "Becton Dickinson", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "BRK.B", name: "Berkshire Hathaway", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "BBY", name: "Best Buy", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "TECH", name: "Bio-Techne", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "BIIB", name: "Biogen", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "BLK", name: "BlackRock", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "BX", name: "Blackstone Inc.", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "XYZ", name: "Block, Inc.", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "BK", name: "BNY Mellon", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "BA", name: "Boeing", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "BKNG", name: "Booking Holdings", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "BSX", name: "Boston Scientific", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "BMY", name: "Bristol Myers Squibb", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "AVGO", name: "Broadcom", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "BR", name: "Broadridge Financial Solutions", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "BRO", name: "Brown & Brown", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "BF.B", name: "Brown\u2013Forman", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "BLDR", name: "Builders FirstSource", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "BG", name: "Bunge Global", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "BXP", name: "BXP, Inc.", type: 'stock', exchange: 'US', sector: "Real Estate", searchableTerms: [] },
  { symbol: "CHRW", name: "C.H. Robinson", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "CDNS", name: "Cadence Design Systems", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "CPT", name: "Camden Property Trust", type: 'stock', exchange: 'US', sector: "Real Estate", searchableTerms: [] },
  { symbol: "CPB", name: "Campbell's Company (The)", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "COF", name: "Capital One", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "CAH", name: "Cardinal Health", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "CCL", name: "Carnival", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "CARR", name: "Carrier Global", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "CVNA", name: "Carvana", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "CASY", name: "Casey's", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "CAT", name: "Caterpillar Inc.", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "CBOE", name: "Cboe Global Markets", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "CBRE", name: "CBRE Group", type: 'stock', exchange: 'US', sector: "Real Estate", searchableTerms: [] },
  { symbol: "CDW", name: "CDW Corporation", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "COR", name: "Cencora", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "CNC", name: "Centene Corporation", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "CNP", name: "CenterPoint Energy", type: 'stock', exchange: 'US', sector: "Utilities", searchableTerms: [] },
  { symbol: "CF", name: "CF Industries", type: 'stock', exchange: 'US', sector: "Materials", searchableTerms: [] },
  { symbol: "CRL", name: "Charles River Laboratories", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "SCHW", name: "Charles Schwab Corporation", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "CHTR", name: "Charter Communications", type: 'stock', exchange: 'US', sector: "Communication Services", searchableTerms: [] },
  { symbol: "CVX", name: "Chevron Corporation", type: 'stock', exchange: 'US', sector: "Energy", searchableTerms: [] },
  { symbol: "CMG", name: "Chipotle Mexican Grill", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "CB", name: "Chubb Limited", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "CHD", name: "Church & Dwight", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "CIEN", name: "Ciena", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "CI", name: "Cigna", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "CINF", name: "Cincinnati Financial", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "CTAS", name: "Cintas", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "CSCO", name: "Cisco", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "C", name: "Citigroup", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "CFG", name: "Citizens Financial Group", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "CLX", name: "Clorox", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "CME", name: "CME Group", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "CMS", name: "CMS Energy", type: 'stock', exchange: 'US', sector: "Utilities", searchableTerms: [] },
  { symbol: "KO", name: "Coca-Cola Company (The)", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "CTSH", name: "Cognizant", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "COHR", name: "Coherent Corp.", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "COIN", name: "Coinbase", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "CL", name: "Colgate-Palmolive", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "CMCSA", name: "Comcast", type: 'stock', exchange: 'US', sector: "Communication Services", searchableTerms: [] },
  { symbol: "FIX", name: "Comfort Systems USA", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "CAG", name: "Conagra Brands", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "COP", name: "ConocoPhillips", type: 'stock', exchange: 'US', sector: "Energy", searchableTerms: [] },
  { symbol: "ED", name: "Consolidated Edison", type: 'stock', exchange: 'US', sector: "Utilities", searchableTerms: [] },
  { symbol: "STZ", name: "Constellation Brands", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "CEG", name: "Constellation Energy", type: 'stock', exchange: 'US', sector: "Utilities", searchableTerms: [] },
  { symbol: "COO", name: "Cooper Companies (The)", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "CPRT", name: "Copart", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "GLW", name: "Corning Inc.", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "CPAY", name: "Corpay", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "CTVA", name: "Corteva", type: 'stock', exchange: 'US', sector: "Materials", searchableTerms: [] },
  { symbol: "CSGP", name: "CoStar Group", type: 'stock', exchange: 'US', sector: "Real Estate", searchableTerms: [] },
  { symbol: "COST", name: "Costco", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "CTRA", name: "Coterra", type: 'stock', exchange: 'US', sector: "Energy", searchableTerms: [] },
  { symbol: "CRH", name: "CRH plc", type: 'stock', exchange: 'US', sector: "Materials", searchableTerms: [] },
  { symbol: "CRWD", name: "CrowdStrike", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "CCI", name: "Crown Castle", type: 'stock', exchange: 'US', sector: "Real Estate", searchableTerms: [] },
  { symbol: "CSX", name: "CSX Corporation", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "CMI", name: "Cummins", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "CVS", name: "CVS Health", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "DHR", name: "Danaher Corporation", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "DRI", name: "Darden Restaurants", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "DDOG", name: "Datadog", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "DVA", name: "DaVita", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "DECK", name: "Deckers Brands", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "DE", name: "Deere & Company", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "DELL", name: "Dell Technologies", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "DAL", name: "Delta Air Lines", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "DVN", name: "Devon Energy", type: 'stock', exchange: 'US', sector: "Energy", searchableTerms: [] },
  { symbol: "DXCM", name: "Dexcom", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "FANG", name: "Diamondback Energy", type: 'stock', exchange: 'US', sector: "Energy", searchableTerms: [] },
  { symbol: "DLR", name: "Digital Realty", type: 'stock', exchange: 'US', sector: "Real Estate", searchableTerms: [] },
  { symbol: "DG", name: "Dollar General", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "DLTR", name: "Dollar Tree", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "D", name: "Dominion Energy", type: 'stock', exchange: 'US', sector: "Utilities", searchableTerms: [] },
  { symbol: "DPZ", name: "Domino's", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "DASH", name: "DoorDash", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "DOV", name: "Dover Corporation", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "DOW", name: "Dow Inc.", type: 'stock', exchange: 'US', sector: "Materials", searchableTerms: [] },
  { symbol: "DHI", name: "D. R. Horton", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "DTE", name: "DTE Energy", type: 'stock', exchange: 'US', sector: "Utilities", searchableTerms: [] },
  { symbol: "DUK", name: "Duke Energy", type: 'stock', exchange: 'US', sector: "Utilities", searchableTerms: [] },
  { symbol: "DD", name: "DuPont", type: 'stock', exchange: 'US', sector: "Materials", searchableTerms: [] },
  { symbol: "ETN", name: "Eaton Corporation", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "EBAY", name: "eBay Inc.", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "SATS", name: "EchoStar", type: 'stock', exchange: 'US', sector: "Communication Services", searchableTerms: [] },
  { symbol: "ECL", name: "Ecolab", type: 'stock', exchange: 'US', sector: "Materials", searchableTerms: [] },
  { symbol: "EIX", name: "Edison International", type: 'stock', exchange: 'US', sector: "Utilities", searchableTerms: [] },
  { symbol: "EW", name: "Edwards Lifesciences", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "EA", name: "Electronic Arts", type: 'stock', exchange: 'US', sector: "Communication Services", searchableTerms: [] },
  { symbol: "ELV", name: "Elevance Health", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "EME", name: "Emcor", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "EMR", name: "Emerson Electric", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "ETR", name: "Entergy", type: 'stock', exchange: 'US', sector: "Utilities", searchableTerms: [] },
  { symbol: "EOG", name: "EOG Resources", type: 'stock', exchange: 'US', sector: "Energy", searchableTerms: [] },
  { symbol: "EPAM", name: "EPAM Systems", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "EQT", name: "EQT Corporation", type: 'stock', exchange: 'US', sector: "Energy", searchableTerms: [] },
  { symbol: "EFX", name: "Equifax", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "EQIX", name: "Equinix", type: 'stock', exchange: 'US', sector: "Real Estate", searchableTerms: [] },
  { symbol: "EQR", name: "Equity Residential", type: 'stock', exchange: 'US', sector: "Real Estate", searchableTerms: [] },
  { symbol: "ERIE", name: "Erie Indemnity", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "ESS", name: "Essex Property Trust", type: 'stock', exchange: 'US', sector: "Real Estate", searchableTerms: [] },
  { symbol: "EL", name: "Est\u00e9e Lauder Companies (The)", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "EG", name: "Everest Group", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "EVRG", name: "Evergy", type: 'stock', exchange: 'US', sector: "Utilities", searchableTerms: [] },
  { symbol: "ES", name: "Eversource Energy", type: 'stock', exchange: 'US', sector: "Utilities", searchableTerms: [] },
  { symbol: "EXC", name: "Exelon", type: 'stock', exchange: 'US', sector: "Utilities", searchableTerms: [] },
  { symbol: "EXE", name: "Expand Energy", type: 'stock', exchange: 'US', sector: "Energy", searchableTerms: [] },
  { symbol: "EXPE", name: "Expedia Group", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "EXPD", name: "Expeditors International", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "EXR", name: "Extra Space Storage", type: 'stock', exchange: 'US', sector: "Real Estate", searchableTerms: [] },
  { symbol: "XOM", name: "ExxonMobil", type: 'stock', exchange: 'US', sector: "Energy", searchableTerms: [] },
  { symbol: "FFIV", name: "F5, Inc.", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "FDS", name: "FactSet", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "FICO", name: "Fair Isaac", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "FAST", name: "Fastenal", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "FRT", name: "Federal Realty Investment Trust", type: 'stock', exchange: 'US', sector: "Real Estate", searchableTerms: [] },
  { symbol: "FDX", name: "FedEx", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "FIS", name: "Fidelity National Information Services", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "FITB", name: "Fifth Third Bancorp", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "FSLR", name: "First Solar", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "FE", name: "FirstEnergy", type: 'stock', exchange: 'US', sector: "Utilities", searchableTerms: [] },
  { symbol: "FISV", name: "Fiserv", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "F", name: "Ford Motor Company", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "FTNT", name: "Fortinet", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "FTV", name: "Fortive", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "FOXA", name: "Fox Corporation (Class A)", type: 'stock', exchange: 'US', sector: "Communication Services", searchableTerms: [] },
  { symbol: "FOX", name: "Fox Corporation (Class B)", type: 'stock', exchange: 'US', sector: "Communication Services", searchableTerms: [] },
  { symbol: "BEN", name: "Franklin Resources", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "FCX", name: "Freeport-McMoRan", type: 'stock', exchange: 'US', sector: "Materials", searchableTerms: [] },
  { symbol: "GRMN", name: "Garmin", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "IT", name: "Gartner", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "GE", name: "GE Aerospace", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "GEHC", name: "GE HealthCare", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "GEV", name: "GE Vernova", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "GEN", name: "Gen Digital", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "GNRC", name: "Generac", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "GD", name: "General Dynamics", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "GIS", name: "General Mills", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "GM", name: "General Motors", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "GPC", name: "Genuine Parts Company", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "GILD", name: "Gilead Sciences", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "GPN", name: "Global Payments", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "GL", name: "Globe Life", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "GDDY", name: "GoDaddy", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "GS", name: "Goldman Sachs", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "HAL", name: "Halliburton", type: 'stock', exchange: 'US', sector: "Energy", searchableTerms: [] },
  { symbol: "HIG", name: "Hartford (The)", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "HAS", name: "Hasbro", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "HCA", name: "HCA Healthcare", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "DOC", name: "Healthpeak Properties", type: 'stock', exchange: 'US', sector: "Real Estate", searchableTerms: [] },
  { symbol: "HSIC", name: "Henry Schein", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "HSY", name: "Hershey Company (The)", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "HPE", name: "Hewlett Packard Enterprise", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "HLT", name: "Hilton Worldwide", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "HD", name: "Home Depot (The)", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "HON", name: "Honeywell", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "HRL", name: "Hormel Foods", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "HST", name: "Host Hotels & Resorts", type: 'stock', exchange: 'US', sector: "Real Estate", searchableTerms: [] },
  { symbol: "HWM", name: "Howmet Aerospace", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "HPQ", name: "HP Inc.", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "HUBB", name: "Hubbell Incorporated", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "HUM", name: "Humana", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "HBAN", name: "Huntington Bancshares", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "HII", name: "Huntington Ingalls Industries", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "IBM", name: "IBM", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "IEX", name: "IDEX Corporation", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "IDXX", name: "Idexx Laboratories", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "ITW", name: "Illinois Tool Works", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "INCY", name: "Incyte", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "IR", name: "Ingersoll Rand", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "PODD", name: "Insulet Corporation", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "INTC", name: "Intel", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "IBKR", name: "Interactive Brokers", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "ICE", name: "Intercontinental Exchange", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "IFF", name: "International Flavors & Fragrances", type: 'stock', exchange: 'US', sector: "Materials", searchableTerms: [] },
  { symbol: "IP", name: "International Paper", type: 'stock', exchange: 'US', sector: "Materials", searchableTerms: [] },
  { symbol: "INTU", name: "Intuit", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "ISRG", name: "Intuitive Surgical", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "IVZ", name: "Invesco", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "INVH", name: "Invitation Homes", type: 'stock', exchange: 'US', sector: "Real Estate", searchableTerms: [] },
  { symbol: "IQV", name: "IQVIA", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "IRM", name: "Iron Mountain", type: 'stock', exchange: 'US', sector: "Real Estate", searchableTerms: [] },
  { symbol: "JBHT", name: "J.B. Hunt", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "JBL", name: "Jabil", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "JKHY", name: "Jack Henry & Associates", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "J", name: "Jacobs Solutions", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "JNJ", name: "Johnson & Johnson", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "JCI", name: "Johnson Controls", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "JPM", name: "JPMorgan Chase", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "KVUE", name: "Kenvue", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "KDP", name: "Keurig Dr Pepper", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "KEY", name: "KeyCorp", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "KEYS", name: "Keysight Technologies", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "KMB", name: "Kimberly-Clark", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "KIM", name: "Kimco Realty", type: 'stock', exchange: 'US', sector: "Real Estate", searchableTerms: [] },
  { symbol: "KMI", name: "Kinder Morgan", type: 'stock', exchange: 'US', sector: "Energy", searchableTerms: [] },
  { symbol: "KKR", name: "KKR & Co.", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "KLAC", name: "KLA Corporation", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "KHC", name: "Kraft Heinz", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "KR", name: "Kroger", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "LHX", name: "L3Harris", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "LH", name: "Labcorp", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "LRCX", name: "Lam Research", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "LVS", name: "Las Vegas Sands", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "LDOS", name: "Leidos", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "LEN", name: "Lennar", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "LII", name: "Lennox International", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "LLY", name: "Lilly (Eli)", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "LIN", name: "Linde plc", type: 'stock', exchange: 'US', sector: "Materials", searchableTerms: [] },
  { symbol: "LYV", name: "Live Nation Entertainment", type: 'stock', exchange: 'US', sector: "Communication Services", searchableTerms: [] },
  { symbol: "LMT", name: "Lockheed Martin", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "L", name: "Loews Corporation", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "LOW", name: "Lowe's", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "LULU", name: "Lululemon Athletica", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "LITE", name: "Lumentum", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "LYB", name: "LyondellBasell", type: 'stock', exchange: 'US', sector: "Materials", searchableTerms: [] },
  { symbol: "MTB", name: "M&T Bank", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "MPC", name: "Marathon Petroleum", type: 'stock', exchange: 'US', sector: "Energy", searchableTerms: [] },
  { symbol: "MAR", name: "Marriott International", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "MRSH", name: "Marsh McLennan", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "MLM", name: "Martin Marietta Materials", type: 'stock', exchange: 'US', sector: "Materials", searchableTerms: [] },
  { symbol: "MAS", name: "Masco", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "MA", name: "Mastercard", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "MKC", name: "McCormick & Company", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "MCD", name: "McDonald's", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "MCK", name: "McKesson Corporation", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "MDT", name: "Medtronic", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "MRK", name: "Merck & Co.", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "META", name: "Meta Platforms", type: 'stock', exchange: 'US', sector: "Communication Services", searchableTerms: [] },
  { symbol: "MET", name: "MetLife", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "MTD", name: "Mettler Toledo", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "MGM", name: "MGM Resorts", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "MCHP", name: "Microchip Technology", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "MU", name: "Micron Technology", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "MSFT", name: "Microsoft", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "MAA", name: "Mid-America Apartment Communities", type: 'stock', exchange: 'US', sector: "Real Estate", searchableTerms: [] },
  { symbol: "MRNA", name: "Moderna", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "TAP", name: "Molson Coors Beverage Company", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "MDLZ", name: "Mondelez International", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "MPWR", name: "Monolithic Power Systems", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "MNST", name: "Monster Beverage", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "MCO", name: "Moody's Corporation", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "MS", name: "Morgan Stanley", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "MOS", name: "Mosaic Company (The)", type: 'stock', exchange: 'US', sector: "Materials", searchableTerms: [] },
  { symbol: "MSI", name: "Motorola Solutions", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "MSCI", name: "MSCI Inc.", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "NDAQ", name: "Nasdaq, Inc.", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "NTAP", name: "NetApp", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "NFLX", name: "Netflix", type: 'stock', exchange: 'US', sector: "Communication Services", searchableTerms: [] },
  { symbol: "NEM", name: "Newmont", type: 'stock', exchange: 'US', sector: "Materials", searchableTerms: [] },
  { symbol: "NWSA", name: "News Corp (Class A)", type: 'stock', exchange: 'US', sector: "Communication Services", searchableTerms: [] },
  { symbol: "NWS", name: "News Corp (Class B)", type: 'stock', exchange: 'US', sector: "Communication Services", searchableTerms: [] },
  { symbol: "NEE", name: "NextEra Energy", type: 'stock', exchange: 'US', sector: "Utilities", searchableTerms: [] },
  { symbol: "NKE", name: "Nike, Inc.", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "NI", name: "NiSource", type: 'stock', exchange: 'US', sector: "Utilities", searchableTerms: [] },
  { symbol: "NDSN", name: "Nordson Corporation", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "NSC", name: "Norfolk Southern", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "NTRS", name: "Northern Trust", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "NOC", name: "Northrop Grumman", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "NCLH", name: "Norwegian Cruise Line Holdings", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "NRG", name: "NRG Energy", type: 'stock', exchange: 'US', sector: "Utilities", searchableTerms: [] },
  { symbol: "NUE", name: "Nucor", type: 'stock', exchange: 'US', sector: "Materials", searchableTerms: [] },
  { symbol: "NVDA", name: "Nvidia", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "NVR", name: "NVR, Inc.", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "NXPI", name: "NXP Semiconductors", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "ORLY", name: "O\u2019Reilly Automotive", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "OXY", name: "Occidental Petroleum", type: 'stock', exchange: 'US', sector: "Energy", searchableTerms: [] },
  { symbol: "ODFL", name: "Old Dominion", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "OMC", name: "Omnicom Group", type: 'stock', exchange: 'US', sector: "Communication Services", searchableTerms: [] },
  { symbol: "ON", name: "ON Semiconductor", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "OKE", name: "Oneok", type: 'stock', exchange: 'US', sector: "Energy", searchableTerms: [] },
  { symbol: "ORCL", name: "Oracle Corporation", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "OTIS", name: "Otis Worldwide", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "PCAR", name: "Paccar", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "PKG", name: "Packaging Corporation of America", type: 'stock', exchange: 'US', sector: "Materials", searchableTerms: [] },
  { symbol: "PLTR", name: "Palantir Technologies", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "PANW", name: "Palo Alto Networks", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "PSKY", name: "Paramount Skydance Corporation", type: 'stock', exchange: 'US', sector: "Communication Services", searchableTerms: [] },
  { symbol: "PH", name: "Parker Hannifin", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "PAYX", name: "Paychex", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "PYPL", name: "PayPal", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "PNR", name: "Pentair", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "PEP", name: "PepsiCo", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "PFE", name: "Pfizer", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "PCG", name: "PG&E Corporation", type: 'stock', exchange: 'US', sector: "Utilities", searchableTerms: [] },
  { symbol: "PM", name: "Philip Morris International", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "PSX", name: "Phillips 66", type: 'stock', exchange: 'US', sector: "Energy", searchableTerms: [] },
  { symbol: "PNW", name: "Pinnacle West Capital", type: 'stock', exchange: 'US', sector: "Utilities", searchableTerms: [] },
  { symbol: "PNC", name: "PNC Financial Services", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "POOL", name: "Pool Corporation", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "PPG", name: "PPG Industries", type: 'stock', exchange: 'US', sector: "Materials", searchableTerms: [] },
  { symbol: "PPL", name: "PPL Corporation", type: 'stock', exchange: 'US', sector: "Utilities", searchableTerms: [] },
  { symbol: "PFG", name: "Principal Financial Group", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "PG", name: "Procter & Gamble", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "PGR", name: "Progressive Corporation", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "PLD", name: "Prologis", type: 'stock', exchange: 'US', sector: "Real Estate", searchableTerms: [] },
  { symbol: "PRU", name: "Prudential Financial", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "PEG", name: "Public Service Enterprise Group", type: 'stock', exchange: 'US', sector: "Utilities", searchableTerms: [] },
  { symbol: "PTC", name: "PTC Inc.", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "PSA", name: "Public Storage", type: 'stock', exchange: 'US', sector: "Real Estate", searchableTerms: [] },
  { symbol: "PHM", name: "PulteGroup", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "PWR", name: "Quanta Services", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "QCOM", name: "Qualcomm", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "DGX", name: "Quest Diagnostics", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "Q", name: "Qnity Electronics", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "RL", name: "Ralph Lauren Corporation", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "RJF", name: "Raymond James Financial", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "RTX", name: "RTX Corporation", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "O", name: "Realty Income", type: 'stock', exchange: 'US', sector: "Real Estate", searchableTerms: [] },
  { symbol: "REG", name: "Regency Centers", type: 'stock', exchange: 'US', sector: "Real Estate", searchableTerms: [] },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "RF", name: "Regions Financial Corporation", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "RSG", name: "Republic Services", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "RMD", name: "ResMed", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "RVTY", name: "Revvity", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "HOOD", name: "Robinhood Markets", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "ROK", name: "Rockwell Automation", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "ROL", name: "Rollins, Inc.", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "ROP", name: "Roper Technologies", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "ROST", name: "Ross Stores", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "RCL", name: "Royal Caribbean Group", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "SPGI", name: "S&P Global", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "CRM", name: "Salesforce", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "SNDK", name: "Sandisk", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "SBAC", name: "SBA Communications", type: 'stock', exchange: 'US', sector: "Real Estate", searchableTerms: [] },
  { symbol: "SLB", name: "Schlumberger", type: 'stock', exchange: 'US', sector: "Energy", searchableTerms: [] },
  { symbol: "STX", name: "Seagate Technology", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "SRE", name: "Sempra", type: 'stock', exchange: 'US', sector: "Utilities", searchableTerms: [] },
  { symbol: "NOW", name: "ServiceNow", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "SHW", name: "Sherwin-Williams", type: 'stock', exchange: 'US', sector: "Materials", searchableTerms: [] },
  { symbol: "SPG", name: "Simon Property Group", type: 'stock', exchange: 'US', sector: "Real Estate", searchableTerms: [] },
  { symbol: "SWKS", name: "Skyworks Solutions", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "SJM", name: "J.M. Smucker Company (The)", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "SW", name: "Smurfit Westrock", type: 'stock', exchange: 'US', sector: "Materials", searchableTerms: [] },
  { symbol: "SNA", name: "Snap-on", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "SOLV", name: "Solventum", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "SO", name: "Southern Company", type: 'stock', exchange: 'US', sector: "Utilities", searchableTerms: [] },
  { symbol: "LUV", name: "Southwest Airlines", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "SWK", name: "Stanley Black & Decker", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "SBUX", name: "Starbucks", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "STT", name: "State Street Corporation", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "STLD", name: "Steel Dynamics", type: 'stock', exchange: 'US', sector: "Materials", searchableTerms: [] },
  { symbol: "STE", name: "Steris", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "SYK", name: "Stryker Corporation", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "SMCI", name: "Supermicro", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "SYF", name: "Synchrony Financial", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "SNPS", name: "Synopsys", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "SYY", name: "Sysco", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "TMUS", name: "T-Mobile US", type: 'stock', exchange: 'US', sector: "Communication Services", searchableTerms: [] },
  { symbol: "TROW", name: "T. Rowe Price", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "TTWO", name: "Take-Two Interactive", type: 'stock', exchange: 'US', sector: "Communication Services", searchableTerms: [] },
  { symbol: "TPR", name: "Tapestry, Inc.", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "TRGP", name: "Targa Resources", type: 'stock', exchange: 'US', sector: "Energy", searchableTerms: [] },
  { symbol: "TGT", name: "Target Corporation", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "TEL", name: "TE Connectivity", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "TDY", name: "Teledyne Technologies", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "TER", name: "Teradyne", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "TSLA", name: "Tesla, Inc.", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "TXN", name: "Texas Instruments", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "TPL", name: "Texas Pacific Land Corporation", type: 'stock', exchange: 'US', sector: "Energy", searchableTerms: [] },
  { symbol: "TXT", name: "Textron", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "TMO", name: "Thermo Fisher Scientific", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "TJX", name: "TJX Companies", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "TKO", name: "TKO Group Holdings", type: 'stock', exchange: 'US', sector: "Communication Services", searchableTerms: [] },
  { symbol: "TTD", name: "Trade Desk (The)", type: 'stock', exchange: 'US', sector: "Communication Services", searchableTerms: [] },
  { symbol: "TSCO", name: "Tractor Supply", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "TT", name: "Trane Technologies", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "TDG", name: "TransDigm Group", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "TRV", name: "Travelers Companies (The)", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "TRMB", name: "Trimble Inc.", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "TFC", name: "Truist Financial", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "TYL", name: "Tyler Technologies", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "TSN", name: "Tyson Foods", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "USB", name: "U.S. Bancorp", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "UBER", name: "Uber", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "UDR", name: "UDR, Inc.", type: 'stock', exchange: 'US', sector: "Real Estate", searchableTerms: [] },
  { symbol: "ULTA", name: "Ulta Beauty", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "UNP", name: "Union Pacific Corporation", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "UAL", name: "United Airlines Holdings", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "UPS", name: "United Parcel Service", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "URI", name: "United Rentals", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "UNH", name: "UnitedHealth Group", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "UHS", name: "Universal Health Services", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "VLO", name: "Valero Energy", type: 'stock', exchange: 'US', sector: "Energy", searchableTerms: [] },
  { symbol: "VTR", name: "Ventas", type: 'stock', exchange: 'US', sector: "Real Estate", searchableTerms: [] },
  { symbol: "VLTO", name: "Veralto", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "VRSN", name: "Verisign", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "VRSK", name: "Verisk Analytics", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "VZ", name: "Verizon", type: 'stock', exchange: 'US', sector: "Communication Services", searchableTerms: [] },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "VRT", name: "Vertiv", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "VTRS", name: "Viatris", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "VICI", name: "Vici Properties", type: 'stock', exchange: 'US', sector: "Real Estate", searchableTerms: [] },
  { symbol: "V", name: "Visa Inc.", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "VST", name: "Vistra Corp.", type: 'stock', exchange: 'US', sector: "Utilities", searchableTerms: [] },
  { symbol: "VMC", name: "Vulcan Materials Company", type: 'stock', exchange: 'US', sector: "Materials", searchableTerms: [] },
  { symbol: "WRB", name: "W. R. Berkley Corporation", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "GWW", name: "W. W. Grainger", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "WAB", name: "Wabtec", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "WMT", name: "Walmart", type: 'stock', exchange: 'US', sector: "Consumer Staples", searchableTerms: [] },
  { symbol: "DIS", name: "Walt Disney Company (The)", type: 'stock', exchange: 'US', sector: "Communication Services", searchableTerms: [] },
  { symbol: "WBD", name: "Warner Bros. Discovery", type: 'stock', exchange: 'US', sector: "Communication Services", searchableTerms: [] },
  { symbol: "WM", name: "Waste Management", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "WAT", name: "Waters Corporation", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "WEC", name: "WEC Energy Group", type: 'stock', exchange: 'US', sector: "Utilities", searchableTerms: [] },
  { symbol: "WFC", name: "Wells Fargo", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "WELL", name: "Welltower", type: 'stock', exchange: 'US', sector: "Real Estate", searchableTerms: [] },
  { symbol: "WST", name: "West Pharmaceutical Services", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "WDC", name: "Western Digital", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "WY", name: "Weyerhaeuser", type: 'stock', exchange: 'US', sector: "Real Estate", searchableTerms: [] },
  { symbol: "WSM", name: "Williams-Sonoma, Inc.", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "WMB", name: "Williams Companies", type: 'stock', exchange: 'US', sector: "Energy", searchableTerms: [] },
  { symbol: "WTW", name: "Willis Towers Watson", type: 'stock', exchange: 'US', sector: "Financials", searchableTerms: [] },
  { symbol: "WDAY", name: "Workday, Inc.", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "WYNN", name: "Wynn Resorts", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "XEL", name: "Xcel Energy", type: 'stock', exchange: 'US', sector: "Utilities", searchableTerms: [] },
  { symbol: "XYL", name: "Xylem Inc.", type: 'stock', exchange: 'US', sector: "Industrials", searchableTerms: [] },
  { symbol: "YUM", name: "Yum! Brands", type: 'stock', exchange: 'US', sector: "Consumer Discretionary", searchableTerms: [] },
  { symbol: "ZBRA", name: "Zebra Technologies", type: 'stock', exchange: 'US', sector: "Information Technology", searchableTerms: [] },
  { symbol: "ZBH", name: "Zimmer Biomet", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
  { symbol: "ZTS", name: "Zoetis", type: 'stock', exchange: 'US', sector: "Health Care", searchableTerms: [] },
] as const;
