import type { DiagnosticQuestion } from './types';

/**
 * 15-question diagnostic. Difficulty increases by band.
 * Scoring is deterministic: 1 point per correct answer.
 */
export const DIAGNOSTIC_QUESTIONS: DiagnosticQuestion[] = [
    {
        id: 'd1',
        band: 'beginner',
        type: 'multiple_choice',
        topic: 'money',
        prompt: 'What is money mainly used for?',
        options: [
            'Only for collecting coins',
            'To buy goods and services, and to save for later',
            'To guarantee you will get rich',
            'To replace every other kind of value',
        ],
        answer: 1,
        explanationCorrect: 'Correct! Money is a tool for buying things you need and saving for later.',
        explanationIncorrect: 'Not quite. Money is a tool people use to buy goods and services and to save for the future.',
    },
    {
        id: 'd2',
        band: 'beginner',
        type: 'compare',
        topic: 'saving vs investing',
        prompt: 'Maya puts $50 in a savings account. Jordan buys a tiny piece of a company. Who is investing?',
        options: [
            'Maya, because saving and investing are the same',
            'Jordan, because investing means buying something that might grow in value — and can also lose value',
            'Both, because any use of money is investing',
            'Neither, because investing is only for adults with huge accounts',
        ],
        answer: 1,
        explanationCorrect: 'Correct! Saving keeps money safer and easier to reach. Investing means buying assets that can grow — and can also lose value.',
        explanationIncorrect: 'Not quite. Saving is setting money aside. Investing is buying assets (like stocks) that can rise or fall in value.',
    },
    {
        id: 'd3',
        band: 'beginner',
        type: 'multiple_choice',
        topic: 'stocks',
        prompt: 'If you buy a stock, what do you own?',
        options: [
            'A loan you made to the company',
            'A tiny piece of ownership in that company',
            'A promise the price can never fall',
            'The company\'s buildings and trucks directly',
        ],
        answer: 1,
        explanationCorrect: 'Correct! A stock is a share of ownership in a company — not a loan, and not a promise of profit.',
        explanationIncorrect: 'Not quite. A stock is a small piece of ownership in a company. It can gain or lose value.',
    },
    {
        id: 'd4',
        band: 'beginner',
        type: 'scenario',
        topic: 'personal finance',
        prompt: 'You get $20 for a birthday. What is the safest first step before investing it?',
        options: [
            'Spend it all so you never have to choose',
            'Put it toward needs and a small savings cushion first, then consider investing extra money',
            'Buy the most popular stock you saw in a video',
            'Borrow more money so you can invest a bigger amount',
        ],
        answer: 1,
        explanationCorrect: 'Correct! Needs and a savings cushion come first. Investing uses extra money you can leave invested — and that you can afford to see go up or down.',
        explanationIncorrect: 'Not quite. A common healthy order is: cover needs, keep some savings, then invest money you can leave invested. Investing can lose value.',
    },
    {
        id: 'd5',
        band: 'basic',
        type: 'compare',
        topic: 'bonds',
        prompt: 'Lee buys a share of a company. Nia buys a bond from the same company. What is the biggest difference?',
        options: [
            'Both own the company equally, so the names do not matter',
            'Lee owns a tiny piece of the company; Nia is lending the company money and may get interest',
            'Nia owns the company, and Lee is only lending money',
            'Bonds can never lose value, so Nia has zero risk',
        ],
        answer: 1,
        explanationCorrect: 'Correct! A stock is ownership. A bond is a loan. Bonds can still lose value if you sell early or the borrower has trouble paying.',
        explanationIncorrect: 'Not quite. A stock is a slice of ownership. A bond is an IOU — you are the lender. Bonds are not risk-free.',
    },
    {
        id: 'd6',
        band: 'basic',
        type: 'scenario',
        topic: 'risk',
        prompt: 'Two practice portfolios start at $100. After a rough month, Portfolio A is $70 and Portfolio B is $97. Which statement is most careful?',
        options: [
            'A is safer because bigger swings always mean bigger future gains',
            'A moved more, so it showed more risk this month — but next month is still unknown',
            'B cannot lose money from here because it barely moved',
            'Neither portfolio has risk because this is only practice',
        ],
        answer: 1,
        explanationCorrect: 'Correct! Risk includes how wildly results can change — including losing money. A bigger drop this month does not promise a bigger rebound later.',
        explanationIncorrect: 'Not quite. The larger drop means A wiggled more this month. That is one picture of risk. It does not lock in what happens next, and B can still fall.',
    },
    {
        id: 'd7',
        band: 'basic',
        type: 'calculation',
        topic: 'return',
        prompt: 'You invest $80. Later it is worth $68. What is your return before fees?',
        options: [
            'A $12 gain, or +15%',
            'A $12 loss, or −15%',
            '$68, because that is the new total',
            '0%, because you did not sell yet',
        ],
        answer: 1,
        explanationCorrect: 'Correct! Return can be negative. $80 → $68 is a $12 loss, which is 12/80 = 15% down. Not selling does not erase the drop.',
        explanationIncorrect: 'Not quite. $80 down to $68 is a $12 loss (15%). Return is the change in value, even if you have not sold yet.',
    },
    {
        id: 'd8',
        band: 'basic',
        type: 'compare',
        topic: 'diversification',
        prompt: 'Which practice mix is more diversified — and what is still true?',
        options: [
            'Five different video-game companies, because five is always enough',
            'A U.S. stock fund plus an international fund plus a bond fund — and it can still lose value',
            'One famous tech stock, because famous companies do not fall',
            'Cash only, because cash is the same as a diversified stock mix',
        ],
        answer: 1,
        explanationCorrect: 'Correct! Spreading across types of assets and regions is more diversified than five similar companies. Diversification lowers some risk — it does not erase losses.',
        explanationIncorrect: 'Not quite. Five companies in the same industry can still move together. A mix of stocks and bonds across regions is more spread out, and it can still fall.',
    },
    {
        id: 'd9',
        band: 'intermediate',
        type: 'compare',
        topic: 'ETFs',
        prompt: 'Priya wants many companies in one purchase. Which choice matches that goal best, and what should she remember?',
        options: [
            'One popular stock, because one company already stands for the whole market',
            'An ETF or similar fund that holds a basket of investments — it can still lose value and may charge a small fee',
            'A bond from one city, because bonds never drop',
            'Any investment labeled “fund,” because all funds are guaranteed by the government',
        ],
        answer: 1,
        explanationCorrect: 'Correct! An ETF is a basket you can buy like a stock. It can help you diversify, but the basket can still fall, and fees matter.',
        explanationIncorrect: 'Not quite. One stock is not a basket. An ETF holds many investments and trades like a stock. It is not a guarantee, and costs still count.',
    },
    {
        id: 'd10',
        band: 'intermediate',
        type: 'calculation',
        topic: 'compound growth',
        prompt: '$200 grows 10% in year 1. In year 2 it falls 10%. About what is it worth, and what does that teach?',
        options: [
            '$200, because +10% and −10% always cancel',
            'About $198, because the 10% drop applies to $220, not to the original $200',
            '$240, because two years always add 20%',
            '$180, because you subtract 10% twice from $200',
        ],
        answer: 1,
        explanationCorrect: 'Correct! Year 1: $200 × 1.10 = $220. Year 2: $220 × 0.90 = $198. Equal up-and-down percents do not cancel. Real years can be worse.',
        explanationIncorrect: 'Not quite. After +10% you have $220. Then −10% of $220 is $22, leaving $198. Percentage gains and losses are not simple opposites.',
    },
    {
        id: 'd11',
        band: 'intermediate',
        type: 'scenario',
        topic: 'market prices',
        prompt: 'A company reports higher sales than last year, but investors expected even higher sales. Many people sell. What is the most accurate takeaway?',
        options: [
            'Good news always lifts the price the same day',
            'Prices often move on surprise versus what people expected — so the stock may fall even after “better than last year”',
            'The exchange freezes the price until the next year',
            'Sales reports cannot affect prices at all',
        ],
        answer: 1,
        explanationCorrect: 'Correct! Markets react to surprise. Beating last year but missing expectations can still bring selling. One day is not a guarantee either way.',
        explanationIncorrect: 'Not quite. Investors compare results with what they already expected. A miss versus those hopes can push a price down even if sales grew.',
    },
    {
        id: 'd12',
        band: 'intermediate',
        type: 'calculation',
        topic: 'fees',
        prompt: 'Your investment grows 6% in a year, inflation is 3%, and a yearly fee is 1%. Which sentence is most honest?',
        options: [
            'You “made 6%” in real life, because fees and inflation do not count',
            'After a rough real-life check, you kept about 2% of purchasing power — and some years this math is negative',
            'Inflation adds to your return, so you made about 10%',
            'Fees only matter if you sell',
        ],
        answer: 1,
        explanationCorrect: 'Correct! 6% − 3% inflation − 1% fee is about 2% in buying power. Costs and rising prices can wipe out a headline gain. This is not a promise for next year.',
        explanationIncorrect: 'Not quite. Inflation reduces what money buys, and fees take a slice. 6% − 3% − 1% is about 2% real, and some years the leftover is below zero.',
    },
    {
        id: 'd13',
        band: 'advanced',
        type: 'chart',
        topic: 'charts',
        prompt: 'The chart shows $20, then $32, then $24. Which reading is strongest?',
        options: [
            'The stock is “in a bull market forever” because it ended above $20',
            'It rose 60% from the first point, then gave back half of that gain — history only, not a forecast',
            'It must return to $32 next, because charts always complete a pattern',
            'A 25% drop from $32 to $24 means the company is bankrupt',
        ],
        answer: 1,
        explanationCorrect: 'Correct! $20 → $32 is a $12 rise. $32 → $24 gives back $8 of that $12. Charts record the past. They do not promise the next print.',
        explanationIncorrect: 'Not quite. The path is up, then partway down. Ending above the start does not make the future safe, and a drop is not the same as bankruptcy.',
        chart: {
            kind: 'line',
            title: 'Sample price path',
            labels: ['Start', 'Peak', 'Later'],
            values: [20, 32, 24],
        },
    },
    {
        id: 'd14',
        band: 'advanced',
        type: 'calculation',
        topic: 'valuation',
        prompt: 'Company A: price $40, earnings $2 per share. Company B: price $18, earnings $1 per share. What is fair to say?',
        options: [
            'B is automatically the better buy because $18 is a lower price',
            'A’s P/E is 20 and B’s P/E is 18, so B looks a bit cheaper on that one ratio — and P/E still is not a full story',
            'A is risk-free because a higher price means a stronger company',
            'P/E cannot be compared unless both companies are in different countries',
        ],
        answer: 1,
        explanationCorrect: 'Correct! P/E is price ÷ earnings per share. 40/2 = 20 and 18/1 = 18. A lower P/E can mean a cheaper sticker relative to earnings, but debt, growth, and quality still matter. Neither is a guaranteed winner.',
        explanationIncorrect: 'Not quite. Cheap-looking share price is not the same as cheap versus earnings. 40÷2=20 and 18÷1=18. Use P/E as one clue, not a trophy.',
    },
    {
        id: 'd15',
        band: 'advanced',
        type: 'scenario',
        topic: 'investing decisions',
        prompt: 'A livestream says: “This ETF is diversified, so it cannot fall. Lock in 25% this month or you will miss it.” What is the best student response?',
        options: [
            'Buy immediately — diversification plus a deadline means the return is safe',
            'Reject the pitch: a diversified fund can still lose value, “cannot fall” is false, and pressure plus a promised high return is a classic red flag',
            'Sell every other investment first, then decide tomorrow',
            'The 25% promise is fine if the person sounds confident',
        ],
        answer: 1,
        explanationCorrect: 'Correct! Diversification reduces some risk; it does not make losses impossible. Investor.gov flags “high return / little risk” and hurry-up pressure as scam warning signs.',
        explanationIncorrect: 'Not quite. Diversified investments can still drop. A guaranteed-sounding monthly gain plus “act now” is a warning, not a reason to rush.',
    },
];
