import type { AcademyRankId, QuizQuestion } from './types';

export interface RankUpTest {
    fromRank: AcademyRankId;
    toRank: AcademyRankId;
    title: string;
    questions: QuizQuestion[];
}

/**
 * Four rank-up tests (25 questions each). Pass score is 16/25, scored in the store.
 * Each test covers all 20 lessons of that rank, plus five review questions.
 */
export const RANK_UP_TESTS: RankUpTest[] = [
    {
        fromRank: 1,
        toRank: 2,
        title: 'Just Starting → Money Explorer',
        questions: [
            {
                id: 'r1-q1',
                type: 'multiple_choice',
                topic: 'money',
                prompt: 'What is money mainly used for?',
                options: [
                    'To guarantee you will get rich',
                    'To buy goods and services, and to save for later',
                    'Only to collect coins and bills',
                    'To replace every other kind of value forever',
                ],
                answer: 1,
                explanationCorrect: 'Correct! Money is a tool for buying things you need and saving for later. It is not a promise of wealth.',
                explanationIncorrect: 'Not quite. Money is a tool people use to buy goods and services and to save for the future — not a guarantee you will get rich.',
            },
            {
                id: 'r1-q2',
                type: 'compare',
                topic: 'saving',
                prompt: 'Sam puts $40 in a savings account. Riley buys a tiny piece of a company. Who is investing?',
                options: [
                    'Sam, because saving and investing are the same thing',
                    'Riley, because investing means buying something that might grow — and can also lose value',
                    'Both, because any use of money is investing',
                    'Neither, because investing is only for people with huge accounts',
                ],
                answer: 1,
                explanationCorrect: 'Correct! Saving keeps money safer and easier to reach. Investing means buying assets that can grow or fall in value.',
                explanationIncorrect: 'Not quite. Saving is setting money aside. Investing is buying assets (like stocks) that can rise or fall. They are not the same.',
            },
            {
                id: 'r1-q3',
                type: 'multiple_choice',
                topic: 'investing',
                prompt: 'What does investing mean, in simple words?',
                options: [
                    'Spending all your money today so you have more fun',
                    'Hiding cash so nobody can find it',
                    'Using money to buy assets that might grow over time — with a real chance of loss',
                    'A promise that your money will double every year',
                ],
                answer: 2,
                explanationCorrect: 'Correct! Investing means putting money into assets that may grow. Growth is not guaranteed, and you can lose money.',
                explanationIncorrect: 'Not quite. Investing is buying assets that might grow over time. Results can be negative. It is not a promise of profit.',
            },
            {
                id: 'r1-q4',
                type: 'multiple_choice',
                topic: 'stock market',
                prompt: 'What is the stock market?',
                options: [
                    'A store that sells only one company',
                    'A place (and a system) where people buy and sell pieces of companies',
                    'A government program that sets every stock price',
                    'A savings account with a locked interest rate',
                ],
                answer: 1,
                explanationCorrect: 'Correct! The stock market is where buyers and sellers trade shares. Prices can rise or fall. Nothing is locked in.',
                explanationIncorrect: 'Not quite. The stock market is a marketplace for company shares. Prices move with supply and demand — they are not fixed.',
            },
            {
                id: 'r1-q5',
                type: 'multiple_choice',
                topic: 'stocks',
                prompt: 'If you buy a stock, what do you own?',
                options: [
                    'A tiny piece of ownership in that company',
                    'A loan you made to the company',
                    'A promise the price can never fall',
                    'The company\'s buildings and trucks directly',
                ],
                answer: 0,
                explanationCorrect: 'Correct! A stock is a share of ownership — not a loan, and not a promise of profit. The value can go down.',
                explanationIncorrect: 'Not quite. A stock is a small piece of ownership in a company. It can gain or lose value. It is not a loan or a guarantee.',
            },
            {
                id: 'r1-q6',
                type: 'scenario',
                topic: 'prices',
                prompt: 'A company reports worse sales than people expected. Many investors want to sell. What often happens to the stock price?',
                options: [
                    'It is frozen by the exchange until the news is forgotten',
                    'It must rise because bad news always gets over-sold',
                    'It may fall because more people want to sell than buy — but one day is never guaranteed',
                    'It becomes a bond automatically',
                ],
                answer: 2,
                explanationCorrect: 'Correct! Prices move with supply and demand. Disappointing news often leads to selling, but prices can still surprise you.',
                explanationIncorrect: 'Not quite. Prices usually reflect supply and demand. Disappointing news often brings more sellers, which can push the price down — not always, and not forever.',
            },
            {
                id: 'r1-q7',
                type: 'multiple_choice',
                topic: 'ownership',
                prompt: 'What does it mean to own a share of a company?',
                options: [
                    'You are the only boss and can take any product home',
                    'You own a small slice of the business and share in its future — good or bad',
                    'The company must pay you a salary',
                    'You can never lose money on that share',
                ],
                answer: 1,
                explanationCorrect: 'Correct! Shareholders own a slice of the company. If the business does well, that slice may be worth more. If it does poorly, it may be worth less.',
                explanationIncorrect: 'Not quite. Owning a share means you own a small piece of the company. That piece can rise or fall in value. You are not guaranteed pay or safety.',
            },
            {
                id: 'r1-q8',
                type: 'multiple_choice',
                topic: 'shares',
                prompt: 'What is a share?',
                options: [
                    'A coupon that always pays $1',
                    'A type of bank loan with no risk',
                    'One unit of ownership in a company — also called a stock',
                    'A receipt that proves the price will only go up',
                ],
                answer: 2,
                explanationCorrect: 'Correct! A share is one unit of ownership (equity). Many shares make up the company. Share prices can fall.',
                explanationIncorrect: 'Not quite. A share is one piece of ownership in a company. It is not a risk-free loan or a promise that the price will rise.',
            },
            {
                id: 'r1-q9',
                type: 'multiple_choice',
                topic: 'exchanges',
                prompt: 'What is a stock exchange (like the NYSE or Nasdaq)?',
                options: [
                    'A classroom where companies teach math',
                    'An organized marketplace where listed stocks are bought and sold',
                    'A vault that stores every company\'s cash',
                    'A rule that stock prices can only go up',
                ],
                answer: 1,
                explanationCorrect: 'Correct! An exchange is a marketplace with rules. It helps buyers and sellers meet. It does not protect you from losses.',
                explanationIncorrect: 'Not quite. An exchange is where listed stocks trade. It organizes the market — it does not lock prices or remove risk.',
            },
            {
                id: 'r1-q10',
                type: 'compare',
                topic: 'market mood',
                prompt: 'What is the difference between a bull market and a bear market?',
                options: [
                    'Bulls mean prices are generally rising; bears mean prices are generally falling — neither lasts forever',
                    'Bulls are safe; bears are illegal',
                    'They are two names for the exact same thing',
                    'A bull market means every stock is guaranteed to rise',
                ],
                answer: 0,
                explanationCorrect: 'Correct! “Bull” usually means a stretch of rising prices; “bear” means a stretch of falling prices. Moods change, and individual stocks can still move the other way.',
                explanationIncorrect: 'Not quite. A bull market is a period when prices are generally up. A bear market is a period when prices are generally down. Neither is permanent or risk-free.',
            },
            {
                id: 'r1-q11',
                type: 'multiple_choice',
                topic: 'portfolio',
                prompt: 'What is a portfolio?',
                options: [
                    'A single stock you can never sell',
                    'The group of investments you hold together',
                    'A type of fee the exchange charges',
                    'A promise that your mix will always grow',
                ],
                answer: 1,
                explanationCorrect: 'Correct! A portfolio is your collection of holdings. It can be one thing or many. The whole mix can still lose value.',
                explanationIncorrect: 'Not quite. A portfolio is the set of investments you own. Building one does not guarantee a profit.',
            },
            {
                id: 'r1-q12',
                type: 'multiple_choice',
                topic: 'risk',
                prompt: 'In investing, what does risk usually mean?',
                options: [
                    'A fee the government always charges',
                    'A sign that an investment is fake',
                    'The chance that results will be different from what you hoped — including losing money',
                    'A promise of higher returns with no downside',
                ],
                answer: 2,
                explanationCorrect: 'Correct! Risk means results can be better or worse than you expected. You can lose money.',
                explanationIncorrect: 'Not quite. Risk means uncertainty — including the chance of losing money. Higher possible returns often come with more risk, not a guarantee.',
            },
            {
                id: 'r1-q13',
                type: 'calculation',
                topic: 'return',
                prompt: 'You invest $100. A year later it is worth $90. What was your return?',
                options: [
                    'A $10 gain, because you still have most of the money',
                    '0%, because you did not sell yet',
                    'A guaranteed rebound next year',
                    'A $10 loss, which is a −10% return',
                ],
                answer: 3,
                explanationCorrect: 'Correct! Return is how much you gained or lost. $100 → $90 is a $10 loss, or −10%. Past return does not promise the next year.',
                explanationIncorrect: 'Not quite. Return is the change in value. $100 → $90 is a $10 loss (−10%), even if you have not sold. Losses are real.',
            },
            {
                id: 'r1-q14',
                type: 'scenario',
                topic: 'time',
                prompt: 'Kai wants money for a bike next month. Priya is saving for a goal 15 years away. Who is usually a better fit for stocks?',
                options: [
                    'Kai, because stocks always bounce back in a month',
                    'Priya, because a longer time horizon can give more room to ride out ups and downs — though losses are still possible',
                    'Both equally, because time never matters',
                    'Neither, because stocks are only for people who need cash tomorrow',
                ],
                answer: 1,
                explanationCorrect: 'Correct! Investing often works better when you can leave money invested for years. Short-term needs usually belong in safer savings. Time does not erase risk.',
                explanationIncorrect: 'Not quite. Stocks can swing a lot in a short time. Money you need soon is often better in savings. A longer horizon can help, but it is not a guarantee.',
            },
            {
                id: 'r1-q15',
                type: 'calculation',
                topic: 'compound growth',
                prompt: 'If $100 grows 10% in year 1, you have $110. If it grows 10% again in year 2, about how much do you have?',
                options: [
                    '$120, because 10% + 10% is always $20',
                    '$100, because growth resets each year',
                    '$121, because the second 10% applies to $110, not just the original $100',
                    '$200, because compounding doubles money every two years',
                ],
                answer: 2,
                explanationCorrect: 'Correct! Compounding means you can earn returns on earlier returns: $110 × 1.10 = $121. Real results vary and can be negative.',
                explanationIncorrect: 'Not quite. Compounding applies the new return to the new total ($110 × 10% = $11 more, so $121). It is not a promise of future growth.',
            },
            {
                id: 'r1-q16',
                type: 'multiple_choice',
                topic: 'dividends',
                prompt: 'What is a dividend?',
                options: [
                    'A cash payout some companies share with owners — it can be cut or stopped',
                    'A fee you always pay to buy a stock',
                    'A promise that the stock price will rise by the same amount',
                    'Interest you earn on every savings account',
                ],
                answer: 0,
                explanationCorrect: 'Correct! A dividend is a payout of company cash to shareholders. Companies can reduce or cancel dividends. Not every stock pays one.',
                explanationIncorrect: 'Not quite. A dividend is money some companies pay to owners. It is optional for the company and is not a promise the price will rise.',
            },
            {
                id: 'r1-q17',
                type: 'multiple_choice',
                topic: 'indexes',
                prompt: 'What is a stock index?',
                options: [
                    'A single stock that never changes',
                    'A list or score that tracks a group of stocks, used as a market yardstick',
                    'A type of savings account',
                    'A government guarantee of profit',
                ],
                answer: 1,
                explanationCorrect: 'Correct! An index summarizes how a basket of stocks is doing. It is a benchmark, not a promise your own investments will match it.',
                explanationIncorrect: 'Not quite. An index tracks a group of stocks so people can see how that slice of the market moved. It is not a guarantee.',
            },
            {
                id: 'r1-q18',
                type: 'multiple_choice',
                topic: 'S&P 500',
                prompt: 'What is the S&P 500?',
                options: [
                    'The 500 smallest companies in the world',
                    'A savings rate set by one bank',
                    'An index of about 500 large U.S. companies — it can still fall in value',
                    'A fund that is legally not allowed to lose money',
                ],
                answer: 2,
                explanationCorrect: 'Correct! The S&P 500 tracks many large U.S. companies. It is widely used as a market snapshot. It has fallen hard in bad years.',
                explanationIncorrect: 'Not quite. The S&P 500 is an index of about 500 large U.S. companies. It is not risk-free and does not always go up.',
            },
            {
                id: 'r1-q19',
                type: 'compare',
                topic: 'diversification',
                prompt: 'Which student is more diversified?',
                options: [
                    'Ava puts all her practice money into one company she likes',
                    'Ben spreads practice money across several companies and a fund that holds many stocks',
                    'Both are equally diversified because they both invested',
                    'Neither, because diversification only works with gold',
                ],
                answer: 1,
                explanationCorrect: 'Correct! Diversification means spreading money so one bad result hurts less. It does not remove all risk.',
                explanationIncorrect: 'Not quite. Diversification means spreading investments. One company is concentrated; a mix is more diversified — though losses are still possible.',
            },
            {
                id: 'r1-q20',
                type: 'scenario',
                topic: 'practice',
                prompt: 'You are building your first practice portfolio in a simulator. What is the main point?',
                options: [
                    'To prove you can pick a stock that never falls',
                    'To spend real money as fast as possible',
                    'To copy a stranger\'s "can\'t lose" tip without reading anything',
                    'To practice buying, holding, and watching a mix — and to learn that paper gains and losses feel different from real ones',
                ],
                answer: 3,
                explanationCorrect: 'Correct! A practice portfolio is for learning. You can try ideas safely. Real investing still has real risk, fees, and emotions.',
                explanationIncorrect: 'Not quite. Practice is for learning how a portfolio works — not for proving you are never wrong. Simulated results are not a promise of real-life results.',
            },
            {
                id: 'r1-q21',
                type: 'chart',
                topic: 'compound growth',
                prompt: 'This chart shows $100 left to grow at 10% a year in a simple example. What is the fairest reading?',
                options: [
                    'The money is guaranteed to follow this path in real life',
                    'Compounding can speed up as the balance grows — but real returns vary and can be negative',
                    'After year 3, the money can never fall',
                    'Charts like this prove stocks always go up',
                ],
                answer: 1,
                explanationCorrect: 'Correct! The example shows compounding on a growing balance. Real investments do not grow in a straight, safe line.',
                explanationIncorrect: 'Not quite. This is a simple 10%-a-year example. Real returns bounce around and can be losses. Charts of the past or of examples are not promises.',
                chart: {
                    kind: 'line',
                    title: 'Example: $100 at 10% a year',
                    labels: ['Start', 'Year 1', 'Year 2', 'Year 3'],
                    values: [100, 110, 121, 133],
                },
            },
            {
                id: 'r1-q22',
                type: 'scenario',
                topic: 'risk',
                prompt: 'You need $80 next week to pay for a class trip. Where does that $80 usually belong?',
                options: [
                    'In one popular stock, because you need growth fast',
                    'In a mix of the riskiest companies you can find',
                    'In savings you can reach, not in investments you might have to sell after a drop',
                    'Borrowed, so you can invest a bigger amount',
                ],
                answer: 2,
                explanationCorrect: 'Correct! Money you need soon should stay reachable. Investing can lose value right when you need the cash.',
                explanationIncorrect: 'Not quite. Short-term needs usually belong in savings. Stocks can drop in a week. Do not invest money you cannot afford to see fall.',
            },
            {
                id: 'r1-q23',
                type: 'compare',
                topic: 'return',
                prompt: 'Which statement about risk and return is most honest?',
                options: [
                    'Higher possible returns usually come with a greater chance of bigger losses',
                    'Higher return always means lower risk',
                    'If you wait one year, risk disappears',
                    'Safe investments always pay the most',
                ],
                answer: 0,
                explanationCorrect: 'Correct! Bigger possible rewards usually come with bigger possible losses. Nothing removes risk completely.',
                explanationIncorrect: 'Not quite. In markets, higher hoped-for returns usually mean more risk. Time can help, but it does not erase the chance of loss.',
            },
            {
                id: 'r1-q24',
                type: 'chart',
                topic: 'stock market',
                prompt: 'A simple chart shows a stock at $40 in January, $48 in March, and $44 in June. What is a fair reading?',
                options: [
                    'The stock only went up, so it is safe',
                    'The stock is guaranteed to return to $48',
                    'The price rose, then fell some — charts show history, not a promise of what happens next',
                    'Charts can only be used by professionals',
                ],
                answer: 2,
                explanationCorrect: 'Correct! Charts summarize past prices. They do not guarantee the next move.',
                explanationIncorrect: 'Not quite. That path is up, then down a bit. Past prices on a chart are history — not a guarantee.',
                chart: {
                    kind: 'line',
                    title: 'Sample price path',
                    labels: ['Jan', 'Mar', 'Jun'],
                    values: [40, 48, 44],
                },
            },
            {
                id: 'r1-q25',
                type: 'multiple_choice',
                topic: 'investing',
                prompt: 'A video says: "Stocks always go up if you just wait." What should you believe?',
                options: [
                    'It is true for every stock and every time period',
                    'It is true only for the S&P 500',
                    'It is true if you own more than three stocks',
                    'It is false — markets and single stocks can stay down or fail, even over long stretches',
                ],
                answer: 3,
                explanationCorrect: 'Correct! Stocks do not always go up. Companies can fail, and markets can have long, painful drops. Risk is real.',
                explanationIncorrect: 'Not quite. "Always go up" is not true. Even broad markets have fallen hard, and individual stocks can go to zero. Time helps, but it is not a shield.',
            },
        ],
    },
    {
        fromRank: 2,
        toRank: 3,
        title: 'Money Explorer → Investing Builder',
        questions: [
            {
                id: 'r2-q1',
                type: 'compare',
                topic: 'bonds',
                prompt: 'What is the core difference between a stock and a bond?',
                options: [
                    'A stock is a loan; a bond is ownership',
                    'A stock is a slice of ownership; a bond is a loan that usually pays interest',
                    'They are the same product with two names',
                    'Bonds can never lose value; stocks always rise',
                ],
                answer: 1,
                explanationCorrect: 'Correct! Stocks are ownership. Bonds are loans. Both can lose value — bonds if you sell at the wrong time or if the borrower struggles.',
                explanationIncorrect: 'Not quite. Stocks = ownership. Bonds = IOUs (loans). Neither is a guarantee. Bond prices can fall, and stocks can fall too.',
            },
            {
                id: 'r2-q2',
                type: 'multiple_choice',
                topic: 'ETFs',
                prompt: 'What is an ETF (exchange-traded fund)?',
                options: [
                    'A single stock that never changes price',
                    'A type of bank account with a locked interest rate',
                    'A basket of investments you can buy like a stock, often used to diversify',
                    'A government promise of profit',
                ],
                answer: 2,
                explanationCorrect: 'Correct! An ETF is a basket of assets that trades on an exchange. It can help you diversify, but it can still lose value.',
                explanationIncorrect: 'Not quite. An ETF is a basket of investments that trades like a stock. It is not a guarantee of profit.',
            },
            {
                id: 'r2-q3',
                type: 'multiple_choice',
                topic: 'mutual funds',
                prompt: 'What is a mutual fund?',
                options: [
                    'A pool of money managed as one fund, often bought at the end of the day — not a promise of gain',
                    'A stock you can only buy at noon',
                    'A loan you make to your friends',
                    'A fee-free account that cannot lose money',
                ],
                answer: 0,
                explanationCorrect: 'Correct! A mutual fund pools many people\'s money and is usually priced once a day. Managers and fees matter. The fund can still fall.',
                explanationIncorrect: 'Not quite. A mutual fund is a pooled investment, typically priced after the market closes. It can lose value, and fees reduce your return.',
            },
            {
                id: 'r2-q4',
                type: 'multiple_choice',
                topic: 'index funds',
                prompt: 'What is an index fund trying to do?',
                options: [
                    'Beat every stock picker every year',
                    'Hold only one "hot" company',
                    'Match a market index (like the S&P 500) instead of picking winners — usually with lower fees',
                    'Guarantee you will never have a down year',
                ],
                answer: 2,
                explanationCorrect: 'Correct! Index funds aim to copy an index, not outsmart it. Lower fees help, but the fund still falls when the index falls.',
                explanationIncorrect: 'Not quite. An index fund tracks a basket. It is passive, often cheaper, and still risky. Matching the market includes matching the market\'s losses.',
            },
            {
                id: 'r2-q5',
                type: 'compare',
                topic: 'company size',
                prompt: 'Large-cap, mid-cap, and small-cap companies mainly differ by…',
                options: [
                    'How many employees they have in one building',
                    'Whether they are allowed to pay dividends',
                    'The color of their logo',
                    'Company size (market value) — smaller companies often swing more and can be riskier',
                ],
                answer: 3,
                explanationCorrect: 'Correct! "Cap" is about market size. Small companies can grow fast or struggle more. Size is not a quality grade by itself.',
                explanationIncorrect: 'Not quite. Large / mid / small usually refers to market capitalization (size). Smaller names often have more volatility and business risk.',
            },
            {
                id: 'r2-q6',
                type: 'compare',
                topic: 'growth',
                prompt: 'Growth stocks vs value stocks — which is the fairest contrast?',
                options: [
                    'Growth names are priced for faster future growth; value names look cheaper vs today\'s numbers — both can disappoint',
                    'Value stocks never fall; growth stocks never rise',
                    'They are official labels the exchange stamps on every share',
                    'Growth always beats value if you wait one year',
                ],
                answer: 0,
                explanationCorrect: 'Correct! Growth investors pay for expected expansion. Value investors look for a lower price vs current measures. Either style can lose money.',
                explanationIncorrect: 'Not quite. Growth vs value is about style and price, not a guarantee. Cheap-looking stocks can stay cheap or get cheaper. Fast growers can miss.',
            },
            {
                id: 'r2-q7',
                type: 'calculation',
                topic: 'market cap',
                prompt: 'A company has 10 million shares. Each share trades at $20. What is its market cap?',
                options: [
                    '$20, because that is the share price',
                    '$10 million, because that is the share count',
                    '$200 million (shares × price)',
                    '$2 million, because you divide price by shares',
                ],
                answer: 2,
                explanationCorrect: 'Correct! Market cap ≈ share price × shares outstanding. $20 × 10 million = $200 million. It is a size snapshot, not a "true worth" stamp.',
                explanationIncorrect: 'Not quite. Market capitalization is price times the number of shares: $20 × 10 million = $200 million. It can change every day with the price.',
            },
            {
                id: 'r2-q8',
                type: 'multiple_choice',
                topic: 'revenue',
                prompt: 'What is revenue?',
                options: [
                    'The cash left after every cost and tax',
                    'Money the company borrows',
                    'A fee you pay to buy the stock',
                    'Sales — the top-line money a company brings in before subtracting most costs',
                ],
                answer: 3,
                explanationCorrect: 'Correct! Revenue is sales (the top line). A company can have big revenue and still lose money after costs.',
                explanationIncorrect: 'Not quite. Revenue means sales. Profit is what may be left after costs. High sales do not automatically mean a healthy business.',
            },
            {
                id: 'r2-q9',
                type: 'multiple_choice',
                topic: 'profit',
                prompt: 'What is profit (net income) in simple terms?',
                options: [
                    'The same thing as revenue',
                    'What may be left after the company pays its costs — it can be negative',
                    'The stock price times 10',
                    'A bonus every shareholder is guaranteed',
                ],
                answer: 1,
                explanationCorrect: 'Correct! Profit is leftover after expenses. Negative profit is a loss. Past profit does not lock in next year.',
                explanationIncorrect: 'Not quite. Profit is revenue minus costs (and more). It is not the same as sales, and it is not guaranteed to owners.',
            },
            {
                id: 'r2-q10',
                type: 'calculation',
                topic: 'EPS',
                prompt: 'A company earns $50 million in profit and has 25 million shares. What is earnings per share (EPS)?',
                options: [
                    '$2.00 ($50 million ÷ 25 million shares)',
                    '$50 million, because that is total profit',
                    '$25, because that is the share count',
                    '$0, because EPS is only for bonds',
                ],
                answer: 0,
                explanationCorrect: 'Correct! EPS = profit ÷ shares. $50m ÷ 25m = $2. One year of EPS is not a promise of the next year.',
                explanationIncorrect: 'Not quite. EPS splits total profit across shares: $50 million / 25 million = $2 per share. It can fall or turn negative.',
            },
            {
                id: 'r2-q11',
                type: 'calculation',
                topic: 'P/E',
                prompt: 'A stock is $40. EPS is $4. What is the P/E ratio, and what does it mean?',
                options: [
                    '4, which means the stock is risk-free',
                    '160, which means you multiply price by EPS',
                    '10 — you are paying $10 of price for each $1 of recent earnings; that is not a buy/sell signal by itself',
                    '0, because P/E only works on indexes',
                ],
                answer: 2,
                explanationCorrect: 'Correct! P/E = price ÷ EPS = 40 / 4 = 10. A lower or higher P/E is a clue, not a verdict. Losses make P/E messy or unused.',
                explanationIncorrect: 'Not quite. P/E is price divided by earnings per share: $40 / $4 = 10. It compares price to earnings. It does not say the stock is safe.',
            },
            {
                id: 'r2-q12',
                type: 'multiple_choice',
                topic: 'financials',
                prompt: 'Why do investors read company financials (income statement, balance sheet, cash flow)?',
                options: [
                    'Because the numbers predict the exact stock price next week',
                    'To see sales, profits, debts, and cash — clues, not a crystal ball',
                    'Because financials replace the need to think about risk',
                    'To find a hidden page that lists next year\'s guaranteed return',
                ],
                answer: 1,
                explanationCorrect: 'Correct! Financial statements show how the business has been doing. They help you ask better questions. They do not lock in future prices.',
                explanationIncorrect: 'Not quite. Financials are a report card on the business. They are useful and still backward-looking. They cannot remove market risk.',
            },
            {
                id: 'r2-q13',
                type: 'chart',
                topic: 'charts',
                prompt: 'This price chart goes $30 → $36 → $33. What can you fairly say?',
                options: [
                    'The stock is now safe because it is above $30',
                    'It must hit $36 again',
                    'The next month will be up, because two of three points rose',
                    'The price rose, then gave some back — the chart is history, not a forecast',
                ],
                answer: 3,
                explanationCorrect: 'Correct! You can describe the path. You cannot treat the path as a promise. Charts do not remove risk.',
                explanationIncorrect: 'Not quite. The line shows what already happened: up, then down a bit. That does not tell you the next move with certainty.',
                chart: {
                    kind: 'line',
                    title: 'Sample closing prices',
                    labels: ['Week 1', 'Week 2', 'Week 3'],
                    values: [30, 36, 33],
                },
            },
            {
                id: 'r2-q14',
                type: 'scenario',
                topic: 'orders',
                prompt: 'You place a market order to buy a stock that is moving fast. What should you expect?',
                options: [
                    'You will get the last price you saw on a screenshot, exactly',
                    'The order aims to fill now at the current market — the fill price can be different from what you hoped',
                    'The exchange will wait until the price is lower',
                    'Market orders cannot lose money because they fill quickly',
                ],
                answer: 1,
                explanationCorrect: 'Correct! A market order is about speed, not a locked-in price. In a fast market you may pay more (or receive less) than you expected.',
                explanationIncorrect: 'Not quite. Market orders seek an immediate fill. The price can slip. Speed is not the same as a good or safe price.',
            },
            {
                id: 'r2-q15',
                type: 'compare',
                topic: 'limit orders',
                prompt: 'How is a limit order different from a market order?',
                options: [
                    'A limit order sets the worst price you will accept; it might not fill',
                    'A limit order always fills instantly at any price',
                    'A market order lets you name a maximum; a limit order does not',
                    'They are identical except for the name',
                ],
                answer: 0,
                explanationCorrect: 'Correct! A buy limit says "no higher than this." A sell limit says "no lower than this." The trade may never happen.',
                explanationIncorrect: 'Not quite. Limit orders cap the price you will take. Protection on price means you might not get filled. Market orders chase a fill instead.',
            },
            {
                id: 'r2-q16',
                type: 'multiple_choice',
                topic: 'bid',
                prompt: 'What are the bid and the ask?',
                options: [
                    'Two nicknames for the closing price',
                    'The bid is what buyers are offering; the ask is what sellers want — the gap is the spread',
                    'Fees the government adds to every trade',
                    'Guaranteed prices for the next year',
                ],
                answer: 1,
                explanationCorrect: 'Correct! Buyers bid. Sellers ask. You usually buy near the ask and sell near the bid. A wide spread can cost you.',
                explanationIncorrect: 'Not quite. The bid is the highest buyers will pay right now. The ask is the lowest sellers will take. The difference is the spread — a real cost.',
            },
            {
                id: 'r2-q17',
                type: 'scenario',
                topic: 'fees',
                prompt: 'Two similar funds track the same index. Fund A charges 0.03% a year. Fund B charges 1.00%. If results before fees match, what happens?',
                options: [
                    'Fees never matter if the index is famous',
                    'Fund B must grow faster because it is more expensive',
                    'Fund A should keep more of the return — higher fees quietly eat your money',
                    'Both funds are guaranteed to match after fees',
                ],
                answer: 2,
                explanationCorrect: 'Correct! Costs compound against you. A higher fee for the same exposure usually means a worse result. Fees are a risk you can often reduce.',
                explanationIncorrect: 'Not quite. If two funds hold the same idea, the cheaper one usually leaves you with more. Expense ratios and commissions are real drags.',
            },
            {
                id: 'r2-q18',
                type: 'multiple_choice',
                topic: 'inflation',
                prompt: 'What does inflation do?',
                options: [
                    'It makes every stock price fall by law',
                    'It raises the interest rate on your piggy bank automatically',
                    'It means the same dollars buy less over time — cash sitting still can lose purchasing power',
                    'It only affects countries that do not have stock markets',
                ],
                answer: 2,
                explanationCorrect: 'Correct! Inflation is rising prices. $20 may buy fewer snacks later. Investments can try to outpace it — or they can lose to it.',
                explanationIncorrect: 'Not quite. Inflation reduces what money can buy. That is why long-term cash can lose "real" value. Investing can help or hurt depending on results.',
            },
            {
                id: 'r2-q19',
                type: 'calculation',
                topic: 'time value of money',
                prompt: 'Why is $100 today usually worth more than a promise of $100 in five years (ignoring gifts and inflation surprises)?',
                options: [
                    'Because you can use or invest today\'s $100 now — future money has a time cost and is less certain',
                    'Because $100 in five years is always $200 after inflation',
                    'Because money in the future is illegal',
                    'Because five-year money is guaranteed to be safer',
                ],
                answer: 0,
                explanationCorrect: 'Correct! Time value of money: cash in hand can be used or invested now. A future $100 is later and less certain. Investing that $100 can still lose value.',
                explanationIncorrect: 'Not quite. A dollar today can work for you now. A dollar later is delayed and not guaranteed. That is the time value of money — not a get-rich rule.',
            },
            {
                id: 'r2-q20',
                type: 'compare',
                topic: 'diversification',
                prompt: 'Which practice portfolio is generally better diversified?',
                options: [
                    '100% in one popular tech stock',
                    'Three companies that all make the same product',
                    'All cash under a mattress, labeled "stocks" for fun',
                    'A mix of a U.S. stock fund, an international fund, and a bond fund',
                ],
                answer: 3,
                explanationCorrect: 'Correct! Mixing different types of assets and regions is a classic way to diversify. Diversification still cannot eliminate all losses.',
                explanationIncorrect: 'Not quite. A mix of different assets (and often different regions) is more diversified than one stock or three similar companies.',
            },
            {
                id: 'r2-q21',
                type: 'chart',
                topic: 'market cap',
                prompt: 'These bars show three companies\' market caps (in billions). What is a fair takeaway?',
                options: [
                    'The largest bar is the safest stock',
                    'Size is different — the $400B company is largest here, but bigger is not automatically better or safer',
                    'The smallest company cannot lose money',
                    'You should always buy the middle bar',
                ],
                answer: 1,
                explanationCorrect: 'Correct! Market cap ranks size. A giant company can still have a falling stock. A small company can still succeed — or fail.',
                explanationIncorrect: 'Not quite. The bars only show size: 80, 200, and 400. Size is not a quality or safety score.',
                chart: {
                    kind: 'bars',
                    title: 'Sample market caps ($B)',
                    labels: ['Small Co', 'Mid Co', 'Large Co'],
                    values: [80, 200, 400],
                },
            },
            {
                id: 'r2-q22',
                type: 'scenario',
                topic: 'inflation',
                prompt: 'Groceries that cost $100 last year now cost $104. Your savings earned 1%. What happened to your "real" buying power?',
                options: [
                    'It rose by 1%, because the bank paid you',
                    'It stayed exactly the same',
                    'It slipped — prices rose faster than your savings grew',
                    'Inflation cannot affect savings',
                ],
                answer: 2,
                explanationCorrect: 'Correct! If prices rise 4% and your cash grows 1%, you can buy less. That gap is a real (inflation-adjusted) loss of power.',
                explanationIncorrect: 'Not quite. Inflation of about 4% beat 1% interest. Your dollars grew, but they buy less. That is why people think about real returns.',
            },
            {
                id: 'r2-q23',
                type: 'multiple_choice',
                topic: 'index funds',
                prompt: 'Why do many long-term learners start with a broad index fund or ETF?',
                options: [
                    'Because it is legally not allowed to fall',
                    'Because one stock is always safer',
                    'Because it can give instant diversification at a low cost — and it will still drop when markets drop',
                    'Because index funds pay a guaranteed salary',
                ],
                answer: 2,
                explanationCorrect: 'Correct! A broad index fund is a simple, low-cost mix of many companies. Simple does not mean safe. The whole market can fall.',
                explanationIncorrect: 'Not quite. Broad funds help you avoid betting on one name. They do not remove market risk or guarantee a return.',
            },
            {
                id: 'r2-q24',
                type: 'scenario',
                topic: 'P/E',
                prompt: 'Company A has a P/E of 8. Company B has a P/E of 40. What is the smartest first thought?',
                options: [
                    'A is always the better buy because the number is smaller',
                    'B is always better because a high P/E means quality',
                    'P/E is one clue about price vs earnings — you still need growth, debt, and the story, and either stock can fall',
                    'The higher P/E is a government safety rating',
                ],
                answer: 2,
                explanationCorrect: 'Correct! A low P/E can mean cheap or troubled. A high P/E can mean high hopes — or a bubble. One ratio is not a full decision.',
                explanationIncorrect: 'Not quite. P/E compares price to earnings. It is a starting point, not a trophy. Cheap-looking stocks can be cheap for a reason.',
            },
            {
                id: 'r2-q25',
                type: 'multiple_choice',
                topic: 'stocks',
                prompt: 'Which statement is most accurate after lessons 21–40?',
                options: [
                    'If you learn every ratio, stocks cannot lose money',
                    'Funds, orders, fees, and company numbers help you decide — they do not remove risk or make prices only go up',
                    'Bonds and stocks are risk-free if you hold overnight',
                    'Market orders lock in the price you saw yesterday',
                ],
                answer: 1,
                explanationCorrect: 'Correct! Tools like ETFs, P/E, and limit orders help you act with more skill. Skill is not a shield. Losses still happen.',
                explanationIncorrect: 'Not quite. Knowing products and numbers is useful. None of it makes investing safe or one-directional.',
            },
        ],
    },
    {
        fromRank: 3,
        toRank: 4,
        title: 'Investing Builder → Market Analyst',
        questions: [
            {
                id: 'r3-q1',
                type: 'multiple_choice',
                topic: 'asset allocation',
                prompt: 'What is asset allocation?',
                options: [
                    'Picking the one stock that will win this month',
                    'How you split money among types of assets (like stocks, bonds, and cash) — a main driver of risk',
                    'A fee you pay when you rebalance',
                    'A rule that stocks must be 100% of every account',
                ],
                answer: 1,
                explanationCorrect: 'Correct! Allocation is the mix. More stocks usually means more ups and downs. The mix should match your goal and stomach for loss.',
                explanationIncorrect: 'Not quite. Asset allocation is the big split among asset types. That mix often matters more than any single pick — and it can still lose money.',
            },
            {
                id: 'r3-q2',
                type: 'scenario',
                topic: 'risk tolerance',
                prompt: 'After a 20% drop, Jordan sleeps fine and sticks to the plan. Avery panics and cannot think about anything else. What does that suggest?',
                options: [
                    'Avery has a higher risk tolerance than Jordan',
                    'Risk tolerance is only about age, so both are the same',
                    'Jordan may have a higher risk tolerance — your mix should be one you can live with when prices fall',
                    'Panic means Avery should borrow money to buy more',
                ],
                answer: 2,
                explanationCorrect: 'Correct! Risk tolerance is how much loss you can handle without abandoning the plan. A "perfect" mix you cannot hold is not perfect.',
                explanationIncorrect: 'Not quite. Risk tolerance is personal comfort with loss. If a drop wrecks your sleep, the mix may be too aggressive — even if a textbook says otherwise.',
            },
            {
                id: 'r3-q3',
                type: 'compare',
                topic: 'time horizon',
                prompt: 'Who usually can take more stock-market risk (if they can handle the swings)?',
                options: [
                    'Someone who needs the money for rent in two months',
                    'Someone investing for a goal 20 years away',
                    'Someone who needs the money on Friday',
                    'Time horizon never changes the right mix',
                ],
                answer: 1,
                explanationCorrect: 'Correct! A longer horizon can give more time to recover from slumps. It does not guarantee recovery. Near-term cash needs are different.',
                explanationIncorrect: 'Not quite. Money you need soon usually cannot afford a big drop. A long horizon can support more stocks — with no promise of a happy ending.',
            },
            {
                id: 'r3-q4',
                type: 'multiple_choice',
                topic: 'dollar-cost averaging',
                prompt: 'What is dollar-cost averaging (DCA)?',
                options: [
                    'Investing a set amount on a regular schedule, so you buy more shares when prices are lower',
                    'Waiting to invest only on the single cheapest day of the year',
                    'Spending every dollar the day you get it',
                    'A trick that removes all risk if you use it for 12 months',
                ],
                answer: 0,
                explanationCorrect: 'Correct! DCA is steady, planned buying. It can reduce the stress of timing. It does not stop you from losing money in a long decline.',
                explanationIncorrect: 'Not quite. DCA means investing on a schedule. You still buy in falling and rising markets. It is a habit, not a shield.',
            },
            {
                id: 'r3-q5',
                type: 'scenario',
                topic: 'rebalancing',
                prompt: 'Your plan is 60% stocks and 40% bonds. After a big stock run, you are at 75% stocks. What is rebalancing?',
                options: [
                    'Buying even more of whatever just went up',
                    'Selling the whole portfolio and hiding cash',
                    'Selling some stocks and/or adding bonds to get back near 60/40 — you may sell winners on purpose',
                    'Ignoring the mix because winners should stay huge forever',
                ],
                answer: 2,
                explanationCorrect: 'Correct! Rebalancing puts the mix back on target. It can feel odd because you trim what rose. It is about risk, not a prediction.',
                explanationIncorrect: 'Not quite. Rebalancing restores your planned weights. Letting winners take over quietly raises risk. Rebalancing is not a promise of higher returns.',
            },
            {
                id: 'r3-q6',
                type: 'calculation',
                topic: 'weights',
                prompt: 'Your portfolio is worth $200. One holding is worth $50. What is that holding\'s weight?',
                options: [
                    '50%, because $50 is half of 100',
                    '25% ($50 ÷ $200)',
                    '200%',
                    'You cannot know without the stock\'s P/E',
                ],
                answer: 1,
                explanationCorrect: 'Correct! Weight = holding value ÷ portfolio value. $50 / $200 = 25%. Weights shift as prices move.',
                explanationIncorrect: 'Not quite. A $50 piece of a $200 portfolio is 25%. That percentage is the weight — and it will change when prices change.',
            },
            {
                id: 'r3-q7',
                type: 'multiple_choice',
                topic: 'sectors',
                prompt: 'Why do people spread money across sectors (tech, health care, energy, and so on)?',
                options: [
                    'Because one sector is legally required to rise each year',
                    'Because every sector always moves in the same direction',
                    'So one industry\'s bad year is less likely to sink the whole mix — sectors can still fall together',
                    'Because sector names guarantee profits',
                ],
                answer: 2,
                explanationCorrect: 'Correct! Different businesses have different drivers. Sector mix is a form of diversification. In a panic, many sectors can drop at once.',
                explanationIncorrect: 'Not quite. Sector diversification reduces "all my companies do the same thing" risk. It does not make the portfolio safe.',
            },
            {
                id: 'r3-q8',
                type: 'compare',
                topic: 'geography',
                prompt: 'Why might someone hold both U.S. and international stocks?',
                options: [
                    'So one country\'s market slump is not the only story — other regions can still fall too',
                    'Because international stocks cannot lose money',
                    'Because the U.S. market is closed to students',
                    'Because geography diversification removes all risk',
                ],
                answer: 0,
                explanationCorrect: 'Correct! Countries and currencies do not always move together. Global mix can help. A world-wide drop can still hurt everything.',
                explanationIncorrect: 'Not quite. Owning more than one region spreads country risk. It is not a guarantee. Global recessions can hit many markets at once.',
            },
            {
                id: 'r3-q9',
                type: 'multiple_choice',
                topic: 'volatility',
                prompt: 'What is volatility?',
                options: [
                    'A fee listed on every trade confirmation',
                    'A sign a stock is fake',
                    'How much prices bounce around — high volatility means bigger swings, up and down',
                    'A promise that a jumpy stock will pay you more each year',
                ],
                answer: 2,
                explanationCorrect: 'Correct! Volatility is the size of the ride. Big swings can mean big gains or big losses. Jumpy is not the same as profitable.',
                explanationIncorrect: 'Not quite. Volatility describes how wild the price path is. High volatility is more risk of large moves — not a bonus coupon.',
            },
            {
                id: 'r3-q10',
                type: 'multiple_choice',
                topic: 'cycles',
                prompt: 'What are market or economic cycles, in simple words?',
                options: [
                    'A calendar that tells you the exact best day to buy',
                    'Repeating-ish stretches of growth and slowdown — they are uneven and hard to time',
                    'A law that markets rise for 8 years then fall for 2',
                    'Proof that you should only invest in even-numbered years',
                ],
                answer: 1,
                explanationCorrect: 'Correct! Economies and markets go through better and worse stretches. The pattern is messy. Trying to jump in and out is easy to get wrong.',
                explanationIncorrect: 'Not quite. Cycles exist, but they are not a timer you can set. Length and depth change. Timing them is not a sure skill.',
            },
            {
                id: 'r3-q11',
                type: 'compare',
                topic: 'bull markets',
                prompt: 'During a bull market, which statement is most honest?',
                options: [
                    'Prices have generally been rising — that streak can end, and some stocks still fall along the way',
                    'Every stock is safe until an official bell rings',
                    'You cannot lose money if the headlines say "bull"',
                    'Bull markets last forever once they start',
                ],
                answer: 0,
                explanationCorrect: 'Correct! Bull markets are periods of generally rising prices. They end. Individual names can still be disasters in a bull tape.',
                explanationIncorrect: 'Not quite. "Bull" describes a rising stretch, not a safety certificate. Gains can reverse. Risk does not take a holiday.',
            },
            {
                id: 'r3-q12',
                type: 'scenario',
                topic: 'bear markets',
                prompt: 'A bear market is often described as a drop of about 20% or more from a peak. What is a healthy student response?',
                options: [
                    'Assume the market will be closed until prices recover',
                    'Assume stocks always bounce in 30 days',
                    'Treat it as a painful, normal kind of risk — check your plan, your cash needs, and your mix',
                    'Sell everything the first down day so you never feel it',
                ],
                answer: 2,
                explanationCorrect: 'Correct! Bear markets happen. They can last a while. The useful work is knowing whether you can hold, not pretending drops are impossible.',
                explanationIncorrect: 'Not quite. A bear market is a large, lasting kind of decline. There is no set recovery date. Panic selling or blind hope are both risky habits.',
            },
            {
                id: 'r3-q13',
                type: 'multiple_choice',
                topic: 'corrections',
                prompt: 'What is a market correction, as people often use the word?',
                options: [
                    'A drop of about 10% from a recent high — uncomfortable, and it can get worse',
                    'The exchange fixing a wrong stock price by hand',
                    'A guaranteed buying opportunity that cannot fall further',
                    'A year when inflation is exactly 2%',
                ],
                answer: 0,
                explanationCorrect: 'Correct! "Correction" usually means a roughly 10% pullback. The name does not mean the slide is over. It can become a bear market.',
                explanationIncorrect: 'Not quite. A correction is a notable drop, often around 10%. It is not a coupon that says "safe to buy" or "cannot fall more."',
            },
            {
                id: 'r3-q14',
                type: 'multiple_choice',
                topic: 'economy',
                prompt: 'Why do investors watch the economy (jobs, spending, GDP)?',
                options: [
                    'Because a strong economy makes every stock go up on a schedule',
                    'Because company results live in the real world — but stocks can still move opposite to the latest headline',
                    'Because the economy and the stock market are always the same thing',
                    'Because GDP is the legal maximum P/E',
                ],
                answer: 1,
                explanationCorrect: 'Correct! Businesses sell more or less as the economy changes. Markets try to look ahead and can disagree with today\'s data.',
                explanationIncorrect: 'Not quite. The economy matters for sales and jobs. The stock market is a separate vote on the future. They do not move in lockstep.',
            },
            {
                id: 'r3-q15',
                type: 'scenario',
                topic: 'interest rates',
                prompt: 'Interest rates jump higher. What is a common (not guaranteed) effect on stocks?',
                options: [
                    'Borrowing gets more expensive and future profits can look less attractive, so stocks may come under pressure',
                    'Every stock is required to rise',
                    'Bond prices are frozen and stocks become risk-free',
                    'Rates only affect companies that sell ice cream',
                ],
                answer: 0,
                explanationCorrect: 'Correct! Higher rates can weigh on stocks and on companies that need cheap loans. The link is real and still not a one-day rule.',
                explanationIncorrect: 'Not quite. Rising rates often make borrowing cost more and can lower what people will pay for future earnings. Effects vary by company and by day.',
            },
            {
                id: 'r3-q16',
                type: 'multiple_choice',
                topic: 'inflation',
                prompt: 'What is a "real" return?',
                options: [
                    'Any return above 0%',
                    'The return after you subtract inflation — you can have a positive number on paper and still lose buying power',
                    'The return only from dividends',
                    'A return the government promises on all stocks',
                ],
                answer: 1,
                explanationCorrect: 'Correct! Real return ≈ investment return minus inflation. If you earn 3% and prices rise 4%, your buying power shrank.',
                explanationIncorrect: 'Not quite. Real return looks through inflation. A 5% gain in a 6% inflation year is a loss of purchasing power.',
            },
            {
                id: 'r3-q17',
                type: 'scenario',
                topic: 'earnings reports',
                prompt: 'A company reports earnings after the bell. The next morning the stock gaps down. What might that mean?',
                options: [
                    'The report was better than every investor hoped, always',
                    'The exchange made a typing error that will be reversed',
                    'Investors may have disliked the results or the outlook — gaps can go either way, and one report is not the whole story',
                    'Earnings reports cannot move prices',
                ],
                answer: 2,
                explanationCorrect: 'Correct! Quarterly reports can move prices fast. A drop often means the news missed hopes or raised worries. It can also be an overreaction.',
                explanationIncorrect: 'Not quite. Earnings days are volatile. Prices move on how results compare with expectations, not just on "the company made a profit."',
            },
            {
                id: 'r3-q18',
                type: 'calculation',
                topic: 'revenue growth',
                prompt: 'Sales were $100 million last year and $110 million this year. What is revenue growth?',
                options: [
                    '$110 million, because that is this year\'s sales',
                    '10% — sales grew $10 million on a $100 million base',
                    '110%',
                    '0%, because growth only counts if profit rose too',
                ],
                answer: 1,
                explanationCorrect: 'Correct! Growth rate = change ÷ starting amount. $10m / $100m = 10%. Growing sales can still come with falling profits.',
                explanationIncorrect: 'Not quite. $110m vs $100m is a $10m increase, or 10%. Revenue growth is not the same as profit growth or a rising stock.',
            },
            {
                id: 'r3-q19',
                type: 'multiple_choice',
                topic: 'cash flow',
                prompt: 'What is cash flow, in simple words?',
                options: [
                    'The stock\'s daily volume',
                    'A company\'s P/E ratio',
                    'Cash moving in and out of the business — a company can show profit and still run short of cash',
                    'The interest rate on a savings account',
                ],
                answer: 2,
                explanationCorrect: 'Correct! Cash flow tracks actual cash. Profit is an accounting idea. Both matter. Weak cash flow is a real risk.',
                explanationIncorrect: 'Not quite. Cash flow is money in vs money out. It can disagree with reported profit. Businesses need cash to stay healthy.',
            },
            {
                id: 'r3-q20',
                type: 'compare',
                topic: 'comparison',
                prompt: 'You compare two similar companies. Which approach is most useful?',
                options: [
                    'Pick the one with the catchier ad',
                    'Assume the higher stock price is the better business',
                    'Look only at last week\'s percent change',
                    'Compare growth, profits, cash, debt, and valuation side by side — then remember the cheaper-looking one can still be worse',
                ],
                answer: 3,
                explanationCorrect: 'Correct! Side-by-side work beats a single number or a vibe. Comparison improves your questions. It does not crown a sure winner.',
                explanationIncorrect: 'Not quite. Comparing businesses means looking at several facts together. Price alone, ads, and short-term charts are weak shortcuts.',
            },
            {
                id: 'r3-q21',
                type: 'chart',
                topic: 'asset allocation',
                prompt: 'These bars are one student\'s mix: 70% stocks, 20% bonds, 10% cash. What is a fair reading?',
                options: [
                    'This mix cannot lose money because it has cash',
                    'The mix is stock-heavy, so it will likely swing more than a 40% stock mix — still not a forecast',
                    'Bonds at 20% make the portfolio risk-free',
                    'You should copy this mix no matter your age or goals',
                ],
                answer: 1,
                explanationCorrect: 'Correct! The bars show a stock-heavy allocation. That usually means more volatility. The "right" mix depends on the person, and any mix can fall.',
                explanationIncorrect: 'Not quite. 70/20/10 is just a picture of weights. More stocks usually means a bumpier ride. Cash and bonds do not make losses impossible.',
                chart: {
                    kind: 'bars',
                    title: 'Sample allocation (%)',
                    labels: ['Stocks', 'Bonds', 'Cash'],
                    values: [70, 20, 10],
                },
            },
            {
                id: 'r3-q22',
                type: 'chart',
                topic: 'volatility',
                prompt: 'This line is a jumpy stock: $50, $62, $48, $55. What does the path show?',
                options: [
                    'A smooth, low-volatility ride',
                    'That the stock is guaranteed to finish the year above $50',
                    'High volatility — large percent swings in a short time, with no promised next step',
                    'That corrections are illegal on this chart',
                ],
                answer: 2,
                explanationCorrect: 'Correct! The price leaped and dropped. That is volatility. Wild paths can continue in either direction.',
                explanationIncorrect: 'Not quite. Moves from 50 to 62 to 48 are large. That is a volatile history, not a safety rating or a forecast.',
                chart: {
                    kind: 'line',
                    title: 'Jumpy sample prices',
                    labels: ['W1', 'W2', 'W3', 'W4'],
                    values: [50, 62, 48, 55],
                },
            },
            {
                id: 'r3-q23',
                type: 'calculation',
                topic: 'dollar-cost averaging',
                prompt: 'You invest $30 each month. Month 1 the share is $10 (3 shares). Month 2 it is $6 (5 shares). What did DCA do here?',
                options: [
                    'It bought more shares when the price was lower — your average cost is below $10, and the position can still lose money',
                    'It locked in a profit of $30',
                    'It proved the price will return to $10',
                    'It bought fewer shares at the lower price',
                ],
                answer: 0,
                explanationCorrect: 'Correct! Same dollars bought 3 shares, then 5. Average cost = $60 / 8 = $7.50. If the price stays at $6, you are still down.',
                explanationIncorrect: 'Not quite. DCA bought more shares at $6 than at $10. That can help the average price. It does not create a guaranteed gain.',
            },
            {
                id: 'r3-q24',
                type: 'scenario',
                topic: 'rebalancing',
                prompt: 'A friend says, "Never rebalance — just let winners run forever." What is the risk?',
                options: [
                    'There is no risk; winners never reverse',
                    'Rebalancing is illegal after a gain',
                    'One winning asset can take over the portfolio, quietly raising the chance of a sharp loss later',
                    'Your weights will always stay exactly on target without you',
                ],
                answer: 2,
                explanationCorrect: 'Correct! Unchecked winners become concentration. That can feel great until the winner slumps. Rebalancing is about staying near your risk plan.',
                explanationIncorrect: 'Not quite. Prices change weights for you. If you never reset, you may own a much riskier mix than you signed up for.',
            },
            {
                id: 'r3-q25',
                type: 'multiple_choice',
                topic: 'bear markets',
                prompt: 'Which sentence should you take into Rank 4?',
                options: [
                    'If you diversify and use DCA, stocks always go up',
                    'Allocation, time horizon, and behavior in drops matter as much as picking names — and bear markets are part of the deal',
                    'Corrections mean the market is broken',
                    'Interest rates never affect investments',
                ],
                answer: 1,
                explanationCorrect: 'Correct! Building a portfolio is about mix, time, and staying with a plan you can survive. Markets fall. That is not a glitch.',
                explanationIncorrect: 'Not quite. Tools like allocation and DCA help you implement a plan. They do not abolish bear markets or make stocks a one-way bet.',
            },
        ],
    },
    {
        fromRank: 4,
        toRank: 5,
        title: 'Market Analyst → Investing Pro',
        questions: [
            {
                id: 'r4-q1',
                type: 'compare',
                topic: 'fundamental analysis',
                prompt: 'What is fundamental analysis mainly about?',
                options: [
                    'Only drawing lines on a 5-minute chart',
                    'Studying the business — sales, profits, debt, and value — to judge what a company might be worth',
                    'Copying the last headline you saw',
                    'Proving the next tick of the stock price',
                ],
                answer: 1,
                explanationCorrect: 'Correct! Fundamentals ask: is this a solid business at a sensible price? Even a great business can be a poor stock if you overpay — or if the story breaks.',
                explanationIncorrect: 'Not quite. Fundamental analysis looks at the company and its value. It is not a short-term price crystal ball.',
            },
            {
                id: 'r4-q2',
                type: 'compare',
                topic: 'technical analysis',
                prompt: 'What is technical analysis mainly about?',
                options: [
                    'Reading price and volume history for patterns and trends — clues, not proof',
                    'Auditing the CEO\'s calendar',
                    'Calculating taxes owed on a dividend',
                    'A method that cannot be wrong if you use enough indicators',
                ],
                answer: 0,
                explanationCorrect: 'Correct! Technicians study the tape: price, volume, trends. Patterns can fail. Charts describe the past first.',
                explanationIncorrect: 'Not quite. Technical analysis uses market data (price and volume). It does not replace business facts, and it does not guarantee the next move.',
            },
            {
                id: 'r4-q3',
                type: 'multiple_choice',
                topic: 'support',
                prompt: 'What do traders mean by support and resistance?',
                options: [
                    'Legal prices set by the exchange',
                    'Zones where a price has often stopped falling (support) or stopped rising (resistance) — they can break',
                    'The bid and ask on every stock, renamed',
                    'Levels that a stock is forbidden to cross',
                ],
                answer: 1,
                explanationCorrect: 'Correct! Support and resistance are habit zones on a chart. When they break, the story changes. They are not walls.',
                explanationIncorrect: 'Not quite. Support is an area buyers have shown up before. Resistance is an area sellers have shown up. Either side can fail.',
            },
            {
                id: 'r4-q4',
                type: 'multiple_choice',
                topic: 'trend lines',
                prompt: 'What is a trend line trying to show?',
                options: [
                    'The exact price in 30 days',
                    'The company\'s true value',
                    'The recent direction of price (up, down, or sideways) — trends reverse',
                    'A government growth target',
                ],
                answer: 2,
                explanationCorrect: 'Correct! Trend lines sketch direction. An uptrend of higher highs can fail. Drawing a line does not make the trend continue.',
                explanationIncorrect: 'Not quite. A trend line is a visual of recent direction. It is a tool, not a contract with the future.',
            },
            {
                id: 'r4-q5',
                type: 'multiple_choice',
                topic: 'moving averages',
                prompt: 'What is a moving average (MA)?',
                options: [
                    'The average price over a recent window, used to smooth noise — price can stay far from it',
                    'The only fair price of the stock',
                    'A dividend the company must pay',
                    'A line that stocks always bounce off',
                ],
                answer: 0,
                explanationCorrect: 'Correct! An MA averages recent closes so the path looks smoother. Traders watch it as a trend hint. It lags, and it can be sliced through.',
                explanationIncorrect: 'Not quite. A moving average is a trailing average of price. It is not a floor, a ceiling, or "true value."',
            },
            {
                id: 'r4-q6',
                type: 'multiple_choice',
                topic: 'volume',
                prompt: 'What is volume on a stock chart?',
                options: [
                    'How loud the trading floor is',
                    'The company\'s revenue that quarter',
                    'How many shares traded — heavy volume can add weight to a move, but it does not guarantee the next day',
                    'The number of employees',
                ],
                answer: 2,
                explanationCorrect: 'Correct! Volume is activity. A rise on high volume can mean stronger conviction — or a blow-off. Volume is context, not a promise.',
                explanationIncorrect: 'Not quite. Volume counts shares that changed hands. It helps you judge how "busy" a move was. Busy is not the same as correct.',
            },
            {
                id: 'r4-q7',
                type: 'multiple_choice',
                topic: 'candlesticks',
                prompt: 'On a basic candlestick, what do the open and close tell you?',
                options: [
                    'The company\'s debt and cash',
                    'Where the price started and finished that period — the wick shows the high and low',
                    'Next week\'s guaranteed range',
                    'Whether you should buy, with no other facts',
                ],
                answer: 1,
                explanationCorrect: 'Correct! A candle is a compact price story: open, high, low, close. One candle is not a full research report.',
                explanationIncorrect: 'Not quite. Candles map a period\'s price path. They do not publish fundamentals or lock in the next candle.',
            },
            {
                id: 'r4-q8',
                type: 'multiple_choice',
                topic: 'valuation',
                prompt: 'What does valuation ask?',
                options: [
                    'Only "did the price go up this week?"',
                    'Only "is the logo famous?"',
                    'What you are paying compared with what you might be getting — a great company can be a risky price',
                    'Which candle color is luckiest',
                ],
                answer: 2,
                explanationCorrect: 'Correct! Valuation is about price vs worth (using earnings, sales, cash, and more). Paying too much is a real way to lose money.',
                explanationIncorrect: 'Not quite. Valuation compares the market price with measures of the business. Popular names can be expensive. Cheap names can be cheap for a reason.',
            },
            {
                id: 'r4-q9',
                type: 'multiple_choice',
                topic: 'PEG',
                prompt: 'What is the PEG idea (P/E compared with growth)?',
                options: [
                    'A high P/E is always too expensive, no matter how fast earnings grow',
                    'Growth never matters for price',
                    'You compare the P/E with the growth rate to ask if you are paying a lot for that growth — it is still a rough tool',
                    'PEG is a government safety score from 1 to 100',
                ],
                answer: 2,
                explanationCorrect: 'Correct! PEG puts P/E next to expected or recent growth. It can make a high P/E look less wild — or more wild. Forecasts can be wrong.',
                explanationIncorrect: 'Not quite. The PEG idea is "price-to-earnings versus growth." It is one more lens. Bad growth guesses make a tidy PEG misleading.',
            },
            {
                id: 'r4-q10',
                type: 'calculation',
                topic: 'price-to-sales',
                prompt: 'A company\'s market cap is $80. Last year\'s sales were $40. What is the price-to-sales (P/S) ratio?',
                options: [
                    '2 ($80 ÷ $40) — you are paying $2 of value for each $1 of sales; that is not a buy signal by itself',
                    '40, because that is sales',
                    '80, because that is market cap',
                    '0.5, because you divide sales by two',
                ],
                answer: 0,
                explanationCorrect: 'Correct! P/S = price (or market cap) ÷ sales = 80 / 40 = 2. Useful when earnings are messy. A low P/S can still be a weak business.',
                explanationIncorrect: 'Not quite. Price-to-sales is market value divided by sales: 80 / 40 = 2. It ignores costs and debt, so it is incomplete.',
            },
            {
                id: 'r4-q11',
                type: 'scenario',
                topic: 'debt',
                prompt: 'Two similar companies earn about the same. Company D has far more debt. Why might that matter?',
                options: [
                    'Debt always makes a company safer',
                    'Leverage can boost results in good times and hurt more when sales slip or rates rise',
                    'Debt is only a problem for governments, not companies',
                    'More debt legally raises the stock price',
                ],
                answer: 1,
                explanationCorrect: 'Correct! Borrowed money is leverage. It can help or harm. Heavy debt is a real risk if cash gets tight.',
                explanationIncorrect: 'Not quite. Debt is not free. Interest must be paid. A leveraged company can look fine until the cycle turns.',
            },
            {
                id: 'r4-q12',
                type: 'multiple_choice',
                topic: 'free cash flow',
                prompt: 'What is free cash flow (FCF), in simple words?',
                options: [
                    'Cash left after running and investing in the business — money that could be used more freely',
                    'The same thing as revenue',
                    'The stock price times volume',
                    'A dividend the company must pay',
                ],
                answer: 0,
                explanationCorrect: 'Correct! FCF is leftover cash after the company maintains and invests in itself. Negative FCF can be a warning — or a growth-spending phase. Context matters.',
                explanationIncorrect: 'Not quite. Free cash flow is cash after operating needs and many investments. It is not sales, and it is not a promised payout.',
            },
            {
                id: 'r4-q13',
                type: 'multiple_choice',
                topic: 'competitive advantage',
                prompt: 'What is a competitive advantage?',
                options: [
                    'A one-day pop in the stock',
                    'A legal monopoly given to every listed company',
                    'Something that helps a company win and keep customers better than rivals — advantages can fade',
                    'A guarantee of 20% yearly returns',
                ],
                answer: 2,
                explanationCorrect: 'Correct! An edge (brand, cost, network, and so on) can support better long-term results. Rivals and change can erase it.',
                explanationIncorrect: 'Not quite. Competitive advantage is a business edge, not a stock-price promise. Edges must be re-earned.',
            },
            {
                id: 'r4-q14',
                type: 'scenario',
                topic: 'management',
                prompt: 'Why do investors care who runs the company?',
                options: [
                    'Leaders set strategy, culture, and how they treat owners — poor management can wreck a good product',
                    'The CEO\'s face on TV makes the stock risk-free',
                    'Management never matters if the logo is famous',
                    'Only the stock ticker decides results',
                ],
                answer: 0,
                explanationCorrect: 'Correct! People at the top allocate capital and set the tone. You cannot measure every leader perfectly, but ignoring them is a mistake.',
                explanationIncorrect: 'Not quite. Management skill and honesty matter. A flashy CEO is not a guarantee, and a quiet team can still do excellent or terrible work.',
            },
            {
                id: 'r4-q15',
                type: 'multiple_choice',
                topic: 'moats',
                prompt: 'What is an economic moat?',
                options: [
                    'A water feature next to headquarters',
                    'A durable advantage that keeps rivals from easily stealing the business — moats can shrink',
                    'A rule that the stock cannot fall more than 5%',
                    'A type of municipal bond',
                ],
                answer: 1,
                explanationCorrect: 'Correct! A moat is a lasting edge (brand, switching costs, network, cost, and so on). Time, tech, and rivals can fill it in.',
                explanationIncorrect: 'Not quite. "Moat" is a picture for a hard-to-copy advantage. It is a business idea, not a price floor.',
            },
            {
                id: 'r4-q16',
                type: 'scenario',
                topic: 'news',
                prompt: 'A shocking headline hits and the stock jumps 8% in an hour. What should a careful student remember?',
                options: [
                    'The first headline is always complete and correct',
                    'News can move prices fast — the first move can be wrong, incomplete, or already "in" the price',
                    'You must buy immediately or miss out forever',
                    'After news, charts stop mattering and risk disappears',
                ],
                answer: 1,
                explanationCorrect: 'Correct! News is a spark. Prices can overshoot. Waiting for facts beats reacting to every alert. Speed is not the same as wisdom.',
                explanationIncorrect: 'Not quite. Headlines move markets. They can also be thin, late, or misleading. "Act now" pressure is a reason to slow down, not speed up.',
            },
            {
                id: 'r4-q17',
                type: 'scenario',
                topic: 'earnings surprises',
                prompt: 'A company "beats" earnings estimates but the stock falls. How can that happen?',
                options: [
                    'It cannot happen; a beat always lifts the price',
                    'The exchange cancels beats after hours',
                    'Investors may have wanted an even bigger beat, or they disliked guidance, margins, or cash flow',
                    'Beats automatically convert the stock into a bond',
                ],
                answer: 2,
                explanationCorrect: 'Correct! The surprise is versus hopes, not versus zero. A "beat" with a weak outlook can still be sold. One print is not the full thesis.',
                explanationIncorrect: 'Not quite. Markets trade expectations. Beating a low bar — or beating while guiding down — can still disappoint. Prices can drop on "good" news.',
            },
            {
                id: 'r4-q18',
                type: 'multiple_choice',
                topic: 'behavior',
                prompt: 'What is behavioral finance mainly about?',
                options: [
                    'How feelings and mental shortcuts can push people into buying high, selling low, or ignoring facts',
                    'A formula that removes emotion from every investor',
                    'The study of only rational robots',
                    'A proof that gut feeling always beats research',
                ],
                answer: 0,
                explanationCorrect: 'Correct! Real people get scared, greedy, and stubborn. Knowing that helps you build rules. It does not make you immune.',
                explanationIncorrect: 'Not quite. Behavioral finance studies human habits in money decisions. Emotions are normal. Unchecked, they are expensive.',
            },
            {
                id: 'r4-q19',
                type: 'compare',
                topic: 'biases',
                prompt: 'FOMO vs confirmation bias — which pairing is right?',
                options: [
                    'FOMO is only about food; confirmation bias is only about colors',
                    'They are the same bias with two names',
                    'FOMO is fear of missing a rise; confirmation bias is hunting only for news that agrees with you — both can hurt',
                    'Neither bias can affect someone who owns an index fund',
                ],
                answer: 2,
                explanationCorrect: 'Correct! FOMO rushes you in. Confirmation bias keeps you from seeing disconfirming facts. Name the habit so you can pause.',
                explanationIncorrect: 'Not quite. FOMO is chasing so you will not "miss it." Confirmation bias is filtering for agreeable facts. Index-fund owners can still panic or brag-bias.',
            },
            {
                id: 'r4-q20',
                type: 'scenario',
                topic: 'thesis',
                prompt: 'What is an investment thesis?',
                options: [
                    'A one-line ticker and a hope it goes up',
                    'A written "why I own this," including what would prove you wrong — so you can update when facts change',
                    'A secret that must never be revisited',
                    'A promise the position cannot lose money if you write it down',
                ],
                answer: 1,
                explanationCorrect: 'Correct! A thesis is your reasoned case plus kill-switches. Writing it down fights foggy thinking. Being wrong is allowed; ignoring new facts is costly.',
                explanationIncorrect: 'Not quite. A thesis is more than a ticker. It says why, what has to stay true, and when you would change your mind. It is not a lucky charm.',
            },
            {
                id: 'r4-q21',
                type: 'chart',
                topic: 'support',
                prompt: 'Price keeps bouncing near $20, then later trades at $16. What is a fair reading of this chart idea?',
                options: [
                    'The $20 zone acted like support until it broke — broken support can become a problem, not a promise of a bounce',
                    '$20 is now a legal floor again',
                    'Once support breaks, the stock must go to zero',
                    'Charts cannot show support or resistance',
                ],
                answer: 0,
                explanationCorrect: 'Correct! Holding near 20 looked like support. Falling through it shows levels fail. The next path is unknown.',
                explanationIncorrect: 'Not quite. The line hovered near 20, then dropped to 16. That is a support break in this example — not a forecast of the final low.',
                chart: {
                    kind: 'line',
                    title: 'Sample support break',
                    labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
                    values: [21, 20, 20.5, 20, 16],
                },
            },
            {
                id: 'r4-q22',
                type: 'chart',
                topic: 'volume',
                prompt: 'Price rose from $10 to $14 while volume bars also rose. What can you say?',
                options: [
                    'The rise is guaranteed to continue',
                    'Low volume means the move is fake by law',
                    'Higher volume on the rise can mean more participation — still not proof the next day is up',
                    'Volume bars replace the need for valuation',
                ],
                answer: 2,
                explanationCorrect: 'Correct! Rising price with rising volume is often read as a stronger advance. Strong advances reverse. Volume is a clue.',
                explanationIncorrect: 'Not quite. The picture pairs an up-move with busier trading. That is interesting context. It is not a warranty.',
                chart: {
                    kind: 'bars',
                    title: 'Sample daily volume (millions)',
                    labels: ['Day 1', 'Day 2', 'Day 3', 'Day 4'],
                    values: [2, 3, 5, 8],
                },
            },
            {
                id: 'r4-q23',
                type: 'calculation',
                topic: 'free cash flow',
                prompt: 'Operating cash flow is $12 million. Needed reinvestment ("capex") is $4 million. What is a simple FCF figure?',
                options: [
                    '$16 million (you add them)',
                    '$4 million, because that is capex',
                    '$12 million, because FCF ignores capex',
                    '$8 million ($12m − $4m) — leftover cash, not a promised dividend',
                ],
                answer: 3,
                explanationCorrect: 'Correct! A classroom FCF is often cash from operations minus capex: 12 − 4 = 8. Definitions vary a bit. The leftover can still be wasted or needed later.',
                explanationIncorrect: 'Not quite. Simple FCF ≈ operating cash flow minus capex. $12m − $4m = $8m. That cash is not automatically sent to you.',
            },
            {
                id: 'r4-q24',
                type: 'scenario',
                topic: 'biases',
                prompt: 'You bought a stock. It is down 30%. You only click articles that say "it will recover." Which bias is showing?',
                options: [
                    'There is no bias; researching only bullish posts is extra careful',
                    'Confirmation bias — you are protecting the story instead of testing it',
                    'FOMO, because you have not bought more yet',
                    'A moat, because you refuse to sell',
                ],
                answer: 1,
                explanationCorrect: 'Correct! Hunting only for agreeing news is confirmation bias. A thesis should include what would change your mind — especially after a big loss.',
                explanationIncorrect: 'Not quite. Filtering for "it will come back" is a classic trap. Losses can be temporary or permanent. You need disconfirming facts too.',
            },
            {
                id: 'r4-q25',
                type: 'multiple_choice',
                topic: 'thesis',
                prompt: 'Which statement is the most honest close to Rank 4?',
                options: [
                    'If you master charts and ratios, stocks always go up',
                    'Fundamentals, charts, news, and behavior are tools for a thesis — none of them cancel risk or replace a plan you can live with',
                    'A strong moat means you never have to look again',
                    'Earnings surprises only move prices up',
                ],
                answer: 1,
                explanationCorrect: 'Correct! Analysis helps you choose and update. Markets can still punish good work. Stay humble, write the why, and respect risk.',
                explanationIncorrect: 'Not quite. Tools from this rank make you a sharper student. They do not make prices one-way or make a thesis immortal.',
            },
        ],
    },
];

export function getRankUpTest(fromRank: AcademyRankId): RankUpTest | null {
    if (fromRank === 5) return null;
    return RANK_UP_TESTS.find(t => t.fromRank === fromRank) ?? null;
}
