import { pack } from './harden-lib.mjs';

const L = {};
function add(id, rows) {
    L[id] = rows.map((row, i) => pack(id, i, ...row));
}

add(21, [
    ['A small slice of ownership in a company, not a loan you are owed',
     'A loan to a company that typically pays you a stated interest rate',
     'A coupon for that company’s products, equal to what you paid',
     'Cash sitting in a savings account with the company’s name on it'],
    ['A loan to a company or government that typically pays interest',
     'A slice of ownership that lets you vote on every product launch',
     'A share of leftover profit that must be paid out as a dividend',
     'A savings deposit that cannot change price after you buy it'],
    ['Bonds are loans that can still lose value; stocks are ownership that can too',
     'Bonds cannot lose value; only stocks are allowed to print a decline',
     'Stocks are loans; bonds are ownership, so only stocks pay interest',
     'Neither can lose value if you hold until the next calendar year'],
    ['Jordan might get less than paid, because newer bonds may offer higher interest',
     'Rising rates force older bonds to pay Jordan a bonus equal to the increase',
     'Selling early is not allowed, so the rate change cannot affect Jordan',
     'A 10-year bond’s price is frozen for the first two years by rule'],
    ['Bondholders, because they are lenders with a higher claim than owners',
     'Stockholders, because owners are always paid before any lender',
     'Whoever bought most recently, regardless of stock or bond',
     'Customers, because unpaid orders rank above every investor claim'],
    ['They often take different risks, so a mix can change how bumpy the ride feels',
     'Holding both deletes all risk, which is why people pair them',
     'Bonds cancel stocks tick for tick, so the mix cannot fall in a year',
     'You are required to pick only one; mixing them is against fund rules'],
    ['$40', '$4', '$400', '$14'],
    ['Interest rates rise, so older bonds that pay less look less attractive',
     'Interest rates rise, so older bonds automatically raise their coupon',
     'Bond prices can only fall if the issuer misses an interest payment',
     'Inflation falling is the only event that can cut a bond’s market price'],
    ['Alex, because stock is ownership of the business',
     'Casey, because a lender is the legal owner until interest is paid',
     'Both, because any claim on a company counts as owning the business',
     'Neither, because only the CEO owns a company that has sold bonds'],
    ['Bonds can lose market value, and inflation can shrink what the payments buy',
     'Bonds cannot lose if the word safe is used in the brochure',
     'Inflation raises what each interest dollar buys, which is why bonds are safe',
     'A friend calling bonds safe converts the holding into insured cash'],
]);

add(22, [
    ['Exchange-traded fund', 'Electronic transfer fee', 'Equity trading floor', 'Estimated tax forecast'],
    ['An ETF share is usually a slice of many holdings, not one business',
     'An ETF share is always one company’s stock with a fancier ticker',
     'Buying an ETF means you lend to every company in equal dollar amounts',
     'ETF shares cannot fall because a basket averages risk down to zero'],
    ['During market hours, with a price that can change through the session',
     'Only once a year, when the fund mails a single official price',
     'Only after midnight, when exchanges match leftover student orders',
     'Anytime, including weekends, at yesterday’s exact closing print'],
    ['Her ETF can fall because the basket’s holdings can lose value too',
     'The ETF is required to hold last year’s price if members have a bad year',
     'A basket cannot fall unless every member falls by the exact same percent',
     'Stock ETFs are insured against member losses during a calendar year'],
    ['A yearly fee, as a percent of assets, that the fund charges',
     'A one-time tax paid only when you first click buy',
     'The bid-ask spread, renamed so it looks like an annual percent',
     'A bonus the fund pays you for holding through a down month'],
    ['$1', '$10', '$100', '$0.10'],
    ['The higher fee can leave you with less over time, all else equal',
     'The higher fee means better holdings, so you should expect more leftover',
     'Fees under 1% do not change results, so 0.75% and 0.05% are the same',
     'The cheaper fund is required to lag because it spends less on research'],
    ['Yes. The trading price can sit a bit above or below the basket’s value',
     'No. ETF prices are locked to the inside value at every second',
     'Yes, but only on up days; discounts below value are not allowed',
     'No. Any gap is refunded to you at the next close automatically'],
    ['What the basket actually holds, and what fees it charges each year',
     'Whether the ticker has three letters, which predicts next year’s return',
     'Whether a celebrity mentioned it, which replaces reading the holdings',
     'Whether last week was up, which locks in the fee and the mix'],
    ['The price moved up and down; those past prints do not promise the next months',
     'Four months of history is a contract that the next four will look the same',
     'If a line ends higher, the down months in the middle did not count',
     'ETF charts cannot fall; any dip is a labeling error on the axis'],
]);

add(23, [
    ['A pool of money invested together; you own shares of that pool',
     'A single stock that a manager renames so it looks like a basket',
     'A savings account that pays a fixed rate and never changes price',
     'A loan you make to other investors that they repay at the close'],
    ['ETFs usually trade during the day; most mutual funds price once daily',
     'Mutual funds trade all day; ETFs can only be bought at the yearly meeting',
     'There is no trading difference; both print a new price every second',
     'ETFs price once daily; mutual funds match orders continuously like stocks'],
    ['Net asset value: the per-share value of what the fund holds',
     'New account volume: how many people opened the fund that morning',
     'National average yield: a savings rate copied onto the fund',
     'Next assigned value: tomorrow’s promised price for every holder'],
    ['$950', '$1,000', '$50', '$1,050'],
    ['No. Many active funds lag after fees, and the fund can still lose money',
     'Yes. A person in charge is required to beat the market after costs',
     'Yes, unless the market is down, in which case active funds must still rise',
     'No only for ETFs; mutual funds with managers cannot print a loss'],
    ['An ETF that trades on an exchange during the session',
     'A typical mutual fund that sets one price after the close',
     'A savings account, because daytime trading needs a fixed rate',
     'A bond you hold to maturity, which you can flip at lunch and at 2 p.m.'],
    ['A yearly cost of running the fund, taken from the fund’s assets',
     'A refund you receive if the fund finishes below last year’s close',
     'The sales load, paid only once, that replaces any yearly cost',
     'A trading commission the exchange charges you on every click'],
    ['$20', '$2', '$200', '$0.20'],
    ['Both can be useful baskets; they differ in how you buy, sell, and sometimes in fees',
     'Mutual funds always win because they cannot be traded until tomorrow',
     'ETFs are only for experts; mutual funds cannot lose if you hold a year',
     'You should treat them as identical, including the way orders fill'],
    ['No. Markets can fall, and fees also reduce the balance a bit',
     'Yes. A lower balance is proof the manager took the missing cash',
     'Yes, unless the statement uses the word fund, which blocks theft claims',
     'No only if the drop is under 1%; larger drops must be stolen money'],
]);

add(24, [
    ['Match a chosen market index as closely as is practical, not beat it',
     'Beat every other fund in its category after fees, every calendar year',
     'Hold only cash and rename it as the index for reporting',
     'Pick the single best stock from the index and ignore the rest'],
    ['About a 20% drop, minus a bit for fees and imperfect tracking',
     'A 20% gain, because index funds move opposite the index in down years',
     'No change, because matching an index means the fund cannot fall',
     'A 20% drop plus a required extra 20% penalty for tracking'],
    ['They might track different lists: stocks vs bonds, U.S. vs world, wide vs narrow',
     'All index funds must hold the same list, so they should feel identical',
     'The label index means the mix is cash, no matter what the name says',
     'Differences only come from ticker length, not from what is inside'],
    ['Yes. Many ETFs are index funds, and some mutual funds are too',
     'No. Index funds can only be mutual funds priced once a day',
     'No. ETF is a separate idea that cannot track an index',
     'Yes, but only if the ETF promises it will never fall with the index'],
    ['$50', '$5', '$500', '$0.50'],
    ['Even small yearly fees can compound and reduce what you keep',
     'Fees under 1% are refunded, so talking about them is only a habit',
     'Costs matter only in the first week, then they stop affecting the pile',
     'Higher costs mean higher official returns, which is why the sites mention them'],
    ['False. Index funds can lose a lot when the market they track falls',
     'True. Matching an index includes a rule that down years are skipped',
     'True for stock indexes; only bond index funds are allowed to fall',
     'False only about fees; the market path itself cannot cut an index fund'],
    ['Active tries to beat a benchmark; index tries to match one; either can lose',
     'Active cannot lose because a person can veto down days',
     'Index cannot lose because matching is the same as insurance',
     'Active always beats index after fees, which is why people still use both'],
    ['A 1% fee takes far more than a 0.05% fee: $100 versus $5 on $10,000 here',
     'The two fees take the same dollars because both are under 2%',
     'The 0.05% fee takes more, because smaller percents apply more often',
     'Fee bars are illustrations only; yearly percents never become dollars'],
    ['Buy a fund that tracks a broad large-company U.S. index',
     'Buy one famous large company and treat it as the whole index',
     'Buy a narrow single-industry fund and rename it broad in your notes',
     'Buy a bond fund, because large U.S. companies are a type of loan'],
]);

add(25, [
    ['Company size, often measured by market cap, not how famous the logo is',
     'How many stores they have, which is the official size bucket',
     'The share price alone, so an $800 stock is always a large company',
     'Employee count only, which is why tiny firms cannot be large-cap'],
    ['Liner maps to a large company; speedboat maps to a small company',
     'Liner maps to a small company because big ships turn slowly',
     'Both sizes map to the liner; speedboats are only for cash accounts',
     'The mapping is reversed: speedboat is large-cap, liner is small-cap'],
    ['Yes. Large companies can still lose a great deal of market value',
     'No. Once a firm is huge and famous, its stock cannot fall a lot',
     'Yes, but only overnight; during the session large names are floored',
     'No, because weak sales are not allowed to hit companies above a size line'],
    ['They have often been more volatile, with less information or thinner trading',
     'Small companies are legally banned from falling as far as large ones',
     'Risk is lower because a small name can only lose a small number of dollars',
     'They are riskier only in name; their prices move less than giant firms'],
    ['You cannot tell from share price alone; you need price times shares',
     'The $80 stock is larger, because a higher price means a bigger company',
     'The $8 stock is larger, because cheaper shares mean more customers',
     'Share price is another name for market cap, so $80 beats $8'],
    ['Concentration risk: one small name can swing his whole practice account',
     'No size risk, because liking the company converts it into a large-cap',
     'Diversified size risk, because one small company still represents its whole bucket',
     'Interest-rate risk only; single-name size does not affect a student account'],
    ['A company in the middle size bucket, not the giants and not the smallest',
     'Any company whose share price is in the middle of the day’s range',
     'A company that is large in sales but small in the number of employees',
     'The label for cash sitting between stocks and bonds in a mix'],
    ['The $1 billion bar is the smallest company on this chart',
     'The tallest bar is the smallest, because size is plotted upside down',
     'All bars are the same size in real life; the chart is only decoration',
     'The smallest bar is a large-cap, by definition of a sample chart'],
    ['It may have helped in other times, but it cannot stop a broad slump',
     'If all size buckets fall together, size diversification is proven fake',
     'A same-month drop across sizes means you actually held only large-caps',
     'Size buckets cannot fall in the same month; one of the labels is wrong'],
    ['It holds mostly smaller companies and can be bumpier than a large-cap fund',
     'Small-cap means the fund cannot fall more than a large-cap fund',
     'The label means each holding has a small share price, not a small company',
     'Small-cap funds are required to hold the same giants as large-cap funds'],
]);

add(26, [
    ['A company investors expect to expand earnings quickly, often at a richer price',
     'A company that looks inexpensive versus earnings, sales, or assets today',
     'Any firm that grew last year, regardless of what people pay for it now',
     'A company that pays a high dividend because it has nothing left to build'],
    ['A company that looks inexpensive versus earnings, sales, or assets',
     'A company expected to expand earnings quickly at a much richer price',
     'Any stock that fell yesterday, which is the official value definition',
     'A firm that cannot grow, so the only story left is the ticker letters'],
    ['Growth often prices in a bright future; value often prices a lower multiple today',
     'Growth means cheap today; value means people are paying for a distant boom',
     'The two labels are required to describe the same stock at the same time',
     'Value stocks cannot have a future; growth stocks cannot look expensive'],
    ['A value trap: it looks cheap for a painful business reason',
     'A growth crown: shrinking sales are how value names officially qualify',
     'A split: cheap prices are later edited up when the business shrinks',
     'A floor: once a stock is cheap, it cannot get cheaper by rule'],
    ['The price can drop a lot if people paid for a future that did not arrive',
     'Growth favorites cannot fall after a miss, because the story is already priced',
     'A miss forces the exchange to raise the price so the future still fits',
     'Expansion targets are optional; missing them cannot change a rich price'],
    ['No. Leadership rotates, and both styles can have losing years',
     'Yes. Growth is required to beat value in every calendar year',
     'Yes for value; growth can lose, but cheap names cannot',
     'No only in theory; live markets keep the same winner each decade'],
    ['Luis, because a mix of styles is less tied to one bucket’s weather',
     'Dana, because a single growth ETF is already every style at once',
     'Both equally, because style labels do not change how a fund moves',
     'Neither, because ETFs cannot be described as growth or value'],
    ['Yes. Numbers and investor mood can move a company from one bucket to the other',
     'No. A company is assigned growth or value at IPO and cannot switch',
     'Yes, but only if the ticker letters change with the bucket',
     'No. Buckets are about the logo color, which does not change with numbers'],
    ['Stock V, because a P/E of 10 is lower than a P/E of 40',
     'Stock G, because a P/E of 40 means you get more earnings per dollar',
     'They look the same on P/E, because both trade at $80 a share',
     'Stock G, because higher P/E is the official meaning of cheaper'],
    ['Disagree. Cheap stocks can get cheaper, and the business can still worsen',
     'Agree. Already cheap is a floor that blocks further price declines',
     'Agree, because value is defined as stocks that cannot print a loss',
     'Disagree only about dividends; the price of a cheap name cannot fall'],
]);

add(27, [
    ['Share price times the number of shares outstanding',
     'Share price plus the number of employees',
     'Last year’s profit times the dividend yield',
     'Revenue divided by the number of stores'],
    ['$20,000,000', '$200,000', '$12,000,000', '$2,000,000'],
    ['B at $80 million is larger than A at $40 million',
     'A at $40 a share is larger, because the price looks higher',
     'They match, because 1 million and 10 million cancel the price gap',
     'A is larger at $40 million, because fewer shares mean a tighter company'],
    ['It stays about the same, because the price is cut as the share count rises',
     'It doubles, because extra shares are new value printed for owners',
     'It halves, because splits are how companies officially get smaller',
     'It jumps 2-for-1 in dollars, matching the split ratio exactly'],
    ['No. Cap moved because the price moved; a rumor can be wrong',
     'Yes. A 30% cap jump is the same thing as 30% more earnings that week',
     'Yes, because market cap is defined as last week’s audited profit',
     'No only if the rumor is about products; price rumors always match earnings'],
    ['The market’s current value of the company’s equity',
     'The cash in the company’s checking account this morning',
     'The sum of all prices the stock ever traded at, added together',
     'A government appraisal that cannot change until next year'],
    ['Gamma at 40', 'The shortest bar, by chart convention', 'Whichever name is listed first', 'They are equal, because sample charts cannot rank size'],
    ['Fewer shares and fewer traders can mean a wider spread and bumpier prices',
     'Tiny caps are easier to trade because so few people care about the price',
     'Smaller caps must have tighter spreads, which is how they stay small',
     'Trading difficulty is about the logo, not about how many shares change hands'],
    ['Its market value sits in the large-size bucket',
     'It has the most stores, which is the official cap test',
     'Its share price is high, which is all large-cap means',
     'It cannot fall more than 5% in a week, by the large-cap rule'],
    ['$90 million', '$110 million', '$10 million', '$100 million'],
]);

add(28, [
    ['Money from selling goods or services; another word is sales',
     'What is left after every cost, interest bill, and tax is paid',
     'Cash borrowed from a bank and deposited into the company',
     'The jump in the stock price on the day a product ships'],
    ['$3,000', '$215', '$15', '$3,200'],
    ['Possible: costs can grow even faster than sales',
     'Impossible: rising revenue is defined as rising leftover profit',
     'Possible only if the stock also rose, which would cancel the losses',
     'Impossible, because a food truck cannot record revenue and a loss'],
    ['Customers paid us $10 million for our product',
     'We borrowed $10 million from a lender this quarter',
     'Our leftover after costs was $10 million this quarter',
     'Our stock’s market cap rose by $10 million this quarter'],
    ['Revenue sits near the top of the income statement',
     'Revenue is the last line, which is why people call it top line',
     'Top line means the stock’s high price for the year',
     'Top line is the CEO’s salary, listed first on the statement'],
    ['Revenue rose from 50 to 80; that is sales growth, not the same as profit',
     'Profit must have risen from 50 to 80, because the chart says revenue',
     'A climb on a revenue chart proves leftover cash also climbed',
     'Year 3 is lower than Year 1; rising bars mean shrinking sales'],
    ['Not necessarily: some businesses are seasonal, so quiet months are normal',
     'Yes: a quiet January after a huge December always means the firm is dying',
     'Not necessarily, but seasonal firms are not allowed to report January sales',
     'Yes, because revenue cannot legally differ from one month to the next'],
    ['No. A loan must be paid back; revenue is earning from customers',
     'Yes. Borrowed cash counts as sales until it is repaid',
     'Yes, if the loan is large enough to look like a year of muffins',
     'No only for banks; other firms treat loans as customer revenue'],
    ['Revenue is what we collected from customers for muffins',
     'Revenue is the leftover after we paid rent, wages, and flour',
     'Revenue is the bank loan we used to buy a second oven',
     'Revenue is how much the stock rose on muffin-launch day'],
    ['Check that “made” means revenue, not profit or something else',
     'Treat “made $5 billion” as profit, because headlines prefer leftover',
     'Treat it as market cap, because billion is how size is always stated',
     'Ignore the wording; sales, profit, and cap are interchangeable here'],
]);

add(29, [
    ['What is left after costs are taken out of sales',
     'All money customers paid, before any costs are subtracted',
     'Cash borrowed this year, counted as leftover if it sits in the bank',
     'The stock’s gain for the year, which accountants call profit'],
    ['$25', '$215', '$95', '$120'],
    ['A loss of $20', 'A profit of $20', 'A profit of $260', 'Zero, because revenue still existed'],
    ['P can be profitable while R loses; sales size is not the leftover',
     'R must be more profitable, because $1 billion of sales beats $200 million',
     'A loss is impossible at $1 billion of sales, so one number is wrong',
     'P cannot show a profit with smaller sales than R in the same lesson'],
    ['Earnings, or net income, for leftover after costs',
     'Revenue, which is another official word for leftover profit',
     'Market cap, which tracks leftover cash in the checking account',
     'Volume, which is how many shares of profit traded that day'],
    ['No. Prices depend on many things, and next year’s leftover can change',
     'Yes. A profitable year requires the stock to rise the following year',
     'Yes, unless the company also had revenue, which would cancel the rule',
     'No only for small firms; profitable giants cannot print a down year'],
    ['Revenue is 80 and profit is 10, so most of the sales were eaten by costs',
     'Profit is 80 and revenue is 10, because leftover is plotted as the tall bar',
     'The two bars must match; a gap means the chart is labeled wrong',
     'A profit bar of 10 means costs were negative, which added extra sales'],
    ['Losses can be a plan or a warning; you still need a path, not just hope',
     'A planned loss means the stock cannot fall, because the plan was disclosed',
     'Start-ups that lose money are not allowed to keep building an app',
     'If the loss is on purpose, leftover cash is guaranteed to arrive next year'],
    ['Gross profit is sales minus product costs; net income is after more costs like interest and taxes',
     'Net income is sales minus product costs; gross profit is after taxes only',
     'The two phrases are identical leftover numbers with two lesson titles',
     'Gross profit includes taxes; net income is sales before any costs'],
    ['No. Paying down debt can be wise, but the share price can still fall',
     'Yes. Using profit to cut debt requires the stock to rise that week',
     'Yes, because debt paydown is the same event as a higher market cap',
     'No only if they also pay a dividend; debt paydown alone lifts the quote'],
]);

add(30, [
    ['Earnings per share', 'Equity paid separately', 'Estimated price spread', 'Exchange posting schedule'],
    ['$5', '$2', '$8', '$20'],
    ['−$3', '$3', '−$3,000,000', '$0'],
    ['B at $4 is higher than A at $2',
     'A at $2 is higher, because more shares mean a bigger company',
     'They match at $20 million, so EPS is the same leftover label',
     'A is higher because 10 million shares beat 5 million in the EPS formula'],
    ['EPS can fall because the same leftover is split across more shares',
     'EPS must rise, because issuing shares is how earnings officially grow',
     'Flat profit plus new shares cannot change EPS, by definition',
     'EPS ignores share count, so extra shares only affect the ticker'],
    ['No. EPS is leftover per share; a dividend is a separate choice',
     'Yes. A $10 EPS is a $10 cash check mailed to each owner',
     'Yes, unless the company is public, in which case EPS stays on paper',
     'No only for losses; a positive EPS is always paid out in cash'],
    ['EPS can rise from fewer shares even if total profit is unchanged',
     'Buybacks cannot change EPS unless total profit also rises',
     'Fewer shares lower EPS, because leftover is attached to each ticker letter',
     'If profit is unchanged, EPS is frozen no matter the share count'],
    ['How much leftover profit there is for each share',
     'How much cash will be mailed to you for sure this quarter',
     'How large the company is compared with every rival on earth',
     'How much the stock must rise next year to match that EPS'],
    ['It counts extra possible shares, so leftover is split more ways',
     'Diluted EPS is always higher, because extra shares add extra profit',
     'Basic and diluted EPS are required to match on every report',
     'Diluted means after dividends, which is why the number is lower'],
    ['Price, share-count context, industry, and whether those earnings will last',
     'Nothing: a $20 EPS always beats a $4 EPS as a company trophy',
     'Only the ticker, because a higher EPS is the official better-company test',
     'Only last week’s volume, which converts EPS into a quality rank'],
]);

add(31, [
    ['Price-to-earnings: price divided by EPS',
     'Profit-to-equity: leftover divided by the number of stores',
     'Price-to-employees: share price divided by headcount',
     'Payout-to-EPS: the dividend as a percent of last year’s high'],
    ['20', '4', '80', '16'],
    ['25', '2', '50', '48'],
    ['A at 10 is lower than B at 30',
     'B at 30 is lower, because a bigger P/E means a cheaper stock',
     'They match at $30, so P/E is the same for both names',
     'B is lower because $1 of earnings is less than $3, which is the P/E'],
    ['You may be paying a lot for each dollar of earnings, and that hope can be wrong',
     'A high P/E is a trophy that means the stock cannot fall from here',
     'Higher P/E always means higher quality, so richer is safer',
     'P/E only rises when earnings rise, so a high number is extra leftover'],
    ['P/E is not a helpful ranking when earnings are negative',
     'Negative EPS makes P/E extra useful as a bargain score',
     'Websites can still rank by P/E, which proves the ratio works in losses',
     'A loss is treated as a tiny EPS, so P/E becomes a huge safety badge'],
    ['No. Different industries often carry different typical P/Es, and both can lose money',
     'Yes. The lower P/E is always the better buy across every industry',
     'Yes, because groceries and software are required to use one P/E scale',
     'No only if the grocer lost money; otherwise 18 always beats 40'],
    ['It rises from 10 to 20', 'It falls from 10 to 5', 'It stays 10, because price did not move', 'It becomes 2, matching the new EPS'],
    ['A flashlight: one way to see if the price looks rich or cheap versus earnings',
     'A trophy: the highest P/E in a contest is the official winner',
     'A floor: once you compute P/E, the stock cannot print below that number',
     'A forecast: P/E is next year’s return, written as a multiple'],
    ['High P/E can mean a rich price; it is not a trophy, and stocks can still fall',
     'Highest P/E wins, because paying more per dollar of earnings is the lesson’s rule',
     'They only missed the ticker; P/E rank is otherwise a complete system',
     'High P/E means extra cash will be mailed, so the strategy cannot lose'],
]);

add(32, [
    ['What did we sell, and what was left over this period?',
     'What do we own and owe on this date, as a snapshot?',
     'How many shares traded today, and who bought them?',
     'What will next year’s stock price be, according to the auditors?'],
    ['What do we own and owe on this date?',
     'What did we sell and what was left over over the whole year?',
     'How much the stock rose since the IPO, minus dividends?',
     'Which products customers liked most in last week’s ads?'],
    ['Profit is an accounting leftover; cash is what actually moved in the account',
     'Profit and cash are the same number on every honest report',
     'Cash is leftover on paper; profit is the money that left the bank',
     'If a firm shows profit, the checking account must have risen by that amount'],
    ['The income statement: costs may be rising faster than sales',
     'The balance sheet only: a snapshot cannot show a period of rising sales',
     'It means the stock must fall, because profit down is a trading rule',
     'The cash-flow statement is the only place sales and leftover can diverge'],
    ['Equity: the owners’ leftover claim after subtracting what is owed',
     'Revenue: sales for the period, which is assets minus liabilities',
     'Volume: how many shares of equity traded on that date',
     'Market cap: always equal to assets minus liabilities by definition'],
    ['Possible. Investing cash can drop even when the income statement shows a leftover',
     'Impossible. A leftover on the income statement freezes the cash balance',
     'Possible only if the stock also fell, which would explain the cash drop',
     'Impossible, because factories are paid for with revenue, not cash'],
    ['Balance sheet is a snapshot; income statement is a movie of a period',
     'Income statement is a snapshot; balance sheet is the year’s movie',
     'Both are snapshots of the same close, just with different titles',
     'Both are movies of next year, which is why they cannot show a loss'],
    ['Costs, debt, and cash might tell a tougher story than the sales headline',
     'Record revenue is enough, because leftover and cash must follow sales',
     'If revenue is a record, debt is not allowed to appear on the balance sheet',
     'Headlines about sales replace the need to read costs or cash'],
    ['Growth might be partly borrowed, so you should look closer',
     'A bigger loan proves the leftover is extra safe, because lenders already checked',
     'Rising leftover plus a bigger loan means the stock cannot fall',
     'Borrowed growth is not possible if the income statement shows a leftover'],
    ['Income statement, balance sheet, and cash-flow statement',
     'Only the stock chart, which already includes sales and leftover',
     'The bid, the ask, and yesterday’s volume',
     'Revenue, the CEO’s salary, and the number of stores'],
]);

add(33, [
    ['Price', 'Volume only', 'The company’s age', 'Next year’s promised close'],
    ['The market price declined over that stretch of time',
     'The company sold fewer products, which is the only way a line can fall',
     'The chart is zoomed wrong; falling lines are not allowed on price charts',
     'Volume disappeared, so the line dropped as a labeling error'],
    ['The price wiggled and ended higher than it started, which is still not a promise',
     'Ending higher proves the next stretch must also end higher',
     'Wiggles in the middle are deleted when the last point is above the first',
     'A sample path that ends up cannot include any down days'],
    ['Zoom changes the story you see, so check the time range before you judge',
     'The one-week view is the official truth; longer charts are decoration',
     'If the five-year chart looks calm, the one-week drop did not happen',
     'Time range cannot change the story, because every zoom must match'],
    ['How many shares were traded in that period',
     'How much leftover profit the company earned in that period',
     'How many news articles mentioned the ticker that day',
     'How far the price is allowed to move before the exchange pauses it'],
    ['The chart shows what already happened; you can still lose from here',
     'A clear past path is a contract for the next month of prices',
     'If you can read the chart, the remaining risk has already printed',
     'Safer means the line cannot fall after you have studied it'],
    ['A pretty slope is not a business study, and it is not a guarantee',
     'A strong-looking line is the same thing as checking sales and leftover',
     'Slope strength is an official forecast that brokers must honor',
     'If the line looks strong, financials are optional for that name'],
    ['The price stayed in a range and did not trend far up or far down',
     'The company paused operations, which is the only meaning of sideways',
     'Sideways means the stock is about to jump, according to the axis',
     'A flat stretch deletes prior gains, resetting the chart to zero'],
    ['Chart shows past prices; financials show sales, leftover, owns/owes, and cash',
     'Chart shows leftover profit; financials show only yesterday’s close',
     'The two jobs are the same: both are pictures of next year’s price',
     'Financials replace the chart, so past prices do not need a picture'],
    ['No. Prices move for many reasons, including mood, news, and rumors',
     'Yes. An 8% down day is defined as a loss reported that morning',
     'Yes, unless volume is high, in which case the drop does not count',
     'No only for ETFs; a single stock’s 8% drop must be an earnings miss'],
]);

add(34, [
    ['Buys or sells now at the best available prices in the book',
     'Waits until your chosen price prints, even if that takes days',
     'Sets a ceiling you will not pay, and may never fill',
     'Converts the order into a fund purchase priced after the close'],
    ['When the fill is worse than the price you thought you would get',
     'When the company reports leftover that is below last year’s leftover',
     'When your limit price is better than the last trade',
     'When the exchange delays the open by a few minutes'],
    ['A much higher fill than the last trade, if few shares are for sale',
     'A guaranteed last-trade fill, because market orders cannot slide',
     'A lower fill than the last trade, which is how thin stocks reward buyers',
     'No fill at all, because tiny names reject market orders'],
    ['You give up price control for a better chance of an immediate fill',
     'You give up any chance of a fill in order to control the exact cent',
     'You keep both: immediate fill and a locked price equal to the quote you saw',
     'You trade away the fill and keep slippage as a refund at the close'],
    ['You got the price you saw; slippage can be about zero when the book is deep',
     'A same-price fill is impossible, so one of the numbers is a display error',
     'Getting $25.00 means slippage was $25, the full price of the share',
     'Market buys cannot fill at the last price; they must print at least a cent worse'],
    ['Sells now to whoever is bidding, at their available prices',
     'Sells only if the price rises to a target you typed in advance',
     'Sells at last month’s high, which the broker must still honor',
     'Holds the shares until the close, then prices them like a mutual fund'],
    ['Fewer traders can mean wilder fills when the regular session is closed',
     'Closed-session market orders are filled at yesterday’s exact close, by rule',
     'After hours, slippage is banned, so market orders become safer',
     'You should prefer market orders then, because the book is always deeper'],
    ['$3.00', '$0.15', '$10.15', '$30.00'],
    ['A huge, heavily traded ETF during regular hours, if you accept a few cents of uncertainty',
     'A tiny, rarely traded name at night, when you need an exact price',
     'Any stock when you must have a ceiling and can wait days for a fill',
     'A closed session, because that is when market orders have no slippage'],
    ['No. It only gets you in or out; the investment can still lose value',
     'Yes. Immediate fills include a rule that the position cannot fall later',
     'Yes, if you use a market order on an ETF instead of a stock',
     'No only for sells; market buys lock in a gain equal to the fill'],
]);

add(35, [
    ['An order that trades only at your price or better, and might not fill',
     'An order that fills now at whatever prices are in the book',
     'An order that is guaranteed to fill by the close at last sale',
     'An order that converts shares into a mutual-fund NAV after 4 p.m.'],
    ['Market is now with possible slippage; limit is your price or better with possible no fill',
     'Market waits for your price; limit always fills immediately at last sale',
     'Both always fill at the exact quote on your screen, with no trade-off',
     'Limit is now with slippage; market is your ceiling with possible no fill'],
    ['You usually wait, because $40 is worse than your $36 buy ceiling',
     'You fill immediately at $40, and the extra $4 is refunded',
     'The limit raises itself to $40 so you are filled within a minute',
     'You fill at $36 right away, because limits buy at the last trade'],
    ['You sell only if the market reaches $24 or better; you might still be holding',
     'The sell limit forces a fill at $20 now, then waits for $24 extra',
     'A sell limit at $24 is the same as a market sell at $20',
     'You are filled at $24 immediately, even if the last print is $20'],
    ['You could pay $9.90; you should not pay $10.50 on that buy limit',
     'Or better means you might pay $10.50 if that is what sellers want',
     'Or better means the order becomes a market order after one minute',
     'A $10 buy limit can fill at any price as long as you clicked today'],
    ['You might fill at $22, which is better, or timing rules might mean you miss; gaps are messy',
     'A gap through $25 still fills you at $25, because that was your limit',
     'Overnight gaps cancel all limits, so the order becomes a market buy at $22',
     'Your $25 buy limit cannot fill below $25, even if $22 prints'],
    ['A market sell, accepting possible slippage, when you must be out today',
     'A sell limit far above the last price, which may never print today',
     'A buy limit, because selling today is the same as bidding',
     'No order: waiting overnight is the tool that guarantees a same-day exit'],
    ['$150', '$15', '$1.50', '$165'],
    ['It blocked a lower sale, so you still own the stock now around $30',
     'It sold you at $50 anyway, because limits protect against missing a fill',
     'It turned into a market sell at $30 when $50 was not reached',
     'It refunded the slide from $48 to $30 as a cash credit'],
    ['No. You can still buy a loser or miss a sale; the company can still fail',
     'Yes. Choosing a limit price removes investment risk from the shares',
     'Yes, if the limit is below the last trade, which floors the stock',
     'No only for buy limits; sell limits make the remaining position safe'],
]);

add(36, [
    ['The highest price buyers are currently offering',
     'The lowest price sellers are currently offering',
     'The last trade, which is always what you will pay next',
     'The official close from yesterday, reused until someone trades'],
    ['The lowest price sellers are currently offering',
     'The highest price buyers are currently offering',
     'The midpoint of last year’s range, used as a floor',
     'A fee the exchange charges when you look at a quote'],
    ['$0.05', '$20.05', '$0.25', '$40.05'],
    ['The ask, which is what sellers want right now',
     'The bid, which is what buyers are offering right now',
     'The last trade, even if it sits below the current ask',
     'Yesterday’s close, because market buys ignore the live book'],
    ['T, because a $1.00 gap is much wider than a $0.01 gap',
     'L, because a one-cent ask means you pay more to cross',
     'They cost the same to cross, because both bids start at $50',
     'L is wider in practice, because $50.01 looks more expensive than $51'],
    ['The spread: a round trip can cost ask minus bid even if last sale did not crash',
     'A hidden crash: last sale is required to drop $0.20 when you round-trip',
     'A commission of $10.20, which is how spreads are billed on tiny names',
     'Nothing: buying at $10.20 and selling at $10.00 is a wash by definition'],
    ['Many people trade them, so bids and asks often sit close together',
     'ETFs are not allowed to have a spread, which is why they look tight',
     'Big ETFs hide a wide spread inside the NAV, so the quote looks tiny',
     'Tiny spreads mean the ETF cannot fall, which attracts more traders'],
    ['Alpha at 1 cent', 'The tallest bar, which is the cheapest by convention', 'Every name equally, because cents cannot rank a spread', 'The name listed last on the chart'],
    ['Buyers are offering $14.70; sellers want $15.40; $15.00 is only the last handshake',
     '$15.00 is what you will pay and receive right now, because it is last sale',
     'The bid is $15.40 and the ask is $14.70, matching last sale in the middle',
     'A last trade of $15.00 forces the next fill to be $15.00 as well'],
    ['No. A tight spread only means cheaper trading; the investment can still lose value',
     'Yes. Tiny spreads are a promise the holding cannot print a down week',
     'Yes for ETFs; tight quotes convert the fund into a savings balance',
     'No only overnight; during the session a tight spread floors the price'],
]);

add(37, [
    ['A yearly fund fee, as a percent of assets',
     'A one-time commission some funds charge when you click buy',
     'The extra cents you pay when you cross from bid to ask',
     'A tax on dividends that appears only in retirement accounts'],
    ['A commission some mutual funds charge when you buy or sell',
     'The yearly percent taken from assets while you hold the fund',
     'The difference between bid and ask on an ETF quote',
     'A bonus load paid to you if the fund beats its index'],
    ['$30', '$3', '$300', '$0.75'],
    ['Costs compound and reduce what you keep, even when they look tiny',
     'Fees under 1% are refunded annually, so the sites mention them as trivia',
     'Costs only matter the day you buy; after that they stop touching the pile',
     'Talking about fees is how funds raise returns, which is why the sites harp'],
    ['No. Spreads, fund expenses, and possible advice fees can still apply',
     'Yes. Zero commissions means every other investing cost is also zero',
     'Yes for stocks; ETFs and funds cannot charge anything if commissions are $0',
     'No only in after-hours trading; during the session $0 means free'],
    ['$5 versus $100, which is a $95 gap that year',
     '$50 versus $100, because 0.05% on $10,000 is $50',
     '$5 versus $10, because 1% on $10,000 is $10',
     'There is no dollar gap; both percents round to the same fee'],
    ['The 0.04% fund, if they track the same idea, because less is skimmed',
     'The 0.85% fund, because a higher fee buys a better copy of the index',
     'They keep the same amount, because matching an index erases fee differences',
     'The 0.85% fund keeps more in down years, which is why the fee exists'],
    ['The bid-ask spread, and slippage when a fill is worse than you expected',
     'Only the expense ratio; trading has no other costs in this lesson',
     'Only a sales load; ETFs cannot have a spread if commissions are zero',
     'The company’s profit, which is billed to you as a trading cost'],
    ['I compare expense ratios and watch spreads, because percents repeat',
     'I ignore percents under 1%, because repeating costs cannot matter',
     'I pick the highest fee, because paying more means a safer fund',
     'I look only at last week’s return, which already includes every future fee'],
    ['You can still lose about what the market lost, minus a little extra for the fee',
     'Low fees reverse a 20% market drop, so the fund should finish near unchanged',
     'A cheap stock fund cannot fall 20%, which is the point of a low ratio',
     'The fee is refunded in down years, leaving you with the market’s 20% intact'],
]);

add(38, [
    ['A general rise in prices that makes each dollar buy less',
     'A rise in one stock’s price, which is the official inflation print',
     'A drop in prices that makes cash buy more groceries next year',
     'A fee funds charge that is named inflation on the statement'],
    ['What a unit of money can actually buy in goods and services',
     'The number printed on a bill, ignoring what shelves charge',
     'The interest a savings account must pay during a rising-price year',
     'The stock market’s return, used as a nickname for grocery costs'],
    ['About 10% less of that old pizza cart; it now takes about $110 to match it',
     'The same pizza cart, because a $100 bill cannot change what it buys',
     'About 10% more pizza, because higher prices mean cash is stronger',
     'None of the pizza, because a 10% rise retires old bills'],
    ['Nominal is the printed number; real is buying power after inflation',
     'Real is the printed number; nominal is buying power after inflation',
     'The two words mean the same leftover after a year of price changes',
     'Nominal includes inflation already; real is the number on the bill'],
    ['The balance can rise a little while real value still slips',
     'A 1% savings rate beats 3% inflation, so real value must rise',
     'If the balance number rises at all, purchasing power cannot slip',
     'Inflation at 3% raises the 1% savings rate to 4% automatically'],
    ['The basket got more expensive, which is a picture of inflation in that example',
     'The climb means leftover profit rose, because baskets are income statements',
     'A rising basket line is a stock chart, not a picture of prices in shops',
     'If the sample basket climbs, cash in a drawer buys more than before'],
    ['Inflation can shrink what the cash buys, even if the printed number is stable',
     'Holding only cash forever blocks inflation, which is why the number is safe',
     'A stable bill number means grocery prices cannot rise on that cash',
     'They missed that cash is required to beat inflation if you never invest'],
    ['No. Markets can fall, and real returns can still be negative',
     'Yes. Owning any investment is defined as beating a rise in prices',
     'Yes for stocks; only cash and bonds can lose to inflation',
     'No only in recessions; otherwise investments must outrun prices'],
    ['A sale on one headphone brand versus a broad rise in food, rent, and transit',
     'A broad rise in food and rent versus a sale on one headphone brand',
     'Both are inflation if any price you notice has changed this month',
     'Neither is inflation, because inflation is only a stock-market word'],
    ['The 3% interest can lose to 4% inflation in real terms, and the bond can also lose market value',
     'A 3% coupon beats 4% inflation, because interest is cash and inflation is not',
     'If a bond pays any interest, inflation cannot cut its real value',
     'Inflation at 4% raises the coupon to 4%, so real value is unchanged'],
]);

add(39, [
    ['A dollar today is usually worth more than the same dollar later',
     'A dollar later is usually worth more than the same dollar today, even with no interest',
     'Time does not change what a dollar can do if the number on the bill matches',
     'A later dollar is stronger because future prices are required to be lower'],
    ['$105', '$100', '$95', '$5'],
    ['$100', '$105', '$110', '$95'],
    ['The later $50 may buy less than $50 buys today',
     'Waiting with no interest raises what the $50 can buy, because you were patient',
     'Prices rising cannot touch money you have not received yet',
     'The later $50 is worth more in shops, which is why people wait'],
    ['$20 today, if you trust both payers equally',
     '$20 next year with no extra interest, because later numbers feel larger',
     'They are equal in value, so the date you get the $20 cannot matter',
     '$20 later, because time value means waiting is automatically better'],
    ['The chance you give up when you lock money into one use',
     'The fee a fund charges, renamed so it sounds like a missed chance',
     'The extra dollars you are owed for waiting, whether or not interest is paid',
     'The guarantee that the path you did not pick would have lost money'],
    ['The math uses an if; high offered rates can come with a real chance of losing the money',
     'Time value requires the riskiest asset, because the formula only works then',
     'Picking more risk deletes the chance of loss, which is how the math maximizes',
     'The video is right: a higher rate in an example is a promise you will be paid'],
    ['Time and a rate can change the pile: $100 versus $105 in this example',
     'The bars prove every $100 becomes $105 in live markets this year',
     '0% and 5% must finish at the same height, because both start at $100',
     'The 0% bar is a stock; the 5% bar is cash, which is why they differ'],
    ['Compounding is time value with earnings left in to earn again, and still not a guarantee',
     'Compounding replaces time value, so Rank 1 and this lesson cannot connect',
     'Time value means compounding cannot go negative, which is the Rank 1 rule',
     'The connection is that both ideas freeze your pile at the classroom example'],
    ['The two amounts are equal numbers; later is usually weaker unless extra interest and trust show up',
     'Later $200 is automatically better, because future-rich is how time value is defined',
     'Today’s $200 is weaker even with no inflation, because waiting creates extra dollars',
     'You should pick later if the numbers match, to collect a hidden time bonus'],
]);

add(40, [
    ['A mix of different investments so one failure hurts the total less',
     'A single famous stock, because one well-studied name is the mix',
     'Trading every hour so no holding lasts long enough to be a risk',
     'Holding only cash, which this lesson treats as a complete stock mix'],
    ['Ben: a total U.S. stock fund plus a bond fund',
     'Ava: five tickers that all hold the same handful of giant companies',
     'Chris: one company he researched for a month, held as 100% of the account',
     'Drew: cash only, labeled as a stock-and-bond mix in the notes'],
    ['No. Diversification never promised a floor; it only changes how risk is spread',
     'Yes. A 12% drop proves a stock-and-bond mix does not count as diversified',
     'Yes, unless bonds are in the mix, in which case a 12% drop cannot happen',
     'No, and a rough year means the mix was secretly only one stock'],
    ['It can hold many companies in one share, which spreads single-name risk',
     'One fund cannot be diversified, because diversification needs five tickers minimum',
     'Broad index funds are one company with a basket nickname',
     'An index fund is cash, so it counts as mixed only when the market is closed'],
    ['Overlap: you may not be as mixed as the ticker count suggests',
     'Five tickers always means five different bets, even if the insides match',
     'Holding more ETFs automatically removes overlap, by the definition of a fund',
     'Giant U.S. companies cannot overlap, which is why five funds are safer'],
    ['One example of spreading across asset types; those weights are a choice, not a law',
     'The only legal mix: 60/30/10 must be used after Rank 2',
     'A forecast that this mix cannot fall, which is why the bars are shown',
     'Proof that cash at 10% cancels stock risk in the other 60%'],
    ['A few low-cost funds that actually hold different things',
     'Many pricey funds that repeat the same giant holdings',
     'The largest number of tickers, even if every fund copies the same list',
     'The highest-fee mix, because paying more buys more true variety'],
    ['Cover near-term needs, while inflation can still shrink what that cash buys',
     'Guarantee the rest of the mix cannot fall, which is cash’s main job',
     'Match stock returns with less bumpiness, by sitting in the 10% sleeve',
     'Replace bonds entirely, because cash and bonds are the same asset'],
    ['Usually no. Near-term money belongs in easier-to-reach places, because stocks can drop suddenly',
     'Yes. Three weeks is the standard stock holding period in this lesson',
     'Yes, if the mix includes bonds, which makes a three-week stock sleeve safe',
     'Usually no only for live money; practice laptop money should be in jumpy stocks'],
    ['I can mix stocks, bonds, and funds, watch fees and orders, and I know I can still lose money',
     'I finished Rank 2, so a careful mix is no longer allowed to fall',
     'Fees and orders do not matter once you can name stocks and bonds',
     'Rank 2 means I should pick one stock, because mixing is a Rank 1 idea only'],
]);

export const byLesson = L;
