import { pack } from './harden-lib.mjs';

const L = {};
function add(id, rows) {
    L[id] = rows.map((row, i) => pack(id, i, ...row));
}

add(1, [
    ['To buy goods, save for later, and compare prices',
     'To prove you already succeeded before you spend anything',
     'To guarantee that cash will buy more groceries next year',
     'To replace friendship and time with one wealth score'],
    ['Paying $8 for a sandwich and keeping $5 for next week',
     'Swapping a sandwich for a haircut with no prices listed',
     'Hiding every dollar because spending would destroy its value',
     'Printing extra play money so listed prices stop mattering'],
    ['Kai can pay listed prices and keep leftover cash for later',
     'Kai must find one person who wants a $10 bill and both items',
     'Kai can force the store to take apples in place of the bill',
     'Kai can change both price tags just by wanting them lower'],
    ['Trading goods or services directly, with no money in between',
     'Keeping a bank balance that is guaranteed never to fall',
     'Buying a slice of a company through a public stock exchange',
     'A rule that freezes every price so trade never needs cash'],
    ['People accept that balance as something you can spend or save',
     'Only coins and paper bills count, so the number is just a label',
     'Account balances automatically grow by a set amount each night',
     'Digital balances cannot be used to compare one price with another'],
    ['Prices act as a measuring stick so you can compare costs',
     'Prices hide value so shoppers cannot tell shirts apart',
     'The $28 tag promises that shirt will last the longest',
     'The higher tag proves the $28 shirt is automatically better'],
    ['Everyday prices can rise, so the same dollars may buy less',
     'Cash sitting still always turns into company stock over time',
     'Money stops working as a tool after it is one year old',
     'Banks delete old bills on a schedule, so unused cash vanishes'],
    ['Money is useful, but it does not promise you will have more later',
     'Having money always means you are already a skilled investor',
     'Only paper bills count as money; cards are never real money',
     'Money and friendship are the same kind of value in every case'],
    ['Riley bought something now and set the rest aside for later',
     'Any leftover cash is automatically an investment in a company',
     'Putting bills in a drawer creates brand new dollars from nothing',
     'The $12 in the drawer is guaranteed to buy more next year'],
    ['Money works when people accept it for trade and for prices',
     'Money only works if every piece of it is made from gold',
     'Money is valuable only when you refuse to spend any of it',
     'Money removes the need to choose between one purchase and another'],
]);

add(2, [
    ['Jordan, because a company slice can grow in value or lose it',
     'Maya, because any money you do not spend today counts as investing',
     'Both, because saving and investing are two names for one action',
     'Neither, because investing is only allowed for banks and funds'],
    ['Keep money available for later needs, with less chance of a big loss',
     'Buy assets that might jump around in price for a shot at growth',
     'Lock cash into a stock so it cannot be used for bills or repairs',
     'Turn every spare dollar into a loan that a company must repay'],
    ['Keep it in savings you can reach; a price drop would be a problem',
     'Buy a volatile stock so two weeks of growth can cover the fee',
     'Lend it to a friend as an investment because it will earn extra',
     'Hide it as cash under a mattress labeled as a long-term portfolio'],
    ['The assets you buy can fall in price after you own them',
     'Savings accounts are required to cut your balance each month',
     'Investing is illegal unless a bank promises you cannot lose',
     'Prices are frozen by law, so losses can only come from fees'],
    ['Save money you may need soon; invest extra you can leave for longer',
     'Invest money you need next week; save only cash you will never use',
     'Treat stocks as a piggy bank and savings as a high-risk asset',
     'Use investing for bills and saving only after every stock is bought'],
    ['Savings for surprises, so you are less likely to sell at a bad time',
     'A stock fund that pays you the day a surprise bill arrives',
     'A loan from a company that you repay only if markets go up',
     'A rule that investments cannot be sold when you have an emergency'],
    ['If the stock falls, Alex may not have enough left for the bill',
     'Stocks cannot be bought with money that would have paid a bill',
     'Phone bills are paid automatically from whatever stock you pick',
     'A one-month stock hold is guaranteed to beat a savings account'],
    ['Save for needs and a cushion; invest only extra money you can risk',
     'Invest first with rent money, then save whatever happens to be left',
     'You must pick only one: people who save are not allowed to invest',
     'If you save at all, investing becomes risk-free because of the cushion'],
    ['A piggy bank holds cash; a stock’s price can jump around and fall',
     'A piggy bank and a stock are both guaranteed to keep the same value',
     'A stock holds cash the same way a jar does, just with a ticker',
     'A piggy bank can lose half its coins overnight like a share price'],
    ['Those $10 can grow or shrink; investing is allowed to lose money',
     'Those $10 are as safe as a savings jar because the cushion exists',
     'Ten dollars invested for years cannot fall below the starting amount',
     'Once money is extra, investing turns it into a guaranteed gain'],
]);

add(3, [
    ['Using money to buy something you hope will grow or pay you later',
     'Spending money on something you will use up right away, like a snack',
     'Moving cash from a checking account into a jar you can open anytime',
     'Lending money only if a website promises you cannot lose a dollar'],
    ['A concert ticket is spending; a share of a company is investing',
     'A concert ticket is investing; a share of a company is only spending',
     'Both are investing, because any use of money is an investment',
     'Both are spending, because stocks are consumed like tickets'],
    ['Lee lost $6 of market value; investing is allowed to go down',
     'Lee is still even, because shares cannot be worth less than cost',
     'Lee gained a hidden $6 credit that appears when the year ends',
     'The $14 price is only a label; Lee can still cash out $20'],
    ['Results are uncertain, so you can lose money as well as gain',
     'Companies are required to match whatever return an ad described',
     'Hope and promise mean the same thing in investing language',
     'A promise is better because past years already lock in future gains'],
    ['Ownership: you own a slice of a business with other shareholders',
     'A loan: the company must pay you back on a fixed date',
     'A gift: the company owes you a prize whether it earns money or not',
     'A subscription: you rent the logo until you cancel next month'],
    ['Treat it as a warning; real investing can lose money, not a lock',
     'Believe it, because ads are not allowed to overstate returns',
     'Ignore the risk words; a $10 start is too small to ever fall',
     'Take it as proof that all public stocks have a loss floor of zero'],
    ['You usually own a real asset and accept uncertain results over time',
     'You pick heads or tails, and the coin decides the same day',
     'You cannot lose if you hold overnight, unlike a coin flip',
     'A coin flip owns a business; a stock is only a scoreboard label'],
    ['Goals, how much time they have, and the chance of losing money',
     'Only the logo, because design is the best predictor of returns',
     'Only yesterday’s jump, because one up day locks in the next day',
     'Only a stranger’s screenshot, because shared gains cannot reverse'],
    ['Pat can still lose money if the investment’s price falls later',
     'Extra money plus a long wait makes losses against the rules',
     'After savings exist, remaining cash is treated as a guaranteed gain',
     'Many years of holding convert any purchase into a savings account'],
    ['Investing is a tradeoff: a chance of growth and a chance of loss',
     'Investing is a receipt: you pay now and collect a fixed prize later',
     'Investing is a refund: the market owes you your starting amount',
     'Investing is a shortcut: time spent holding deletes the chance of loss'],
]);

add(4, [
    ['A marketplace where people buy and sell shares of public companies',
     'A warehouse that stores every company’s products until they sell',
     'A government office that sets one daily price for all stocks',
     'A savings club that pays a fixed rate and never lets prices fall'],
    ['Both match people who want to buy with people who want to sell',
     'Both freeze prices so nobody has to agree on a trade',
     'Both give every visitor the same bag of goods at one posted price',
     'Both are only for farmers, so stocks cannot trade in a market'],
    ['A company whose shares the public can buy and sell on an exchange',
     'Any shop that lets customers walk in, even if it never issued shares',
     'A firm owned by one family that has never sold stock to outsiders',
     'A company that only governments are allowed to buy pieces of'],
    ['Usually no; private firms are not traded like listed public stocks',
     'Yes; every bakery share appears on the stock market by default',
     'Yes, if you ask the exchange to print a ticker for that shop',
     'Usually yes; private and public mean the same thing for trading'],
    ['Trades: buyers and sellers agreeing on a price in the marketplace',
     'A single official who types tomorrow’s price each evening',
     'The company’s factory output, which becomes the share price 1-for-1',
     'Last year’s revenue, copied forward as this year’s locked price'],
    ['A summary of many stocks moved down; not every name had to fall',
     'Every listed company dropped by the exact same percent that day',
     'The market was closed, so no prices existed anywhere that day',
     'Only one famous stock fell, and headlines treat that as the market'],
    ['A stock is one company’s shares; the market is the marketplace',
     'A stock and the market are two words for the same single company',
     'The market is one share; a stock is the whole list of every firm',
     'There is no difference once a company has any customers at all'],
    ['Prices can rise or fall as people trade; nobody is owed tomorrow',
     'Exchanges are required to push prices up after every down day',
     'Once a company is public, its shares cannot trade below the IPO',
     'Brokers sign a pledge that customers will not see a losing year'],
    ['Sending her order through a broker so it can meet a seller',
     'Printing a new share at the company and mailing her a product',
     'Moving cash into the company’s register as soon as she taps buy',
     'Setting a law that the price she saw at lunch cannot change'],
    ['The stock market is a marketplace, and the scoreboard can fall too',
     'The stock market is a promise that listed prices only move up',
     'The stock market is a museum of old prices that never trade again',
     'The stock market is a savings account with a ticker as decoration'],
]);

add(5, [
    ['A small slice of ownership in that company, not its office furniture',
     'A loan the company must repay you on a date printed on the share',
     'The company’s building, which you can visit and use as your own',
     'A coupon for that company’s products, equal to what you paid'],
    ['A stock is ownership; a loan is money the borrower should pay back',
     'A stock and a loan are the same claim, just with different names',
     'A loan is ownership of the business; a stock is only a receipt',
     'Neither one can lose value, because both are cash in another form'],
    ['Mostly to the seller of that share, not into the company’s register',
     'Straight into the company’s cash register as brand new funding',
     'Into a public pot that every shareholder must split that afternoon',
     'Nowhere; practice trades create shares without a counterparty'],
    ['To raise money for the business by selling new shares to investors',
     'To lower the share count so each owner automatically owns more',
     'To cancel old shares so the price can never fall again',
     'To pay a tax that is due only when a ticker symbol is created'],
    ['Someone who owns stock in the company, even a very small amount',
     'Only a CEO or board member; small buyers are never shareholders',
     'Anyone who likes the brand, whether they own shares or not',
     'A lender who is owed interest but has no ownership stake'],
    ['The market price is $27, so the value of that holding fell',
     'You still have a locked-in $30, because you did not click sell',
     'The company owes you the $3 difference as a cash refund',
     'Prices shown after you buy are only estimates, not real quotes'],
    ['A short code used to label a company’s shares in quotes and orders',
     'The legal name of the CEO, printed beside every trade',
     'A count of how many products the company sold that morning',
     'A guarantee stamp that the price will not move for 24 hours'],
    ['Stock is a claim through the company; you do not take office gear home',
     'Buying stock lets you take a laptop or chair as personal property',
     'Shareholders own every tool in the building in equal physical pieces',
     'A share is a rental of the headquarters until you sell the ticker'],
    ['Owning a slice still means that slice can lose market value',
     'Once you own any share, losses are against the rules for that name',
     'Buying “the company” converts the position into a savings balance',
     'Small slices cannot fall because only large owners take the risk'],
    ['A stock is a piece of a company and its value can rise or fall',
     'A stock is a cash IOU that pays you the purchase price on demand',
     'A stock is a coupon book whose value is fixed at the checkout price',
     'A stock is a loan to you from the exchange, due when you sell'],
]);

add(6, [
    ['Buyers and sellers change how many shares they want and will pay',
     'A daily official sets one price that every trader must accept',
     'Factories print new share prices based on how many products ship',
     'Last year’s revenue is copied forward as a locked quote each morning'],
    ['The price often rises when extra buyers chase fewer willing sellers',
     'The price must fall, because more interest always means a glut of shares',
     'The price freezes until the company publishes a new official quote',
     'The exchange cancels the ticker until the crowd of buyers thins out'],
    ['More people may sell, so the price may fall, but that path is not certain',
     'The price must drop by the same percent as the sales miss, by rule',
     'Weak sales cannot affect a listed stock until the next calendar year',
     'The exchange pauses the name until sales return to last year’s level'],
    ['Closing prices can rise some days and fall on others, even in a short stretch',
     'A four-day chart proves the next month will copy the same staircase',
     'Once a close is printed, that price is locked for the rest of the year',
     'Day-to-day closes only move up; down days are recording errors'],
    ['They may value the news differently, so one wants to buy and one to sell',
     'Headlines assign one official fair price that every reader must use',
     'If two people disagree, the stock is removed from public trading',
     'News can only be read one way, so disagreement means someone broke a rule'],
    ['Wide fear or a weaker economy can cut demand for many stocks at once',
     'If many names fall together, that proves each company failed that morning',
     'Economy-wide news is not allowed to change more than one ticker a day',
     'A weak economy raises every stock, because buyers rush in automatically'],
    ['Fear can trigger extra sell orders, and that selling can push the price down',
     'Fear is only a feeling, so it cannot show up in actual trade prices',
     'Fear forces the exchange to raise prices to calm people back into buying',
     'Fear deletes the order book until everyone reports they feel confident'],
    ['A jump today can reverse tomorrow; nobody is owed the next print',
     'After a jump, the next close is required to be at least as high',
     'Intraday jumps are stored as a floor the price cannot cross again',
     'If it jumped at lunch, brokers must fill you at that same price later'],
    ['A guaranteed price that will hold for the rest of the year',
     'The most recent trade direction people are using in the session',
     'Whether that name has been ticking up or down in the latest quotes',
     'A short hint about recent order flow, not a long-term contract'],
    ['Stock prices move with supply and demand, and they can fall as well as rise',
     'Stock prices only rise after a company lists, because demand is permanent',
     'Supply and demand set products, not shares, so quotes are just decoration',
     'Once demand appears, the price is not allowed to print a down day'],
]);

add(7, [
    ['You own a piece of the company along with the other shareholders',
     'You manage daily operations and can veto any product the CEO picks',
     'You lent the company cash that it must repay you on a printed date',
     'You rented the brand name until your brokerage subscription ends'],
    ['One giant-company share is usually a much smaller slice of that business',
     'One share always equals one percent of the company, giant or tiny',
     'Tiny companies issue fewer products, so one share is legally two votes',
     'Share size is identical at every firm; only the ticker letters change'],
    ['Managers make many daily choices; a small owner’s voice is usually limited',
     'Any shareholder can stop a product by emailing the store that week',
     'Managers cannot launch products unless every owner clicks approve',
     'Disliking a product automatically converts your shares into a refund'],
    ['Whoever owns more shares generally has more votes on those questions',
     'Every owner gets one vote, no matter how many shares they hold',
     'Only employees vote; outside owners watch but cannot be counted',
     'Votes go to whoever bought most recently, even with a single share'],
    ['You can lose what you paid for the shares, not typically all company debts',
     'You personally owe every company bill if the business runs short',
     'Limited liability means the shares cannot fall below what you paid',
     'Owners never lose money, because debts transfer to the government'],
    ['Your shares can be worth much less, or even close to nothing',
     'The exchange refunds your purchase price when a collapse is confirmed',
     'Shareholders are billed extra until the old price is restored',
     'A collapse only hits managers; outside owners keep a frozen value'],
    ['Possible upside if the business is worth more; possible loss if shares fall',
     'Upside only: part-owners are not allowed to see a lower quote',
     'Risk only: ownership cannot become more valuable than cash in a jar',
     'Neither upside nor risk, because shares are a membership sticker'],
    ['A group that oversees big direction while managers handle much daily work',
     'The people who ring up customers and stock shelves each afternoon',
     'A club of all small shareholders that votes on every supply order',
     'An app feature that sets the next day’s price before the open'],
    ['They hope the slice becomes more valuable or may share profits, with real loss risk',
     'They become the boss on day one and can fire managers at lunch',
     'Part-owners are paid a salary equal to the share price each month',
     'Not being the boss means the slice is insured against any decline'],
    ['Owning stock makes you a part-owner whose slice can rise or fall',
     'Owning stock makes you the daily manager of stores and factories',
     'Owning stock is a loan that matures at the price you originally paid',
     'Owning stock is a coupon for free products until you sell the ticker'],
]);

add(8, [
    ['One unit of a company’s stock, which you can buy or sell in pieces',
     'The company’s entire business, transferred to you with a single click',
     'A loan contract that pays you a fixed amount on a printed date',
     'A ticket to the headquarters tour, unrelated to ownership at all'],
    ['$48', '$54', '$14', '$80'],
    ['$35', '$50', '$15', '$70'],
    ['You cannot tell which company is “better” from share price alone',
     'The $400 stock is always a larger, safer company than the $20 stock',
     'The $20 stock must be cheaper in value, so it is the better buy',
     'Share price is the same idea as the company’s total size'],
    ['Both positions start with $100 of stock value before prices move',
     '100 shares at $1 are worth more because the share count is higher',
     '2 shares at $50 are worth more because each share looks expensive',
     'Share count always beats price, so 100 shares cannot equal 2 shares'],
    ['Famous companies often have millions or billions of shares outstanding',
     'Famous companies issue only a handful of shares, so one share is huge',
     'A well-known brand means each share is legally 10% of the business',
     'Ticker fame sets a minimum slice size that small buyers cannot go under'],
    ['It is still a piece of ownership, and that piece can lose value',
     'Half a share is only a coupon and cannot change with the market',
     'Fractional shares are insured to stay at the price you clicked',
     'You cannot own less than one share, so 0.5 is only a display error'],
    ['More slices alone do not make the whole pie more valuable',
     'A split creates new value equal to the extra slices printed',
     'After a split, each new share is worth the old price plus a bonus',
     'Splits are how exchanges guarantee owners a higher total value'],
    ['Selling those units to someone else at a price that may be above or below cost',
     'Returning them to the company for the exact price you originally paid',
     'Deleting the shares so the supply shrinks and your remaining stock is safer',
     'Converting them into cash at last month’s high, even if quotes are lower'],
    ['A share is a unit; dollars at risk are about price times how many you own',
     'A share is a unit, but dollars at risk are always $1 no matter the price',
     'Share count is decorative; you only risk the ticker’s first letter value',
     'Owning more shares reduces dollars at risk because the risk is split'],
]);

add(9, [
    ['An organized marketplace that matches buy and sell orders under rules',
     'A news site that publishes opinions about which brands people like',
     'A warehouse that stores products until customers pick them up',
     'A savings club that holds cash and never prints a changing price'],
    ['An exchange uses published rules and a system for matching many orders',
     'Street-corner trades and exchanges follow identical matching rules',
     'Exchanges ban matching; each buyer must find a seller by phone',
     'Any handshake in public is legally the same as a listed exchange trade'],
    ['Two well-known U.S. stock exchanges where listed shares can trade',
     'Two government departments that set one national stock price daily',
     'Two product brands that sell computers, unrelated to share trading',
     'Two savings banks that pay a fixed rate and do not match orders'],
    ['Usually no; a private family firm is not listed for public trading',
     'Yes; liking a brand is enough for it to appear on the NYSE today',
     'Yes, because every company with customers is automatically listed',
     'Usually yes; private and listed mean the same thing on U.S. exchanges'],
    ['Its shares can trade there if the company meets that exchange’s requirements',
     'The company donated its logo, so the ticker is only decorative',
     'Listing means the price is insured and cannot print a down day',
     'Every private shop is listed by default the day it opens a register'],
    ['The main session’s crowd is gone; a quote may be last-sale or thinner trading',
     'U.S. listed stocks cannot change at all after 4 p.m., even elsewhere',
     'After hours, exchanges refund any price that differs from the close',
     '9 p.m. is when the NYSE assigns tomorrow’s official locked price'],
    ['A firm that helps send your orders toward the marketplace',
     'A judge who decides the fair price before any trade can happen',
     'The company’s factory manager who approves each public purchase',
     'A news anchor whose opinion becomes the next printed last sale'],
    ['The first is about a group of listed stock prices; the second is a grocery tag',
     'Both sentences describe the same thing: one official cost of living number',
     'If the NYSE is down, milk is required to get cheaper the same day',
     'Grocery prices and stock indexes are two names for the same list'],
    ['Listing makes shares easier to trade under rules; the stock can still fall',
     'A famous listing converts the stock into a risk-free savings balance',
     'Once listed, brokers must restore any decline before the next open',
     'Exchanges admit only companies whose prices are not allowed to drop'],
    ['An exchange matches trades; matched prices can still fall after you buy',
     'An exchange matches trades only on up days; down prints are rejected',
     'Matching is a ceremony; listed prices are copied from last year’s close',
     'Once matched, a trade price becomes a floor the quote cannot cross'],
]);

add(10, [
    ['That prices are more likely to rise in the period they have in mind',
     'That prices are more likely to fall, so they only sell and never buy',
     'That the market is closed, so no quotes should be trusted this week',
     'That every stock they own is insured against any decline'],
    ['That prices are more likely to fall in the period they have in mind',
     'That prices can only rise, which is why bears refuse to look at quotes',
     'That they work at an exchange and set the official daily close',
     'That cash is worthless, so they must hold stocks no matter the drop'],
    ['Bull describes a broad rising stretch; bear describes a broad falling stretch',
     'Bull and bear are two tickers, not descriptions of a market period',
     'A bull market means only one stock rose; a bear market means one stock fell',
     'Bull means the market is closed; bear means it is open for trading'],
    ['Yes. A broad rising stretch does not lift every single stock',
     'No. In a bull market every listed name must print a higher close',
     'Only if the stock is unlisted; listed names cannot fall in a bull stretch',
     'Yes, but the exchange later edits the print so the drop did not count'],
    ['Bullish is an opinion; prices can still fall and you can still lose money',
     'Calling yourself a bull activates a rule that blocks losing trades',
     'Bulls are refunded automatically if a name they like prints lower',
     'The nickname is a contract: brokers owe bulls last month’s high'],
    ['They label a mood or a stretch of time; they do not guarantee the next move',
     'They are official forecasts that exchanges must make come true',
     'Once the nickname is used, the opposite move is not allowed to print',
     'Bulls and bears are two funds whose returns are fixed in advance'],
    ['Bullish on one company and bearish on another at the same time',
     'Only all-in bullish or all-in bearish on every stock that exists',
     'Bullish on cash only; stocks do not get those nicknames per name',
     'Neither, because the nicknames apply only to the whole planet’s GDP'],
    ['That is a trap. Rising stretches can end, and prices can fall afterward',
     'It is a rule: after a long rise, down days are posting errors',
     'Long rising stretches convert the market into a savings account',
     'If it rose for a long time, next year’s return is already locked in'],
    ['Bearish on what, for how long, and what happens if that view is wrong',
     'Whether they prefer a cartoon mascot, which is the whole meaning',
     'Which broker will refund them when the bearish call misses',
     'How to force the exchange to lower every ticker to match the view'],
    ['Markets go through rising and falling stretches; neither is guaranteed to last',
     'Once a bull stretch starts, it is required to continue for ten years',
     'Bear stretches cannot happen in public markets, only in private firms',
     'Rising and falling are labels for logos, not for price periods'],
]);

add(11, [
    ['The collection of investments you own, looked at together as one mix',
     'A single famous stock that everyone is required to hold',
     'A loan you take from a broker that must be repaid on Friday',
     'A news headline that lists yesterday’s most popular tickers'],
    ['One stock is a holding; a portfolio is the set of holdings together',
     'A portfolio is always exactly one stock, just with a fancier name',
     'A holding is the whole mix; a portfolio is only cash you have not used',
     'They are identical: any purchase is both a portfolio and a market'],
    ['It is concentrated: that one holding drives almost the whole result',
     'It is diversified automatically, because practice money cannot cluster',
     'One company still counts as a full market index in a student account',
     'Concentration only applies to real money, not to practice shares'],
    ['$100', '$80', '$60', '$20'],
    ['The larger holding can weigh more in the total, so the mix can still fall',
     'A 30% winner always forces the whole backpack up, no matter the other size',
     'Portfolio math ignores size; each name counts as an equal vote of + or −',
     'If any name is up 30%, losses in other names are erased from the total'],
    ['Cash is money not yet in stocks, or kept for needs, and still part of the mix',
     'Cash cannot sit in a portfolio; the mix is defined as stocks only',
     'Cash in a portfolio is treated as a stock with a hidden ticker',
     'Including cash means the portfolio is closed and cannot change value'],
    ['One mix is concentrated; the other is spread across more holdings',
     'Both mixes are identical because they started with the same $100',
     'Four stocks always behave like one stock if the dollars match',
     'The concentrated mix is safer because there is less to keep track of'],
    ['One winner does not erase other holdings that may be down at the same time',
     'The highlight reel is the official score; losers are not part of a portfolio',
     'If one name doubled, the rest of the mix is assumed to have doubled too',
     'Judging by the best holding is required, because averages hide skill'],
    ['Its value can still change as the holdings’ prices change without a trade',
     'If you do not click, prices freeze until you return to the app',
     'Portfolios only move on days you place an order, by design',
     'A quiet week converts the mix into a savings balance that cannot fall'],
    ['A portfolio is your mix; its value can rise or fall as holdings move',
     'A portfolio is a trophy case of past wins that cannot show a loss',
     'A portfolio is only practice if it never changes from the starting cash',
     'A portfolio is a single ticker the exchange assigns to each student'],
]);

add(12, [
    ['The chance results go worse than you hoped, including losing money',
     'The guarantee that every stock will pay you extra if you wait a week',
     'A fee the app charges, unrelated to prices moving against you',
     'The rule that practice accounts cannot print a lower value'],
    ['A single stock can lose a large share of its value; savings is built to protect dollars more',
     'A single stock is safer than savings because it can grow without falling',
     'Savings and a single stock have the same chance of a sudden 40% drop',
     'Savings accounts swing more than stocks because cash is marked each hour'],
    ['Prices bounce around a lot, up and down, over the period you watch',
     'The company is about to be deleted from the exchange overnight',
     'Volatility means the price is frozen and cannot print a new close',
     'It is a nickname for a dividend that arrives on the same day each year'],
    ['A drop could leave you short when that required fee is due',
     'Jumpy stocks are reserved for money you must spend within a month',
     'Required fees are paid by the exchange if your practice stock falls',
     'One month is long enough that a volatile name is treated like cash'],
    ['Be skeptical: higher hoped-for return usually comes with more risk, not zero',
     'Believe it: ads are not allowed to pair “high return” with “no risk”',
     'No-risk high return is the normal package for any listed stock',
     'If the video is popular, the no-risk claim has already been tested'],
    ['A loss is ending worse off; volatility is the bumpy path along the way',
     'Volatility and loss are the same word, so a bumpy week is always a loss',
     'A loss is only a feeling; volatility is the only number that can be negative',
     'If a path was volatile, the ending result is required to be positive'],
    ['No. Growth-seeking stock investments still include a chance of loss',
     'Yes. Diversified stocks are not allowed to finish below your start',
     'Yes, if you check the app daily, risk is removed from public companies',
     'No, unless you hold overnight; then growth stocks become cash-like'],
    ['Some risks can hit many stocks at once; spreading does not erase every risk',
     'If several names fall together, diversification is proven to be fake',
     'A bad month for many stocks means your mix was secretly only one company',
     'Broad drops cannot happen; each stock’s risk is fully separate by law'],
    ['If this fell a lot, would I still be okay for the goal I care about?',
     'Which logo is trending, so I can ignore how much I could lose?',
     'How do I turn off down days so only up days count in the total?',
     'Which friend made money last week, so I can copy them without a plan?'],
    ['Investing can lose money, and bigger hoped-for gains usually mean more risk',
     'Investing can lose money only in private companies, not public stocks',
     'Bigger hoped-for gains come from deleting risk, not from accepting more of it',
     'If you hope for more return, the market owes you a smaller chance of loss'],
]);

add(13, [
    ['How much you gained or lost on an investment over a period',
     'A fee you pay the app, whether the holding went up or down',
     'Only a gain: losses are recorded under a different name',
     'The company’s sales that year, copied onto your account as cash'],
    ['10%', '1%', '20%', '110%'],
    ['−$10', '+$10', '−$40', '$50'],
    ['−20%', '−10%', '+20%', '−80%'],
    ['The first is 10%; the second is only 1% of the larger starting amount',
     'Both are 10%, because $10 of gain is always a 10% return',
     'The $1,000 example is 10% too, because dollars of gain match',
     'Percent return ignores starting size, so both count as the same score'],
    ['Only that last year happened; this year could be higher, lower, or negative',
     'This year must also be 20%, because last year is a contract',
     'After a 20% year, the next year is required to be at least 10%',
     'A past 20% return refunds you if this year prints anything lower'],
    ['100%', '50%', '25%', '200%'],
    ['Return means the result, which can be negative if you are worse off',
     'Return is only allowed to be a plus number in investing language',
     'A loss cannot be a return because return is a synonym for profit',
     'Negative results are fees, not returns, even if the price fell'],
    ['The market price can already be down; selling is what locks that result in',
     'Until you sell, a lower quote is imaginary and cannot affect you',
     'On-paper declines are refunded automatically if you wait overnight',
     'Selling cannot lock a loss; the broker must fill you at your purchase price'],
    ['Return can be a gain or a loss, and last year’s number is not next year’s promise',
     'Return can only be a gain, and last year is treated as a forecast',
     'If last year was positive, this year’s return cannot print negative',
     'Return is a nickname for the dividend, so price changes do not count'],
]);

add(14, [
    ['Businesses and prices need room to work, and short stretches are noisy',
     'Time is a rule that converts any purchase into a guaranteed gain',
     'Short stretches are the real signal; years of data are mostly noise',
     'Investing is built for next week, so long waits are a sign you are late'],
    ['Ten-minute checks show a lot of weather; long goals care more about the climate',
     'Ten-minute checks are the official way to judge a years-long plan',
     'Long goals should be managed by reacting to every bounce on the tape',
     'Weather and climate are the same in markets, so the interval does not matter'],
    ['There may not be time to recover if the price drops before you need the cash',
     'Three weeks is the standard holding period that removes volatility',
     'Volatile stocks are designed for bills that are due within a month',
     'If you need money soon, a jumpy stock is safer than a savings balance'],
    ['No. A stock can stay down or fail even if you wait a long time',
     'Yes. Waiting is enough to repair any weak business on its own',
     'Yes, if you wait a year, exchanges restore the old higher price',
     'No, unless the logo is famous; famous names cannot stay weak'],
    ['That is a get-rich-quick pitch; real investing is uncertain and usually slower',
     'Monday deadlines are normal for serious long-term investing plans',
     'If the post is confident, the stock is required to jump by Monday',
     'Get-rich-by-Monday claims are how indexes are officially forecast'],
    ['Trying to jump in and out at perfect minutes instead of following a plan',
     'Holding for years without ever looking at what you own',
     'Matching your mix to a goal date and leaving extra money invested',
     'Saving for a bill that is due before you would sell a volatile stock'],
    ['Patience means you do not let every bounce boss you; you can still learn',
     'Patience means you never read another fact once you have clicked buy',
     'If you are patient, you must ignore a company that is clearly failing',
     'Patience and “never thinking again” are two names for the same habit'],
    ['Short slumps happen; time may help, but you are not owed a recovery',
     'Three months down means the recovery is already scheduled next week',
     'Practice slumps are reversed automatically because the money is pretend',
     'If it fell for a quarter, it cannot fall further, so waiting is a lock'],
    ['Money you need soon cannot afford a long wait for a possible recovery',
     'The clock does not matter; every tool is safe at every deadline',
     'Near-term money should go into the jumpiest stock for extra speed',
     'Long-term tools are required for bills that are due this month'],
    ['Investing is built for longer goals; time is not a promise of profit',
     'Investing is built for this afternoon; longer goals do not use stocks',
     'Time guarantees profit if you simply refuse to look at prices',
     'Longer goals delete risk, so time and profit are the same word'],
]);

add(15, [
    ['Earning a return on the new total, including growth you already earned',
     'Earning the same dollar amount each year on only the original cash',
     'Adding a fee at the end of each year whether the holding rose or fell',
     'Resetting the pile to $100 each January so growth cannot stack'],
    ['$110', '$100', '$90', '$10'],
    ['$121', '$120', '$130', '$220'],
    ['Simple addition ends at $120; compounding at 10% twice ends at $121',
     'Both methods end at $120, because two years of 10% is always $20',
     'Compounding ends at $120; simple addition is the one that reaches $121',
     'Both methods end at $110, because year 2 does not change the total'],
    ['The classroom path goes $100 to $110 to $121; real returns can be negative',
     'The chart is a forecast that your account will follow those exact prints',
     'After two up years in an example, live markets cannot print a loss',
     'Classroom 10% steps are copied into every public stock by rule'],
    ['$99, because 10% of $90 is $9, which does not fully replace the drop',
     '$100, because a 10% rise always cancels a 10% fall',
     '$110, because the rise is applied to the original $100, not to $90',
     '$90, because after a drop the later 10% rise does not count'],
    ['Disagree; if returns are negative, compounding can shrink the pile',
     'Agree; compounding is a shield that blocks any down year from counting',
     'Agree, because once growth stacks, later losses are rounded up to zero',
     'Disagree only for fees; price drops cannot reduce a compounded total'],
    ['The arithmetic is easy to follow; 10% is not a prediction for your account',
     'Teachers use 10% because that is the official long-run stock market rate',
     'The example is a promise that careful students will earn 10% a year',
     '10% is required in compounding; other percents are not allowed in math'],
    ['More years give more chances for growth-on-growth, if growth actually happens',
     'Starting earlier guarantees a larger pile even if every year is negative',
     'Compounding only works for people who start after the example year',
     'Extra years delete the chance of loss, which is why earlier is safer'],
    ['Later returns apply to the new total; actual returns vary and can be negative',
     'Later returns apply only to the original cash; the new total is ignored',
     'Compounding means the total cannot fall once it has risen once',
     'Actual returns are fixed at the classroom 10%, so variation is a glitch'],
]);

add(16, [
    ['Cash a company may pay to people who own its shares',
     'A required monthly fee owners pay the company to keep their shares',
     'The jump in price on the day a product ships, counted as income',
     'A loan the shareholder must repay if the stock prints a down day'],
    ['One may send cash to owners now; the other may keep cash in the business',
     'The payer is always the better company; skipping dividends means failure',
     'The non-payer cannot grow, because unused cash expires each quarter',
     'Both policies are illegal unless the yield matches a savings account'],
    ['$5.00', '$0.50', '$10.00', '$50.00'],
    ['The board can reduce or stop the dividend after a weak year',
     'Last year’s dividend is a contract, so this year’s check cannot change',
     'If the company loses money, the exchange pays the old dividend instead',
     'Boards can raise dividends but are not allowed to cut them'],
    ['The yield can look high after the price already fell, and the payout can still be cut',
     'A high yield is a safety badge that means the price cannot fall further',
     'Yield only rises when the company is healthier, never after a drop',
     'Once yield is high, brokers must keep paying that cash if the firm stops'],
    ['You received $1 of cash and still lost more than that on the share price',
     'The $1 dividend cancels the $5 drop, so you are ahead for the season',
     'Dividends and price changes cannot happen in the same season',
     'A dividend refunds any price drop that prints in the following week'],
    ['Shareholders who own the stock when they are eligible for that payout',
     'Anyone who ever liked the brand, even with no shares in the account',
     'Only employees; outside owners cannot receive cash from the company',
     'Whoever sold the stock last year, because they created the dividend'],
    ['It may prefer to reinvest cash in the business instead of sending it out',
     'Growing companies are banned from paying dividends in their first decade',
     'Skipping dividends means the company has no cash and cannot invest',
     'If a company grows, dividends are paid automatically by the exchange'],
    ['Using the cash to buy more shares, which can then rise or fall',
     'Sending the cash back to the company as a required extra fee',
     'Locking the dividend at a fixed value that cannot change with price',
     'Converting the dividend into a loan the broker must repay at your cost'],
    ['Dividends are possible cash from a company; they can be cut, and prices can still fall',
     'Dividends are guaranteed cash, and paying one freezes the share price',
     'If a dividend is paid, that season’s price drop is reversed at the close',
     'Dividends replace the need to care about whether the shares lose value'],
]);

add(17, [
    ['A list and score that tracks a group of investments as one number',
     'A single company’s ticker that stands in for the whole economy',
     'A savings rate banks must pay, copied onto every stock overnight',
     'A law that freezes member prices so the group score cannot fall'],
    ['Both summarize a group so you can see an overall result, not each name',
     'A class average is one student; an index is also exactly one company',
     'Indexes hide the group and only show the single best member’s score',
     'Class averages and indexes are forecasts, not summaries of what happened'],
    ['A yardstick you compare a result against, not a promise of matching it',
     'A trophy you are owed if you hold any stock for a full month',
     'The official future return of your account, published in advance',
     'A nickname for cash, used when you do not want to say savings'],
    ['You lagged that yardstick this period; it does not make you a bad person',
     'A 3% gain while the index rose 9% is impossible, so one number is fake',
     'Lagging an index this period means you must close the practice account',
     'If you rose at all, you beat the index, because any plus is a win'],
    ['No. The index is a score; people buy funds or stocks that try to copy it',
     'Yes. Clicking the number on a website transfers that score into cash',
     'Yes. The index itself is a share you can hold like a single company',
     'No, because indexes cannot be copied; only private deals get a score'],
    ['They may include different members or follow different construction rules',
     'Two indexes are required to print the same change every session',
     'Disagreement means both indexes are closed and should be ignored',
     'If two scores differ, the higher one is the only legal market number'],
    ['It no longer fits that index’s rules; membership lists can change',
     'The company is deleted from the economy and cannot sell products',
     'Dropped members still count in the score, just with a hidden ticker',
     'Leaving an index converts the shares into a risk-free savings balance'],
    ['Yes. If enough members slump, the group score can slump too',
     'No. An index is an average, and averages are not allowed to fall',
     'No. Group scores only move on days when every member rises',
     'Yes, but a fall is later edited out so the benchmark stays positive'],
    ['That index’s group rose; other groups might have moved differently',
     'One index rising means every investment a person can buy also rose',
     'Headlines pick an index only when every market in the world is up',
     'If “the market” is up, cash, bonds, and small foreign stocks all rose'],
    ['An index is a group score used as a benchmark, and that score can fall',
     'An index is a group score that is insured never to print a down day',
     'An index is one company’s price, used as a nickname for all stocks',
     'Benchmarks are future promises, so an index cannot describe the past'],
]);

add(18, [
    ['About 500 large U.S. companies, not every business on earth',
     'Every public and private company in the world, equally weighted',
     '500 small foreign firms that have never listed in the United States',
     'The 500 newest startups, replaced each morning if a logo changes'],
    ['Bigger companies count more in the score than smaller members on the list',
     'Every member counts the same, no matter how large the company is',
     'Smaller companies count more, because they have more room to grow',
     'Weighting is by logo color, not by how large the company is'],
    ['The giant’s move usually pulls the overall score more than the small name',
     'The +5% small name cancels the giant’s −5% because the percents match',
     'Market-cap weighting ignores size, so both names tug the index equally',
     'A small member’s +5% counts double, which is how new names get noticed'],
    ['Small companies, many non-U.S. names, and other asset types sit outside it',
     'Nothing is missing; the S&P 500 is a complete map of all investing',
     'Only cash is missing; every stock in the world sits inside those 500',
     'Only bonds are missing; every company size and country is already in'],
    ['Many investors know it, so it is a shared yardstick for comparison',
     'It is the only legal benchmark, and other indexes cannot be used',
     'It predicts next year’s return, which is why people treat it as a plan',
     'It includes every asset, so beating it means you beat all possible mixes'],
    ['The past includes rises and deep drops; the future is not promised to copy it',
     'Fifty years of history is a contract that the next fifty will look the same',
     'Ugly drops in the chart are illustrations, not real index declines',
     'If a long chart ends higher, down years in the middle did not count'],
    ['Share price times the number of shares, used as a simple size idea',
     'Last year’s profit only, which is why small firms can outrank giants',
     'The CEO’s salary, which is how exchanges decide membership weight',
     'The number of stores, copied onto the index as a dollar figure'],
    ['The S&P 500 is a group score; a single stock is one company you chose',
     'Liking one stock is the same as holding the whole 500-name score',
     'A single stock is safer than the index because you can watch it closer',
     'The index is one ticker you buy at a store, just like a favorite brand'],
    ['Disagree. It has fallen in the past, and past returns are not a promise',
     'Agree. A well-known index is not allowed to print a down calendar year',
     'Agree, because “always” is how market-cap weighting is defined',
     'Disagree only about fees; the price path itself cannot go down'],
    ['It tracks about 500 large U.S. companies, weights giants more, and its past is not a promise',
     'It tracks every company on earth and is insured to rise every decade',
     'It is a single stock with 500 in the name, weighted like any other ticker',
     'It is a savings rate of 500 basis points, unrelated to company prices'],
]);

add(19, [
    ['Spread money across more than one investment instead of one name only',
     'Put everything into the single stock you researched the longest',
     'Trade every hour so no holding lasts long enough to be a risk',
     'Hold only cash, because cash is the definition of a diversified mix'],
    ['The one-stock mix takes the full collapse; the split mix takes a smaller hit from that name',
     'Both mixes lose the same $100, because collapse size ignores how you split',
     'The split mix still loses $100 on that name, just labeled as four tickets',
     'The one-stock mix is protected, because concentration is a safety style'],
    ['No. Diversification does not erase all risk; a broad drop can still hit many names',
     'Yes. If several holdings fall together, spreading is proven not to work',
     'Yes, unless you own more than ten names, which cannot fall in the same week',
     'No, and a bad week for four stocks means you actually owned only one'],
    ['Erase all risk or guarantee that the mix will finish with a profit',
     'Reduce how much one name can hurt the total if that name fails',
     'Spread money across more than a single investment in the backpack',
     'Limit the damage from one company’s collapse compared with going all-in'],
    ['The same shock can hit both at once if they rely on the same kind of business',
     'Two companies cannot share a problem, so any two names are fully spread',
     'Sameness is required for diversification; different businesses cancel the benefit',
     'Product twins are treated as an index, so one collapse cannot touch both'],
    ['Concentration can win or lose big on one name; spreading shrinks that one-name swing',
     'Concentration always loses, and spreading always wins, in every period',
     'Spreading makes one-name swings larger, which is why people concentrate',
     'The two words mean the same mix; only the lesson title changes'],
    ['Not letting one accident wreck everything you packed in the same place',
     'Buying the most expensive basket because price equals safety',
     'Keeping all eggs together so you can watch them with one glance',
     'Using a basket as a nickname for a single stock you like a lot'],
    ['One winner does not erase the times a single name also halves; spreading is about those times',
     'A double on one name proves mixes are unnecessary from then on',
     'If a concentrated bet won once, later halves on that style cannot happen',
     'Laughing at mixes is correct whenever any one stock has a good year'],
    ['No. A few different companies is already more spread than one; wider mixes can come later',
     'Yes. Diversification does not start until you hold at least 500 names',
     'Yes. Two or three companies still count as the same as one stock',
     'No, because even one stock is diversified if the company has many products'],
    ['Diversification reduces the hit from one investment doing badly; it does not remove all risk',
     'Diversification removes all risk, which is why mixed portfolios cannot fall',
     'Diversification only works if every holding rises on the same day',
     'Diversification means owning more shares of the same single company'],
]);

add(20, [
    ['A pretend collection of investments you use for learning, not real cash',
     'A live brokerage account funded with your lunch money and bills',
     'A list of headlines, with no holdings you can actually practice on',
     'A guaranteed contest purse that pays you if a practice ticker rises'],
    ['Practice is a rehearsal; it does not prove what you would do with real money',
     'A strong practice month is treated as proof you would match it live',
     'Practice and live results are the same, because the quotes look similar',
     'If you can click in a simulator, real-money skill is already finished'],
    ['That is short-term luck in a classroom, not a promise you would repeat with real cash',
     'A 40% two-day jump is the normal pace you should expect with live money',
     'Viral practice wins are copied into real accounts as a locked return',
     'If it happened in practice, brokers must let you withdraw that gain'],
    ['No. Money you need tomorrow still belongs in a saving idea, even while you learn',
     'Yes. Practice stocks cannot fall, so lunch money is a safe classroom tool',
     'Yes, because jumpy names teach faster when the cash is truly needed soon',
     'No, unless the practice ticker is famous, which makes next-day cash safe'],
    ['A small mix lets you feel spreading, not only one-name weather',
     'One company is enough, because practice accounts cannot concentrate',
     'Starting with many names is banned until you finish every lesson first',
     'Diversification only applies to live money, so practice should be one ticker'],
    ['Add what the company sells, and why people might keep paying, knowing you can still be wrong',
     'Keep the logo-only reason; design is the strongest long-term signal',
     'Replace the reason with a screenshot of someone else’s gain last week',
     'Write that you cannot be wrong if the practice money is not real'],
    ['You can learn by checking a small mix over days without frantic clicking',
     'You must trade every hour or the simulator will not count as studying',
     'Learning only happens on days you buy and sell at least five times',
     'If you do not click constantly, the mix freezes and you cannot observe risk'],
    ['Two names will not copy an index of about 500 large U.S. companies, and that is expected',
     'Two practice stocks are required to track the S&P 500 almost tick for tick',
     'If your two names differ from the index, the practice account is broken',
     'A two-stock mix is another name for the S&P 500 in a student simulator'],
    ['Notice the risk without real bills, then review the mix and your reasons',
     'Delete the account, because a 15% practice drop means you cannot learn',
     'Add lunch money next, so the drop feels more realistic and instructive',
     'Assume the 15% will reverse tomorrow, because practice losses are refunded'],
    ['The simulator is a rehearsal: pretend money, real ideas, and no live-performance promise',
     'The simulator is a live account, so practice gains can be withdrawn as cash',
     'The simulator promises that a careful student will match those results live',
     'The simulator is only a quiz; holdings never change once the lesson starts'],
]);

export const byLesson = L;
